const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os'),vm=require('node:vm'),{createRequire}=require('node:module');
const {startService}=require('../server.cjs'),{createWorkbench}=require('../../desktop/src/services/workbench.cjs');
const correction=require('../../desktop/src/ai-corrections.cjs');
const profile={schemaVersion:1,demo:false,values:{basic:[{name:'PRIVATE_FACT',email:'private@example.invalid'}]}};
const candidate={id:'f1',label:'姓名',labels:['姓名'],headings:[],section:'basic',tag:'input',type:'text',selector:'#name',frameUrl:'https://example.invalid/apply',frameIndex:0,hasValue:true,observedValue:'PRIVATE_CURRENT'};
const valid={mappings:[{id:'f1',group:'basic',key:'name',confidence:.95,reason:'姓名'}]};
function scope(){const frame={};frame.circular=frame;return{mode:'correction',url:candidate.frameUrl,applicationId:'a1',profileStamp:correction.profileStamp(profile),candidates:[{...candidate,frame}],allowedMappings:[{id:'f1',targets:[{group:'basic',key:'name'}]}]};}
test('independent hosted correction HTTP settlement, replay, failure, history and account isolation',async t=>{
 const root=fs.mkdtempSync(path.join(os.tmpdir(),'correction-http-review-'));let mode='valid',calls=0,release;
 const server=startService({directory:path.join(root,'server'),invite:'review-invite',prices:{'field-correction':3,'field-mapping':2},processJob:async(kind,p)=>{calls++;assert.equal(kind,'field-correction');assert.deepEqual(Object.keys(p),['fields','allowedMappings']);assert(!JSON.stringify(p).includes('PRIVATE'));if(mode==='empty')return{mappings:[]};if(mode==='range')return{mappings:[{...valid.mappings[0],key:'email'}]};if(mode==='throw')throw Error('provider failure');if(mode==='slow')return new Promise(resolve=>{release=()=>resolve(valid);});return valid;}});
 await new Promise(resolve=>server.server.listen(0,'127.0.0.1',resolve));const baseUrl=`http://127.0.0.1:${server.server.address().port}`,workspace=path.join(root,'workspace');fs.mkdirSync(path.join(workspace,'知识库'),{recursive:true});fs.writeFileSync(path.join(workspace,'知识库/profile.json'),JSON.stringify(profile));const secret=new Map(),vault={get:k=>secret.get(k),set:(k,v)=>secret.set(k,v),remove:k=>secret.delete(k)};let wb=createWorkbench(workspace,{vault});
 t.after(async()=>{wb.close();await server.close();fs.rmSync(root,{recursive:true,force:true});});
 wb.hosted.configure({baseUrl});await wb.hosted.login({email:'review-a@example.invalid',password:'review-password-12345',register:true,invite:'review-invite'});const accountId=(await wb.hosted.account()).account.id;server.jobs.grant(accountId,30,'review-seed');
 const q=await wb.hosted.quoteMapping(scope());assert.equal((await wb.hosted.account()).account.balance,30);assert.equal(Object.hasOwn(wb.hosted.mappingJob(q.id,'correction').scope.candidates[0],'frame'),false);
 await Promise.all([wb.hosted.start({id:q.id,confirmed:true}),wb.hosted.start({id:q.id,confirmed:true})]);let job=await wb.hosted.refresh(q.id);assert.equal(job.status,'ready');assert.equal(calls,1);assert.equal((await wb.hosted.account()).account.balance,27);assert.equal(wb.hosted.mappingJobs().length,0);assert.equal(wb.hosted.mappingJobs('correction').length,1);assert.throws(()=>wb.hosted.mappingJob(q.id),/不是/);
 for(const failure of ['empty','range','throw']){mode=failure;const failed=await wb.hosted.quoteMapping(scope());await wb.hosted.start({id:failed.id,confirmed:true});job=await wb.hosted.refresh(failed.id);assert.equal(job.status,'failed',failure);const account=(await wb.hosted.account()).account;assert.equal(account.balance,27);assert.equal(account.reserved,0);}
 mode='slow';const slow=await wb.hosted.quoteMapping(scope());await wb.hosted.start({id:slow.id,confirmed:true});assert.equal((await wb.hosted.account()).account.reserved,3);await wb.hosted.cancel(slow.id);release();await new Promise(r=>setTimeout(r,10));assert.equal((await wb.hosted.refresh(slow.id)).status,'cancelled');assert.equal((await wb.hosted.account()).account.balance,27);assert.equal((await wb.hosted.account()).account.reserved,0);
 mode='valid';wb.close();wb=createWorkbench(workspace,{vault});assert.equal(wb.hosted.mappingJob(q.id,'correction').suggestions[0].key,'name');assert.equal(wb.hosted.mappingJobs('correction').length,5);await wb.hosted.start({id:q.id,confirmed:true});assert.equal((await wb.hosted.account()).account.balance,27);
 const tokenA=secret.get('hosted-token');await wb.hosted.login({email:'review-b@example.invalid',password:'review-password-12345',register:true,invite:'review-invite'});assert.equal(wb.hosted.mappingJobs('correction').length,0);assert.throws(()=>wb.hosted.mappingJob(q.id,'correction'),/账号/);const read=await fetch(baseUrl+'/jobs/'+job.remoteId,{headers:{Authorization:'Bearer '+secret.get('hosted-token')}});assert.notEqual(read.status,200);assert.notEqual(secret.get('hosted-token'),tokenA);
 await wb.hosted.login({email:'review-a@example.invalid',password:'review-password-12345'});const cancelled=await wb.hosted.quoteMapping(scope());const beforeCalls=calls;const offline=require('../../desktop/src/services/hosted.cjs').createHosted(wb.store,wb.facts,{vault,fetchImpl:async()=>{throw Error('network must not be used');}});assert.equal((await offline.cancel(cancelled.id)).status,'cancelled');assert.equal((await offline.start({id:cancelled.id,confirmed:true})).status,'cancelled');offline.close();assert.equal(calls,beforeCalls);assert.equal((await wb.hosted.account()).account.balance,27);
});
test('main IPC refuses paid start after current value or profile changed, before hosted request',async()=>{
 const filename=path.resolve(__dirname,'../../desktop/src/main.cjs'),source=fs.readFileSync(filename,'utf8');const block=source.slice(source.indexOf("  handle('ai-correction'"),source.indexOf("  handle('ai-scope'"));let handler,starts=0,current=structuredClone(profile),scan={url:candidate.frameUrl,items:[{...candidate,observedValue:'USER_EDIT'}]};const job={id:'local',scope:scope()};
 const context={handle:(_name,fn)=>{handler=fn;},busy:false,teaching:{active:false},aiPageEpoch:0,activeApplicationId:'a1',profile:null,push:()=>{},executionProfile:()=>current,getPage:async()=>({url:()=>candidate.frameUrl}),scanPage:async()=>scan,workbench:{hosted:{mappingJob:()=>job,start:async()=>{starts++;return{status:'ready'};}}},require:createRequire(filename),Date};vm.runInNewContext(block,context);
 await assert.rejects(handler({action:'start',id:'local',confirmed:true}),/变化/);assert.equal(starts,0);
 scan={url:candidate.frameUrl,items:[candidate]};current={...profile,changed:true};await assert.rejects(handler({action:'start',id:'local',confirmed:true}),/变化/);assert.equal(starts,0);
 current=profile;await handler({action:'start',id:'local',confirmed:true});assert.equal(starts,1);
});
test('field correction has no implicit production price',async()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'correction-price-review-'));const service=startService({directory:root,processJob:async()=>valid});try{assert.throws(()=>service.jobs.quote('no-account',{kind:'field-correction',payload:{}}),/未定价|未开放/);}finally{await service.close();fs.rmSync(root,{recursive:true,force:true});}});
test('allowed correction targets require distinct local facts and processor receives no fact values',async()=>{
 const exact={...candidate,observedValue:'PRIVATE_FACT'},allowed=correction.allowedMappings([exact],profile,candidate.frameUrl)[0].targets;assert(!allowed.some(t=>t.key==='name'));assert(allowed.some(t=>t.key==='email'));
 const absent={...candidate,section:'projects'};assert.equal(correction.allowedMappings([absent],profile,candidate.frameUrl)[0].targets.length,0);
 const {validatePayload,createProcessor}=require('../processors.cjs'),payload=validatePayload('field-correction',{fields:[candidate],allowedMappings:scope().allowedMappings,profile,currentValue:'PRIVATE_CURRENT'});let input;
 const process=createProcessor({},{invoke:async(_config,args)=>{input=args.input;return valid;}});const result=await process('field-correction',payload,{signal:new AbortController().signal});assert.equal(result.mappings[0].key,'name');assert(!JSON.stringify(input).includes('PRIVATE'));assert(!JSON.stringify(input).includes('private@example.invalid'));assert.deepEqual(input.allowedMappings,scope().allowedMappings);assert(Array.isArray(input.catalog));
});
