const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os');
const {startService}=require('../server.cjs'),{createWorkbench}=require('../../desktop/src/services/workbench.cjs');
test('native client -> HTTP auth -> quote -> reserve/deliver -> local briefing and retained balance',async t=>{
 const root=fs.mkdtempSync(path.join(os.tmpdir(),'hosted-e2e-')),service=startService({directory:path.join(root,'server'),invite:'test-invite',prices:{briefing:3},processJob:async(_kind,p)=>({sources:[{id:'S1',url:p.urls[0],text:'官网介绍产品面向开发者。',capturedAt:new Date().toISOString()}],facts:[{sourceId:'S1',quote:'产品面向开发者'}],hypotheses:[],questions:['团队的目标是什么？']})});
 await new Promise(r=>service.server.listen(0,'127.0.0.1',r));const workspace=path.join(root,'workspace');fs.mkdirSync(path.join(workspace,'知识库'),{recursive:true});fs.writeFileSync(path.join(workspace,'知识库/profile.json'),JSON.stringify({schemaVersion:1,demo:false,values:{basic:[{}]}}));const secrets=new Map(),wb=createWorkbench(workspace,{vault:{get:id=>secrets.get(id),set:(id,v)=>secrets.set(id,v),remove:id=>secrets.delete(id)}});
 t.after(async()=>{wb.close();await service.close();fs.rmSync(root,{force:true,recursive:true});});
 wb.hosted.configure({baseUrl:`http://127.0.0.1:${service.server.address().port}`});await wb.hosted.login({email:'test@example.invalid',password:'test-password-12345',register:true,invite:'test-invite'});const account=await wb.hosted.account();service.jobs.grant(account.account.id,10,'test-grant');
 const organization=wb.workflow.organization({name:'测试公司'}),event=wb.workflow.event({organizationId:organization.id,title:'面试',type:'interview'});const quoted=await wb.hosted.quoteBriefing({eventId:event.id,urls:['https://example.com/product'],confirmed:true});assert.equal(quoted.units,3);assert.equal((await wb.hosted.account()).account.available,10);
 let job=await wb.hosted.start({id:quoted.id,confirmed:true});for(let i=0;job.status!=='ready'&&i<20;i++){await new Promise(r=>setTimeout(r,5));job=await wb.hosted.refresh(quoted.id);}assert.equal(job.status,'ready');assert.equal(wb.store.list('briefings').length,1);await wb.hosted.start({id:quoted.id,confirmed:true});assert.equal((await wb.hosted.account()).account.available,7);assert.equal(wb.store.list('briefings').length,1);assert.ok(!JSON.stringify(wb.snapshot()).includes(secrets.get('hosted-token')));await wb.hosted.logout();assert.equal(wb.hosted.config().connected,false);assert.equal(wb.store.list('briefings').length,1);
});
