const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os');
const {startService}=require('../server.cjs'),{createWorkbench}=require('../../desktop/src/services/workbench.cjs'),{createProcessor,validatePayload}=require('../processors.cjs');
const text='面试地点：北京办公室。日期：明天下午三点',valid={changes:[{key:'location',value:'北京办公室',quote:'面试地点：北京办公室'}]};
test('independent hosted mail HTTP billing, failures, stale scope, cancellation, restart and account isolation',async t=>{
 const root=fs.mkdtempSync(path.join(os.tmpdir(),'mail-http-review-'));let mode='valid',calls=0,release;
 const service=startService({directory:path.join(root,'server'),invite:'mail-review',prices:{'mail-parse':4},processJob:async(kind,p)=>{calls++;assert.equal(kind,'mail-parse');assert.deepEqual(p,{text,offset:''});if(mode==='empty')return{changes:[]};if(mode==='fabricated')return{changes:[{key:'location',value:'上海',quote:'面试地点：北京办公室'}]};if(mode==='unclear')return{changes:[{key:'startsAt',value:'明天下午三点',quote:'日期：明天下午三点'}]};if(mode==='error')throw Error('provider failure');if(mode==='slow')return new Promise(resolve=>{release=()=>resolve(valid);});return valid;}});
 await new Promise(r=>service.server.listen(0,'127.0.0.1',r));const workspace=path.join(root,'workspace');fs.mkdirSync(path.join(workspace,'知识库'),{recursive:true});fs.writeFileSync(path.join(workspace,'知识库/profile.json'),JSON.stringify({schemaVersion:1,demo:false,values:{basic:[{name:'PRIVATE_PROFILE'}]}}));const secrets=new Map(),vault={get:k=>secrets.get(k),set:(k,v)=>secrets.set(k,v),remove:k=>secrets.delete(k)};let wb=createWorkbench(workspace,{vault});t.after(async()=>{wb.close();await service.close();fs.rmSync(root,{recursive:true,force:true});});
 wb.store.put('messages',{id:'m',subject:'PRIVATE_SUBJECT',text:'PRIVATE_PREFIX\n'+text+'\nPRIVATE_SUFFIX',from:'PRIVATE_FROM',attachments:[{name:'PRIVATE_ATTACHMENT'}],password:'PRIVATE_PASSWORD'});wb.store.put('confirmations',{id:'c',kind:'mail_event',messageId:'m',status:'pending',proposal:{title:'原始草稿',type:'other'}});
 wb.hosted.configure({baseUrl:`http://127.0.0.1:${service.server.address().port}`});await wb.hosted.login({email:'mail-a@example.invalid',password:'review-password-12345',register:true,invite:'mail-review'});const accountId=(await wb.hosted.account()).account.id;service.jobs.grant(accountId,30,'mail-seed');
 const input=()=>({confirmationId:'c',revision:wb.store.get('confirmations','c').revision,text,offset:'',confirmed:true,fingerprint:wb.hosted.mailConfig().fingerprint});
 for(const patch of [{text:'not original'},{confirmed:false},{fingerprint:'stale'},{revision:999}])await assert.rejects(wb.hosted.quoteMail({...input(),...patch}));assert.equal(calls,0);
 const q=await wb.hosted.quoteMail(input());assert.equal((await wb.hosted.account()).account.balance,30);assert.equal(calls,0);assert.deepEqual(wb.hosted.mailJob(q.id).payload,{text,offset:''});
 await Promise.all([wb.hosted.start({id:q.id,confirmed:true}),wb.hosted.start({id:q.id,confirmed:true})]);let job=await wb.hosted.refresh(q.id);assert.equal(job.status,'ready');assert.equal(calls,1);assert.equal((await wb.hosted.account()).account.balance,26);
 const review=wb.hosted.mailResult(q.id);assert.equal(review.changes[0].normalized,'北京办公室');assert.equal(wb.store.get('confirmations','c').proposal.title,'原始草稿');assert.equal(wb.store.list('events').length,0);
 for(const failure of ['empty','fabricated','unclear','error']){mode=failure;const f=await wb.hosted.quoteMail(input());await wb.hosted.start({id:f.id,confirmed:true});assert.equal((await wb.hosted.refresh(f.id)).status,'failed',failure);const a=(await wb.hosted.account()).account;assert.equal(a.balance,26);assert.equal(a.reserved,0);}
 mode='slow';const slow=await wb.hosted.quoteMail(input());await wb.hosted.start({id:slow.id,confirmed:true});assert.equal((await wb.hosted.account()).account.reserved,4);await wb.hosted.cancel(slow.id);release();await new Promise(r=>setTimeout(r,10));assert.equal((await wb.hosted.refresh(slow.id)).status,'cancelled');assert.equal((await wb.hosted.account()).account.balance,26);
 service.jobs.refund(accountId,job.remoteId);service.jobs.refund(accountId,job.remoteId);assert.equal((await wb.hosted.refresh(q.id)).status,'refunded');assert.equal((await wb.hosted.account()).account.balance,30);
 wb.close();wb=createWorkbench(workspace,{vault});assert.equal(wb.hosted.mailJobs('c').length,6);assert.equal(wb.hosted.mailResult(q.id).id,review.id);assert.equal(wb.hosted.mappingJobs().length,0);const savedToken=secrets.get('hosted-token');secrets.delete('hosted-token');assert.equal(wb.hosted.mailJobs('c').length,0);assert.equal(wb.mailAI.list('c').length,0);secrets.set('hosted-token',savedToken);
 await wb.hosted.login({email:'mail-b@example.invalid',password:'review-password-12345',register:true,invite:'mail-review'});assert.equal(wb.hosted.mailJobs('c').length,0);assert.throws(()=>wb.hosted.mailResult(q.id),/账号/);assert.equal(wb.mailAI.list('c').some(j=>j.id===review.id),false,'unadopted hosted review must not bypass account isolation');assert.throws(()=>wb.mailAI.adopt({jobId:review.id,ids:[review.changes[0].id],confirmed:true}),/账号|不可|不存在/);
 await wb.hosted.login({email:'mail-a@example.invalid',password:'review-password-12345'});const stale=await wb.hosted.quoteMail(input()),beforeCalls=calls,c=wb.store.get('confirmations','c');wb.store.put('confirmations',{...c,proposal:{...c.proposal,title:'手改草稿'}},{expectedRevision:c.revision});await assert.rejects(wb.hosted.start({id:stale.id,confirmed:true}),/变化|处理/);assert.equal(calls,beforeCalls);assert.equal((await wb.hosted.account()).account.balance,30);assert.throws(()=>wb.hosted.mailResult(q.id),/变化|处理/);
 mode='valid';const fresh=await wb.hosted.quoteMail(input());await wb.hosted.start({id:fresh.id,confirmed:true});await wb.hosted.refresh(fresh.id);const r=wb.hosted.mailResult(fresh.id),adopted=wb.mailAI.adopt({jobId:r.id,ids:[r.changes[0].id],confirmed:true});assert.equal(adopted.status,'pending');assert.equal(adopted.proposal.location,'北京办公室');assert.equal(adopted.proposal.title,'手改草稿');assert.equal(adopted.proposal.confidence,'needs_review');assert.equal(wb.store.list('events').length,0);assert.equal(wb.store.list('tasks').length,0);
});
test('mail processor sees only selected text/field catalog; offset only normalizes locally/server-side',async()=>{
 const payload=validatePayload('mail-parse',{text,offset:'',attachments:['PRIVATE'],profile:'PRIVATE',password:'PRIVATE'});assert.deepEqual(payload,{text,offset:''});let received;const processor=createProcessor({},{invoke:async(_config,args)=>{received=args;return valid;}});const output=await processor('mail-parse',payload,{signal:new AbortController().signal});assert.deepEqual(Object.keys(received.input).sort(),['fields','text']);assert.equal(received.input.text,text);assert(!JSON.stringify(received.input).includes('PRIVATE'));assert.deepEqual(output,valid);
});
test('mail parsing has no implicit price',async()=>{const directory=fs.mkdtempSync(path.join(os.tmpdir(),'mail-price-review-')),service=startService({directory,processJob:async()=>valid});try{assert.throws(()=>service.jobs.quote('unused',{kind:'mail-parse',payload:{text,offset:''}}),/未定价|未开放/);}finally{await service.close();fs.rmSync(directory,{recursive:true,force:true});}});
test('historical mail UI renders adopted or stale results without adopt controls',async()=>{
 const vm=require('node:vm'),source=fs.readFileSync(path.resolve(__dirname,'../../desktop/src/ui/workbench.js'),'utf8'),block=source.slice(source.indexOf('  async function mailAIReview('),source.indexOf('  async function mailAIHostedStatus('));let html,submitHandler,calls=0;
 const context={state:{confirmations:[{id:'c',revision:1,status:'pending'}]},h:String,mailAIValue:c=>c.normalized,submit:()=>'<button type="submit">采用</button>',modal:async(_title,_subtitle,body,handler)=>{html=body;submitHandler=handler;},api:async()=>{calls++;},mailConfirmation:()=>{}};vm.runInNewContext(block,context);
 const job={id:'review',confirmationId:'c',confirmationRevision:1,status:'ready',changes:[{id:'x',key:'location',label:'地点',value:'办公室',normalized:'办公室',quote:'办公室',adoptable:true}]};
 await context.mailAIReview(job);assert(html.includes('type="submit"'));
 for(const setup of [()=>context.state.confirmations[0].status='confirmed',()=>{context.state.confirmations[0].status='pending';context.state.confirmations[0].revision=2;},()=>{context.state.confirmations[0].revision=1;job.status='adopted';}]){setup();await context.mailAIReview(job);assert(!html.includes('type="submit"'));assert(html.includes('disabled'));await assert.rejects(submitHandler({},{}),/仅供查看/);}
 assert.equal(calls,0);
});
