const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os');
const {startService}=require('../server.cjs'),{createWorkbench}=require('../../desktop/src/services/workbench.cjs');
test('selected scope -> native HTTP -> scheduled baseline/change/failure -> pause/remove; no profile uploads',async t=>{
 const root=fs.mkdtempSync(path.join(os.tmpdir(),'monitor-e2e-'));let now=Date.now(),title='开发工程师',failure=false,calls=0;
 const service=startService({directory:path.join(root,'server'),invite:'test-invite',monitoringEnabled:true,monitoring:{autoStart:false,clock:()=>now,reader:async url=>{calls++;if(failure)throw Error('secret raw transport error');return{url,body:JSON.stringify({'@type':'JobPosting',title,hiringOrganization:{name:'样本公司'}})};}}});
 await new Promise(r=>service.server.listen(0,'127.0.0.1',r));const workspace=path.join(root,'workspace');fs.mkdirSync(path.join(workspace,'知识库'),{recursive:true});fs.writeFileSync(path.join(workspace,'知识库/profile.json'),JSON.stringify({schemaVersion:1,demo:false,values:{basic:[{name:'private name'}]}}));const secrets=new Map(),wb=createWorkbench(workspace,{vault:{get:id=>secrets.get(id),set:(id,v)=>secrets.set(id,v),remove:id=>secrets.delete(id)}});
 t.after(async()=>{wb.close();await service.close();fs.rmSync(root,{force:true,recursive:true});});
 wb.hosted.configure({baseUrl:`http://127.0.0.1:${service.server.address().port}`});await wb.hosted.login({email:'test@example.invalid',password:'test-password-12345',register:true,invite:'test-invite'});
 await assert.rejects(wb.command({action:'cloud-monitoring',data:{action:'add',label:'公司',url:'https://example.com/jobs'}}));
 const input={action:'add',label:'公司',url:'https://example.com/jobs?batch=2026',confirmed:true,profile:'must not send',password:'must not send'},row=await wb.command({action:'cloud-monitoring',data:input});assert.equal((await wb.command({action:'cloud-monitoring',data:input})).id,row.id);assert.equal(calls,0);
 await service.monitoring.tick();let snapshot=await wb.command({action:'cloud-monitoring',data:{action:'list'}});assert.equal(snapshot.monitors[0].status,'success');assert.equal(snapshot.notices.length,0);assert.equal(calls,1);await service.monitoring.tick();assert.equal(calls,1);
 title='数据工程师';now+=86400000;await service.monitoring.tick();snapshot=await wb.hosted.monitoring();assert.equal(snapshot.notices.length,1);assert.equal(snapshot.notices[0].kind,'changed');await wb.hosted.monitoring('read',{id:snapshot.notices[0].id});assert.equal((await wb.hosted.monitoring()).notices[0].read,1);
 failure=true;now+=86400000;await service.monitoring.tick();const success=snapshot.monitors[0].last_success;now+=86400000;await service.monitoring.tick();snapshot=await wb.hosted.monitoring();assert.equal(snapshot.notices.filter(n=>n.kind==='failed').length,1);assert.equal(snapshot.monitors[0].last_success,success);assert.ok(!JSON.stringify(snapshot).includes('secret'));
 const paused=await wb.hosted.monitoring('update',{id:row.id,revision:row.revision,enabled:false}),before=calls;now+=86400000;await service.monitoring.tick();assert.equal(calls,before);await assert.rejects(wb.hosted.monitoring('remove',{id:row.id,revision:row.revision}));await wb.hosted.monitoring('remove',{id:row.id,revision:paused.revision});snapshot=await wb.hosted.monitoring();assert.equal(snapshot.monitors.length,0);assert.equal(snapshot.notices.length,0);
});
