'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const {openDatabase}=require('../store.cjs'),{createMonitoring}=require('../monitoring.cjs');
const {publicAddress}=require('../../desktop/src/services/public-page.cjs');
const DAY=86400000;
function setup(t){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'monitor-review-')),db=openDatabase(dir);for(const id of ['a','b'])db.run('INSERT INTO accounts(id,email,password,salt,created_at) VALUES(?,?,?,?,?)',id,id+'@example.com','unused','unused',new Date().toISOString());const instances=[];let time=1000000000000;const service=options=>{const m=createMonitoring(db,{enabled:true,autoStart:false,clock:()=>time,...options});instances.push(m);return m;};t.after(()=>{instances.forEach(m=>m.close());db.close();fs.rmSync(dir,{recursive:true,force:true});});return{db,service,advance:delta=>time+=delta,now:()=>time};}
const add=(m,account='a',suffix='one')=>m.add(account,{confirmed:true,label:'Company '+suffix,url:'https://recruit.example/'+suffix});
const body=(title='Engineer')=>JSON.stringify({'@type':'JobPosting',title,hiringOrganization:{name:'Company'},description:'Role description',identifier:'job-1',url:'https://recruit.example/vacancy'});
const page=(url,title)=>({url,body:body(title)});

test('monitor review: consent, public URL restrictions, per-account cap and duplicate add',t=>{const {service}=setup(t),m=service();assert.throws(()=>m.add('a',{label:'Company',url:'https://recruit.example',confirmed:false}),/确认/);for(const url of ['http://recruit.example','https://127.0.0.1','https://localhost','https://name:password@recruit.example','https://recruit.example:8443'])assert.throws(()=>m.add('a',{label:'Company',url,confirmed:true}));for(const address of ['127.0.0.1','10.0.0.1','169.254.169.254','192.168.1.1','172.16.0.1','100.64.0.1','::1'])assert.equal(publicAddress(address),false);const first=add(m);assert.equal(add(m).id,first.id);for(let i=1;i<20;i++)add(m,'a',String(i));assert.throws(()=>add(m,'a','twenty-first'),/20/);assert.doesNotThrow(()=>add(m,'b'));assert.equal(m.list('a').monitors.length,20);assert.equal(m.list('b').monitors.length,1);});

test('monitor review: account isolation applies to pause, removal and notification read',async t=>{const {service}=setup(t),m=service({reader:async()=>{throw Error('private provider details');}}),row=add(m);await m.tick();const notice=m.list('a').notices[0];assert.equal(m.list('b').notices.length,0);assert.throws(()=>m.update('b',{id:row.id,revision:row.revision,enabled:false}),/不存在/);assert.throws(()=>m.remove('b',{id:row.id,revision:row.revision}),/不存在/);assert.throws(()=>m.read('b',{id:notice.id}),/不存在/);assert.doesNotMatch(m.list('a').monitors[0].error,/private provider/);assert.equal(m.read('a',{id:notice.id}).read,true);});

test('monitor review: structured change notices are deduplicated and empty pages remain uncertain',async t=>{const {service,advance}=setup(t);let title='Engineer',empty=false,calls=0;const m=service({reader:async url=>{calls++;return empty?{url,body:'<html>No structured jobs</html>'}:page(url,title);}});add(m);await Promise.all([m.tick(),m.tick()]);assert.equal(calls,1);assert.equal(m.list('a').notices.length,0);advance(DAY);title='Researcher';await m.tick();assert.equal(m.list('a').notices.filter(n=>n.kind==='changed').length,1);advance(DAY);await m.tick();assert.equal(m.list('a').notices.length,1);advance(DAY);empty=true;await m.tick();assert.equal(m.list('a').monitors[0].status,'manual_required');assert.equal(m.list('a').notices.filter(n=>n.kind==='changed').length,1);});

test('monitor review: pause and delete discard even reader results that ignore abort',async t=>{for(const action of ['update','remove']){const {service}=setup(t);let resolve;const m=service({reader:url=>new Promise(r=>resolve=()=>r(page(url)))}),row=add(m),running=m.tick();m[action]('a',{id:row.id,revision:row.revision,enabled:false});resolve();await running;const list=m.list('a');assert.equal(list.notices.length,0);if(action==='remove')assert.equal(list.monitors.length,0);else assert.equal(list.monitors[0].status,'paused');}});

test('monitor review: service recreation recovers incomplete checks without accepting old response',async t=>{const {service,advance}=setup(t);let resolve;const old=service({reader:url=>new Promise(r=>resolve=()=>r(page(url,'Old result')))});add(old);const pending=old.tick();old.close();const current=service({reader:async url=>page(url,'Fresh result')});assert.equal(current.list('a').monitors[0].status,'interrupted');resolve();await pending;await current.tick();assert.equal(current.list('a').monitors[0].status,'interrupted','restart must not bypass daily attempt limit');advance(DAY);await current.tick();assert.equal(current.list('a').monitors[0].status,'success');assert.equal(current.list('a').notices.filter(n=>n.kind==='recovered').length,1);});

test('monitor review: global service disable preserves user ability to pause and remove',t=>{const {service}=setup(t),enabled=service(),row=add(enabled);enabled.close();const disabled=service({enabled:false});const paused=disabled.update('a',{id:row.id,revision:row.revision,enabled:false});assert.equal(paused.enabled,0);assert.equal(disabled.remove('a',{id:paused.id,revision:paused.revision}).removed,true);assert.throws(()=>add(disabled,'a','new'),/启用/);});

test('monitor review: repeat enable and pause/resume cannot bypass daily check limit',async t=>{const {service}=setup(t);let calls=0;const m=service({reader:async url=>{calls++;return page(url);}});add(m);await m.tick();let row=m.list('a').monitors[0];row=m.update('a',{id:row.id,revision:row.revision,enabled:true});await m.tick();assert.equal(calls,1,'repeat enable must not re-fetch today');row=m.update('a',{id:row.id,revision:row.revision,enabled:false});m.update('a',{id:row.id,revision:row.revision,enabled:true});await m.tick();assert.equal(calls,1,'pause/resume must preserve scheduled daily limit');});

test('monitor review: deleted and recreated URL retains its daily fetch limit',async t=>{const {service,advance}=setup(t);let calls=0;const m=service({reader:async url=>{calls++;return page(url);}}),row=add(m);await m.tick();m.remove('a',{id:row.id,revision:row.revision});add(m);await m.tick();assert.equal(calls,1);advance(DAY);await m.tick();assert.equal(calls,2);});

test('monitor review: account daily budget survives page rotation and does not block other accounts',async t=>{const {service}=setup(t);let calls=0;const m=service({reader:async url=>{calls++;return page(url);}});for(let i=0;i<20;i++)add(m,'a',String(i));await m.tick();assert.equal(calls,20);for(const row of m.list('a').monitors)m.remove('a',{id:row.id,revision:row.revision});add(m,'a','replacement');await m.tick();assert.equal(calls,20);add(m,'b','other-account');await m.tick();assert.equal(calls,21);assert.equal(m.list('a').monitors[0].status,'pending');assert.equal(m.list('b').monitors[0].status,'success');});

test('monitor review: failure notice is emitted on transition and deduplicated until recovery',async t=>{const {service,advance}=setup(t);let fails=true;const m=service({reader:async url=>{if(fails)throw Error('connection failed');return page(url);}});add(m);await m.tick();advance(DAY);await m.tick();assert.equal(m.list('a').notices.length,1);assert.equal(m.list('a').notices[0].kind,'failed');fails=false;advance(DAY);await m.tick();assert.equal(m.list('a').notices.filter(n=>n.kind==='recovered').length,1);});
