'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),{createHmac}=require('node:crypto');
const {openDatabase}=require('../store.cjs'),{createJobs}=require('../jobs.cjs'),{createPayments}=require('../payments.cjs'),{startService}=require('../server.cjs');
const {validatePayload,validateResult}=require('../processors.cjs');
const payload={fields:[{id:'f',label:'School',currentValue:''}],facts:[{id:'s',label:'School',value:'Verified school'}]};
const tick=()=>new Promise(resolve=>setImmediate(resolve));
function setup(t){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'hosted-review-')),db=openDatabase(dir);for(const id of ['a','b'])db.run('INSERT INTO accounts(id,email,password,salt,balance,reserved,created_at) VALUES(?,?,?,?,?,?,?)',id,id+'@example.com','unused','unused',100,0,new Date().toISOString());t.after(()=>{db.close();fs.rmSync(dir,{recursive:true,force:true});});return db;}
function jobs(db,processJob){return createJobs(db,{prices:{'field-suggestions':10},validatePayload,validateResult,processJob});}
function start(j,account='a',requestId='request_123'){const q=j.quote(account,{kind:'field-suggestions',payload});return j.start(account,{kind:'field-suggestions',payload,confirmed:true,quoteId:q.id,requestId});}
function paymentOptions(extra={}){return{secretKey:'sk_test_fake',webhookSecret:'whsec_fake',packs:[{id:'small',units:50,amount:100,currency:'usd'}],successUrl:'https://merchant.example/success',cancelUrl:'https://merchant.example/cancel',...extra};}
function signed(p,event){const body=Buffer.from(JSON.stringify(event)),ts=String(Math.floor(Date.now()/1000)),signature=createHmac('sha256','whsec_fake').update(ts+'.').update(body).digest('hex');return p.webhook(body,`t=${ts},v1=${signature}`);}

test('review: concurrent replays reserve and settle once; account boundary is enforced',async t=>{const db=setup(t);let resolve,count=0;const j=jobs(db,()=>{count++;return new Promise(r=>resolve=r);}),q=j.quote('a',{kind:'field-suggestions',payload}),input={kind:'field-suggestions',payload,confirmed:true,quoteId:q.id,requestId:'request_123'},first=j.start('a',input);assert.equal(j.start('a',{...input,requestId:'request_456'}).id,first.id);assert.equal(count,1);assert.throws(()=>j.read('b',first.id));assert.throws(()=>j.cancel('b',first.id));assert.equal(db.get('SELECT reserved FROM accounts WHERE id=?','a').reserved,10);resolve({suggestions:[{fieldId:'f',factId:'s'}]});await tick();assert.equal(j.read('a',first.id).status,'ready');assert.equal(db.get('SELECT balance FROM accounts WHERE id=?','a').balance,90);j.refund('a',first.id);j.refund('a',first.id);assert.equal(db.get('SELECT balance FROM accounts WHERE id=?','a').balance,100);j.close();});

test('review: cancellation discards late output without charging',async t=>{const db=setup(t);let resolve;const j=jobs(db,()=>new Promise(r=>resolve=r)),first=start(j);j.cancel('a',first.id);resolve({suggestions:[{fieldId:'f',factId:'s'}]});await tick();assert.equal(j.read('a',first.id).status,'cancelled');assert.equal(db.get('SELECT balance FROM accounts WHERE id=?','a').balance,100);assert.equal(db.get('SELECT reserved FROM accounts WHERE id=?','a').reserved,0);j.close();});

test('review: invalid result releases reserve and cannot settle',async t=>{const db=setup(t),j=jobs(db,async()=>({suggestions:[{fieldId:'f',factId:'invented'}]})),first=start(j);await tick();assert.equal(j.read('a',first.id).status,'failed');assert.equal(db.get('SELECT balance FROM accounts WHERE id=?','a').balance,100);assert.equal(db.get('SELECT reserved FROM accounts WHERE id=?','a').reserved,0);j.close();});

test('review: restart recovery releases abandoned reserve exactly once',t=>{const db=setup(t),j=jobs(db,()=>new Promise(()=>{}));start(j);const recovered=jobs(db,async()=>({}));assert.equal(db.get('SELECT reserved FROM accounts WHERE id=?','a').reserved,0);assert.equal(db.get('SELECT balance FROM accounts WHERE id=?','a').balance,100);const again=jobs(db,async()=>({}));assert.equal(db.get("SELECT count(*) n FROM ledger WHERE kind='release'").n,1);again.close();recovered.close();j.close();});

test('review: signed paid event is idempotent and mismatched amount rejected',async t=>{const db=setup(t);let calls=0;const p=createPayments(db,paymentOptions({fetchImpl:async(_url,options)=>{calls++;const id=options.body.get('client_reference_id');return new Response(JSON.stringify({id:'cs_test_review',url:'https://checkout.stripe.com/c/pay/test',client_reference_id:id}));}}));const input={packId:'small',amount:100,currency:'usd',units:50,requestId:'purchase_123',confirmed:true};const [a,b]=await Promise.all([p.checkout('a',input),p.checkout('a',input)]);assert.equal(a.orderId,b.orderId);assert.equal(calls,1);const event={id:'evt_fake',type:'checkout.session.completed',livemode:false,data:{object:{id:'cs_test_review',client_reference_id:a.orderId,payment_status:'paid',amount_total:100,currency:'usd'}}};assert.throws(()=>signed(p,{...event,data:{object:{...event.data.object,amount_total:99}}}));signed(p,event);signed(p,event);assert.equal(db.get('SELECT balance FROM accounts WHERE id=?','a').balance,150);assert.throws(()=>p.webhook(Buffer.from('{}'),'t=0,v1='+'0'.repeat(64)));});

// Independent regressions for findings fixed by the implementation agent.
test('review: signed refund/chargeback freezes corresponding account and persists review alert',async t=>{const db=setup(t);const p=createPayments(db,paymentOptions({fetchImpl:async(_url,options)=>new Response(JSON.stringify({id:'cs_test_review',url:'https://checkout.stripe.com/c/pay/test',client_reference_id:options.body.get('client_reference_id')}))}));const order=await p.checkout('a',{packId:'small',amount:100,currency:'usd',units:50,requestId:'purchase_123',confirmed:true});signed(p,{type:'checkout.session.completed',livemode:false,data:{object:{id:'cs_test_review',client_reference_id:order.orderId,payment_status:'paid',amount_total:100,currency:'usd',payment_intent:'pi_review'}}});for(const type of ['charge.refunded','charge.dispute.created'])assert.deepEqual(signed(p,{id:'evt_'+type,type,livemode:false,data:{object:{id:'ch_review',payment_intent:'pi_review',amount:100,amount_refunded:100,refunded:true}}}),{received:true});assert.equal(db.get('SELECT balance FROM accounts WHERE id=?','a').balance,150);assert.equal(db.get('SELECT count(*) n FROM ledger').n,1);assert.equal(db.get('SELECT frozen FROM accounts WHERE id=?','a').frozen,1);assert.equal(db.get('SELECT frozen FROM accounts WHERE id=?','b').frozen,0);assert.equal(db.get('SELECT count(*) n FROM payment_alerts').n,2);const j=jobs(db,async()=>({suggestions:[{fieldId:'f',factId:'s'}]}));assert.throws(()=>start(j));j.close();});

test('review: live launch requires operator acceptance and complete model settings',t=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'hosted-review-live-'));try{const base={directory:dir,prices:{'field-suggestions':10},model:{enabled:false},payments:paymentOptions({secretKey:'sk_live_fake',live:true})};assert.throws(()=>startService(base),/验收/);assert.throws(()=>startService({...base,liveAccepted:true}),/模型/);assert.throws(()=>startService({...base,liveAccepted:true,model:{enabled:true,baseUrl:'https://model.example',apiKey:'fake'}}),/模型/);}finally{fs.rmSync(dir,{recursive:true,force:true});}});

test('review: refund arriving before paid event is isolated and later freezes only related account',async t=>{const db=setup(t),p=createPayments(db,paymentOptions({fetchImpl:async(_url,options)=>{const id=options.body.get('client_reference_id');return new Response(JSON.stringify({id:'cs_'+id,url:'https://checkout.stripe.com/c/pay/test',client_reference_id:id}));}}));const purchase={packId:'small',amount:100,currency:'usd',units:50,requestId:'purchase_123',confirmed:true};const orderA=await p.checkout('a',purchase),orderB=await p.checkout('b',purchase);const paid=(order,intent)=>({type:'checkout.session.completed',livemode:false,data:{object:{id:'cs_'+order.orderId,client_reference_id:order.orderId,payment_status:'paid',amount_total:100,currency:'usd',payment_intent:intent}}});signed(p,paid(orderB,'pi_b'));signed(p,{id:'evt_early_refund',type:'charge.refunded',livemode:false,data:{object:{id:'ch_a',payment_intent:'pi_a',amount:100,amount_refunded:100,refunded:true}}});assert.equal(db.get('SELECT frozen FROM accounts WHERE id=?','b').frozen,0,'unrelated paid customer must not freeze');signed(p,paid(orderA,'pi_a'));assert.equal(db.get('SELECT frozen FROM accounts WHERE id=?','a').frozen,1,'early refund must be linked when payment is received');assert.equal(db.get('SELECT frozen FROM accounts WHERE id=?','b').frozen,0);});

test('review: account tokens are opaque, revocable, and scoped to their account',async t=>{const db=setup(t),{createAccounts}=require('../accounts.cjs'),accounts=createAccounts(db,{invite:'test-invite'});await assert.rejects(accounts.register({email:'user@example.com',password:'long-password-123',invite:'wrong'}));const account=await accounts.register({email:'USER@example.com',password:'long-password-123',invite:'test-invite'});await assert.rejects(accounts.login({email:'user@example.com',password:'wrong-password-123'}));const login=await accounts.login({email:'user@example.com',password:'long-password-123'});assert.equal(accounts.authenticate(login.token),account.id);assert.notEqual(db.get('SELECT hash FROM sessions WHERE account_id=?',account.id).hash,login.token);accounts.logout(login.token);assert.throws(()=>accounts.authenticate(login.token));});

test('review: refund freeze during running job releases reserve and discards late output',async t=>{const db=setup(t);let resolve;const j=jobs(db,()=>new Promise(r=>resolve=r)),first=start(j);db.run('UPDATE accounts SET frozen=1 WHERE id=?','a');resolve({suggestions:[{fieldId:'f',factId:'s'}]});await tick();assert.notEqual(j.read('a',first.id).status,'ready');assert.equal(j.read('a',first.id).result,null);assert.equal(db.get('SELECT balance FROM accounts WHERE id=?','a').balance,100);assert.equal(db.get('SELECT reserved FROM accounts WHERE id=?','a').reserved,0);j.close();});

test('review: checkout rejects changed price or units before contacting provider',async t=>{const db=setup(t);let called=false;const p=createPayments(db,paymentOptions({fetchImpl:async()=>{called=true;throw Error('must not call');}}));for(const patch of [{amount:99},{currency:'eur'},{units:51}])await assert.rejects(p.checkout('a',{packId:'small',amount:100,currency:'usd',units:50,requestId:'purchase_123',confirmed:true,...patch}),/重新确认/);assert.equal(called,false);assert.equal(db.get('SELECT count(*) n FROM orders').n,0);});

test('review: watchdog releases reserve even if provider ignores abort and discards late result',async t=>{const db=setup(t);let resolve;const j=createJobs(db,{prices:{'field-suggestions':10},validatePayload,validateResult,jobTimeoutMs:10,processJob:()=>new Promise(r=>resolve=r)}),first=start(j);await new Promise(r=>setTimeout(r,35));assert.equal(j.read('a',first.id).status,'failed');assert.equal(db.get('SELECT reserved FROM accounts WHERE id=?','a').reserved,0);resolve({suggestions:[{fieldId:'f',factId:'s'}]});await tick();assert.equal(j.read('a',first.id).status,'failed');assert.equal(j.read('a',first.id).result,null);assert.equal(db.get('SELECT balance FROM accounts WHERE id=?','a').balance,100);assert.equal(db.get("SELECT count(*) n FROM ledger WHERE kind='release'").n,1);j.close();});

test('review: old ambiguous checkout cannot create another provider session after retry window',async t=>{const db=setup(t);let now=Date.now(),calls=0;const p=createPayments(db,paymentOptions({clock:()=>now,fetchImpl:async()=>{calls++;throw Error('provider accepted but response lost');}})),purchase={packId:'small',amount:100,currency:'usd',units:50,requestId:'purchase_123',confirmed:true};await assert.rejects(p.checkout('a',purchase),/response lost/);assert.equal(calls,1);now+=21*3600000;await assert.rejects(p.checkout('a',purchase),/旧订单|核对/);assert.equal(calls,1);assert.equal(db.get('SELECT count(*) n FROM orders').n,1);});
