'use strict';
const {randomUUID,createHash}=require('node:crypto');
const {publicUrl}=require('./public-page.cjs');
function endpoint(value){const u=new URL(value);if(u.username||u.password||u.search||u.hash||u.pathname!=='/'||!(u.protocol==='https:'||u.protocol==='http:'&&['localhost','127.0.0.1','[::1]'].includes(u.hostname)))throw Error('服务地址需为 HTTPS 根地址，本机测试可用 HTTP');return u.origin;}
function createHosted(store,facts,{vault,fetchImpl=fetch}={}){
 let closed=false,epoch=0;const active=new Set();
 const put=(collection,item)=>store.put(collection,item,{expectedRevision:store.get(collection,item.id)?.revision||0});
 function config(){const s=store.get('settings','hosted');let connected=false;try{connected=!!(s?.accountId&&vault?.get('hosted-token'));}catch{}return{baseUrl:s?.baseUrl||'',accountId:s?.accountId||'',email:s?.email||'',connected};}
 function configure(input){const baseUrl=endpoint(input.baseUrl);if(config().baseUrl!==baseUrl){epoch++;for(const c of active)c.abort();vault?.remove('hosted-token');}put('settings',{id:'hosted',baseUrl,...(config().baseUrl===baseUrl?{accountId:config().accountId,email:config().email}:{})});return config();}
 async function request(path,{data,auth=true,tokenOverride}={}){
  if(closed)throw Error('工作区已关闭');const current=config(),captured=epoch;if(!current.baseUrl)throw Error('请配置托管服务地址');const token=auth?(tokenOverride??vault?.get('hosted-token')):'';if(auth&&!token)throw Error('请登录托管账号');
  const controller=new AbortController();active.add(controller);
  try{const response=await fetchImpl(current.baseUrl+path,{method:data===undefined?'GET':'POST',redirect:'error',headers:{'Content-Type':'application/json',...(token?{Authorization:`Bearer ${token}`}:{})},body:data===undefined?undefined:JSON.stringify(data),signal:AbortSignal.any([controller.signal,AbortSignal.timeout(30000)])});let size=0;const chunks=[];for await(const chunk of response.body){size+=chunk.length;if(size>2*1024*1024)throw Error('服务结果过大');chunks.push(Buffer.from(chunk));}if(closed||captured!==epoch)throw Error('连接已切换或关闭');const result=JSON.parse(Buffer.concat(chunks).toString('utf8'));if(!response.ok)throw Error(typeof result.error==='string'?result.error:'托管服务请求失败');return result;
  }finally{active.delete(controller);}
 }
 async function login(input){if(!vault)throw Error('系统密钥存储不可用');epoch++;for(const c of active)c.abort();if(input.register===true)await request('/auth/register',{data:{email:input.email,password:input.password,invite:input.invite},auth:false});const result=await request('/auth/login',{data:{email:input.email,password:input.password},auth:false});if(typeof result.token!=='string'||typeof result.account?.id!=='string')throw Error('登录响应无效');vault.set('hosted-token',result.token);put('settings',{id:'hosted',baseUrl:config().baseUrl,accountId:result.account.id,email:result.account.email});return config();}
 async function logout(){const previous=config(),token=vault?.get('hosted-token');epoch++;for(const c of active)c.abort();vault?.remove('hosted-token');put('settings',{id:'hosted',baseUrl:previous.baseUrl});let failure;try{if(previous.connected)await request('/auth/logout',{data:{},tokenOverride:token});}catch(e){failure=e;}return{...config(),warning:failure?'本机已退出，原远程会话撤销未确认；会话到期后失效':''};}
 async function account(){const r=await request('/account');const integer=v=>Number.isSafeInteger(v);if(!r.account||typeof r.account.id!=='string'||r.account.id!==config().accountId||![r.account.balance,r.account.reserved,r.account.available].every(integer)||r.account.balance<0||r.account.reserved<0||r.account.available!==r.account.balance-r.account.reserved||!r.catalog||!Array.isArray(r.catalog.packs)||!Array.isArray(r.ledger)||!Array.isArray(r.jobs)||r.catalog.packs.length>100||r.ledger.length>200||r.jobs.length>100)throw Error('托管账号响应无效');for(const p of r.catalog.packs)if(typeof p.id!=='string'||!integer(p.units)||p.units<1||!integer(p.amount)||p.amount<1||!['usd','cny','eur','hkd','sgd'].includes(p.currency))throw Error('额度包响应无效');for(const l of r.ledger)if(!integer(l.balance_delta)||!integer(l.reserved_delta))throw Error('额度记录响应无效');return r;}
 async function quoteBriefing(input){if(input.confirmed!==true)throw Error('请确认向托管服务发送的范围');const event=store.get('events',input.eventId);if(!event||event.type!=='interview')throw Error('请选择面试');const {opportunity:job}=require('./event-context.cjs').eventContext(store,event),organization=store.get('organizations',event.organizationId);
  const payload={company:organization?.name||'',title:event.title,description:job?.description||'',urls:Array.isArray(input.urls)&&input.urls.length>0&&input.urls.length<=5?[...new Set(input.urls.map(u=>publicUrl(u).href))]:(()=>{throw Error('请提供1至5个公开来源链接');})(),includeExperience:input.includeExperience===true};let profileHash='';
  if(payload.includeExperience){const p=facts.read();profileHash=p.hash;const allowed={education:['school','level','degree','major','researchStudy','researchDirection'],internship:['company','department','position','description'],projects:['name','role','description','responsibilities'],campus:['name','role','description'],skills:['name','level','category']};payload.experiences=Object.fromEntries(Object.entries(allowed).map(([g,keys])=>[g,(p.profile.values[g]||[]).map(r=>Object.fromEntries(keys.filter(k=>typeof r[k]==='string').map(k=>[k,r[k]])))]));}
  const quote=await request('/quotes',{data:{kind:'briefing',payload}});if(typeof quote.id!=='string'||!Number.isSafeInteger(quote.units)||quote.units<1||!Number.isFinite(quote.expiresAt)||typeof quote.successDefinition!=='string'||quote.successDefinition.length>1000)throw Error('服务报价无效');const current=config(),requestId=randomUUID(),local=put('aiJobs',{id:`hosted-${requestId}`,kind:'hosted-briefing',status:'quoted',billing:'hosted',eventId:event.id,eventRevision:event.revision,opportunityId:job?.id||'',opportunityRevision:job?.revision||0,profileHash,server:current.baseUrl,accountId:current.accountId,requestId,payload,quote});return{id:local.id,units:quote.units,expiresAt:quote.expiresAt,successDefinition:quote.successDefinition};
 }
 async function quoteMapping(scope){
  const payload={fields:require('../ai-mapping.cjs').mappingInput(scope.candidates).fields,...(scope.mode==='correction'?{allowedMappings:scope.allowedMappings}:{})};
  const savedScope={...scope,candidates:scope.candidates.map(({frame,...candidate})=>candidate)};
  const quote=await request('/quotes',{data:{kind:scope.mode==='correction'?'field-correction':'field-mapping',payload}});
  if(typeof quote.id!=='string'||!Number.isSafeInteger(quote.units)||quote.units<1||!Number.isFinite(quote.expiresAt)||typeof quote.successDefinition!=='string'||quote.successDefinition.length>1000)throw Error('服务报价无效');
  const current=config(),requestId=randomUUID(),local=put('aiJobs',{id:`hosted-${requestId}`,kind:scope.mode==='correction'?'hosted-correction':'hosted-mapping',status:'quoted',billing:'hosted',scope:savedScope,server:current.baseUrl,accountId:current.accountId,requestId,payload,quote});
  return{id:local.id,units:quote.units,expiresAt:quote.expiresAt,successDefinition:quote.successDefinition};
 }
 function mappingJob(id,mode='mapping'){const j=localJob(id);if(j.kind!==(mode==='correction'?'hosted-correction':'hosted-mapping'))throw Error('不是字段识别任务');return j;}
 function mappingJobs(mode='mapping'){const c=config();return store.list('aiJobs').filter(j=>j.kind===(mode==='correction'?'hosted-correction':'hosted-mapping')&&j.server===c.baseUrl&&j.accountId===c.accountId).slice(-20).map(j=>({id:j.id,status:j.status,error:j.error,quote:j.quote}));}
 function adoptMapping(local,remote){
  const current=localJob(local.id);
  if(!remote||typeof remote.id!=='string'||!/^[a-f0-9-]{36}$/.test(remote.id)||remote.kind!==(local.kind==='hosted-correction'?'field-correction':'field-mapping')||remote.units!==local.quote.units||current.remoteId&&remote.id!==current.remoteId||!['queued','running','ready','failed','cancelled','interrupted','refunded'].includes(remote.status))throw Error('托管字段响应无效');
  if(['ready','refunded','failed','cancelled','interrupted'].includes(current.status)&&!['ready','refunded','failed','cancelled','interrupted'].includes(remote.status))return current;
  if(current.status==='refunded'&&remote.status==='ready')return current;
  let suggestions=current.suggestions;
  if(['ready','refunded'].includes(remote.status)){if(remote.result)suggestions=require('../ai-mapping.cjs').validateMappings(remote.result,local.scope.candidates);if(!suggestions?.length)throw Error('未交付可用的字段对应建议');if(local.kind==='hosted-correction'&&suggestions.some(s=>!local.payload.allowedMappings.find(a=>a.id===s.id)?.targets.some(t=>t.group===s.group&&t.key===s.key)))throw Error('托管纠错超出可用资料范围');}
  return put('aiJobs',{...current,remoteId:remote.id,status:remote.status,error:remote.error||'',suggestions});
 }
 function mailConfig(){const current=config();return{...current,fingerprint:createHash('sha256').update(JSON.stringify([current.baseUrl,current.accountId])).digest('hex')};}
 async function quoteMail(input){
  const current=mailConfig();if(!current.connected||input.fingerprint!==current.fingerprint)throw Error('托管账号或服务已变化，请重新确认');
  const scope=require('./mail-ai.cjs').mailScope(store,input),payload={text:scope.text,offset:scope.offset};
  const quote=await request('/quotes',{data:{kind:'mail-parse',payload}});
  require('./mail-ai.cjs').assertMailScope(store,scope);
  if(typeof quote.id!=='string'||quote.kind!=='mail-parse'||!Number.isSafeInteger(quote.units)||quote.units<1||!Number.isFinite(quote.expiresAt)||typeof quote.successDefinition!=='string'||quote.successDefinition.length>1000)throw Error('服务报价无效');
  const requestId=randomUUID(),local=put('aiJobs',{id:'hosted-'+requestId,kind:'hosted-mail-parse',status:'quoted',billing:'hosted',scope,confirmationId:scope.confirmationId,server:current.baseUrl,accountId:current.accountId,requestId,payload,quote});
  return{id:local.id,units:quote.units,expiresAt:quote.expiresAt,successDefinition:quote.successDefinition};
 }
 function mailJob(id){const j=localJob(id);if(j.kind!=='hosted-mail-parse')throw Error('不是托管邮件解析任务');return j;}
 function mailJobs(id){const c=config();if(!c.connected)return[];return store.list('aiJobs').filter(j=>j.kind==='hosted-mail-parse'&&j.confirmationId===id&&j.server===c.baseUrl&&j.accountId===c.accountId).slice(-20);}
 function adoptMail(local,remote){
  const current=mailJob(local.id);
  if(!remote||typeof remote.id!=='string'||!/^[a-f0-9-]{36}$/.test(remote.id)||remote.kind!=='mail-parse'||remote.units!==local.quote.units||current.remoteId&&remote.id!==current.remoteId||!['queued','running','ready','failed','cancelled','interrupted','refunded'].includes(remote.status))throw Error('托管邮件响应无效');
  if(['ready','refunded','failed','cancelled','interrupted'].includes(current.status)&&!['ready','refunded','failed','cancelled','interrupted'].includes(remote.status))return current;
  if(current.status==='refunded'&&remote.status==='ready')return current;
  let changes=current.changes;
  if(['ready','refunded'].includes(remote.status)){if(remote.result)changes=require('./mail-ai.cjs').validateMailResult(remote.result,local.payload.text,local.payload.offset);if(!changes?.some(c=>c.adoptable))throw Error('未交付可用的邮件字段');}
  return put('aiJobs',{...current,remoteId:remote.id,status:remote.status,error:remote.error||'',changes});
 }
 function mailResult(id){
  const local=mailJob(id);if(!['ready','refunded'].includes(local.status)||!local.changes?.some(c=>c.adoptable))throw Error('托管邮件结果尚不可核对');
  require('./mail-ai.cjs').assertMailScope(store,local.scope);
  const reviewId='mail-review-'+local.id,old=store.get('aiJobs',reviewId);if(old)return old;
  return put('aiJobs',{id:reviewId,kind:'mail-parse',status:'ready',billing:'hosted',sourceJobId:local.id,server:local.server,accountId:local.accountId,...local.scope,changes:local.changes});
 }
 function localJob(id){const j=store.get('aiJobs',id),current=config();if(!j||!['hosted-briefing','hosted-mapping','hosted-correction','hosted-mail-parse'].includes(j.kind))throw Error('托管任务不存在');if(j.server!==current.baseUrl||j.accountId!==current.accountId)throw Error('请登录创建此任务的服务账号');return j;}
 function adopt(local,remote){if(local.kind==='hosted-mail-parse')return adoptMail(local,remote);if(['hosted-mapping','hosted-correction'].includes(local.kind))return adoptMapping(local,remote);const current=localJob(local.id);if(['ready','refunded','failed','cancelled','interrupted'].includes(current.status)&&!['ready','refunded','failed','cancelled','interrupted'].includes(remote?.status))return current;if(current.status==='refunded'&&remote?.status==='ready')return current;if(remote?.units!==local.quote.units)throw Error('托管结算额度与报价不一致');if(!remote||typeof remote.id!=='string'||!/^[a-f0-9-]{36}$/.test(remote.id)||remote.kind!=='briefing'||current.remoteId&&remote.id!==current.remoteId||!['queued','running','ready','failed','cancelled','interrupted','refunded'].includes(remote.status))throw Error('托管任务响应无效');if(['ready','refunded'].includes(remote.status)&&!remote.result&&!store.get('briefings',`briefing-${local.id}`))throw Error('托管服务未返回完整结果，未标记交付');return store.transaction(()=>{if(['ready','refunded'].includes(remote.status)&&remote.result&&!store.get('briefings',`briefing-${local.id}`)){const r=remote.result;if(!Array.isArray(r.sources)||r.sources.length!==local.payload.urls.length||r.sources.some((s,i)=>s.id!==`S${i+1}`||typeof s.text!=='string'||s.text.length>40000||typeof s.url!=='string'||new URL(s.url).origin!==new URL(local.payload.urls[i]).origin))throw Error('托管来源与授权链接不一致');if(!Array.isArray(r.sources)||!Array.isArray(r.facts)||!Array.isArray(r.hypotheses)||!Array.isArray(r.questions))throw Error('托管简报结果无效');const result=require('./briefings.cjs').validateBriefing(r,r.sources,local.payload.experiences||null);store.put('briefings',{id:`briefing-${local.id}`,eventId:local.eventId,eventRevision:local.eventRevision,opportunityId:local.opportunityId||'',opportunityRevision:local.opportunityRevision||0,profileHash:local.profileHash,createdAt:new Date().toISOString(),status:'ready',sources:r.sources,...result,body:[...result.facts.map(f=>`[${f.sourceId}] ${f.quote}`),...result.personalEvidence.map(p=>`个人经历原文：${p.quote}\n待核实关联：${p.relevance}`),...result.hypotheses.map(s=>`待核实推断：${s}`),...result.questions.map(s=>`准备建议：${s}`)].join('\n\n')});}return put('aiJobs',{...local,remoteId:remote.id,status:remote.status,error:remote.error||'',units:remote.units});});}
 async function start(input){if(input.confirmed!==true)throw Error('请确认扣除额度');const local=localJob(input.id);if(local.status==='cancelled'&&!local.remoteId)return local;if(local.kind==='hosted-mail-parse'&&!['ready','refunded','failed','cancelled','interrupted'].includes(local.status))require('./mail-ai.cjs').assertMailScope(store,local.scope);if(!['ready','refunded','failed','cancelled','interrupted'].includes(local.status))put('aiJobs',{...local,status:'pending_remote'});const remote=await request('/jobs',{data:{kind:local.kind==='hosted-mapping'?'field-mapping':local.kind==='hosted-correction'?'field-correction':local.kind==='hosted-mail-parse'?'mail-parse':'briefing',payload:local.payload,quoteId:local.quote.id,requestId:local.requestId,confirmed:true}});return adopt(local,remote);}
 async function refresh(id){const local=localJob(id);if(local.status==='cancelled'&&!local.remoteId)return local;let remoteId=local.remoteId;if(!remoteId){const a=await account();remoteId=a.jobs?.find(j=>j.request_id===local.requestId)?.id;if(!remoteId)return{...local,error:'远程尚未确认接收，可用同一任务重试，避免重复扣费'};}return adopt(local,await request('/jobs/'+encodeURIComponent(remoteId)));}
 async function cancel(id){const local=localJob(id);if(local.status==='quoted'||local.status==='cancelled'&&!local.remoteId)return put('aiJobs',{...local,status:'cancelled'});let remoteId=local.remoteId;if(!remoteId){const a=await account();remoteId=a.jobs?.find(j=>j.request_id===local.requestId)?.id;if(!remoteId)throw Error('远程接收状态尚不明确，请先刷新，不会直接标记取消成功');}return adopt(local,await request('/jobs/'+encodeURIComponent(remoteId)+'/cancel',{data:{}}));}
 async function checkout(input){const result=await request('/checkout',{data:input});const url=new URL(result.url);if(url.protocol!=='https:'||url.hostname!=='checkout.stripe.com')throw Error('支付链接无效');return{...result,url:url.href};}
 async function monitoring(action='list',input={}){if(!['list','add','update','remove','read'].includes(action))throw Error('未知监控操作');if(action==='add'&&input.confirmed!==true)throw Error('请先确认云端监控发送范围');const data=action==='add'?{label:input.label,url:publicUrl(input.url).href,confirmed:input.confirmed===true}:action==='update'?{id:input.id,revision:input.revision,enabled:input.enabled}:action==='remove'?{id:input.id,revision:input.revision}:{id:input.id};return request(action==='list'?'/monitoring':'/monitoring/'+action,action==='list'?{}:{data});}
 function close(){closed=true;epoch++;for(const c of active)c.abort();}
 return{config,configure,login,logout,account,quoteBriefing,quoteMail,mailConfig,mailJob,mailJobs,mailResult,quoteMapping,mappingJob,mappingJobs,start,refresh,cancel,checkout,monitoring,close};
}
module.exports={createHosted,endpoint};
