'use strict';
const {randomUUID}=require('node:crypto');
const {publicUrl}=require('./public-page.cjs');
const normalized=v=>v.normalize('NFKC').trim().toLowerCase();
const types={企业:'enterprise',招录机关:'government',事业单位:'public',院校:'university',enterprise:'enterprise',government:'government',public:'public',university:'university'};
const typeValue=value=>typeof value==='string'&&Object.hasOwn(types,value)?types[value]:null;
function createOpportunityActions(store,workflow,{clock=Date.now}={}){
 const previews=new Map();
 function preview(input){if(typeof input.text!=='string'||input.text.length>100000)throw Error('请粘贴不超过 200 行的单位清单');const fallback=typeValue(input.type||'enterprise');if(!fallback)throw Error('单位类型无效');const lines=input.text.split(/\r?\n/).filter(l=>l.trim());if(!lines.length||lines.length>200)throw Error('单位清单需要 1 至 200 行');const seen=new Set(),rows=[];let duplicates=0;
  for(const [index,line]of lines.entries()){const columns=line.split('\t');if(columns.length>3)throw Error(`第 ${index+1} 行最多三列：名称、公开链接、类型`);const name=columns[0].trim(),type=typeValue(columns[2]?.trim()||fallback);if(!name||name.length>150||!type)throw Error(`第 ${index+1} 行名称或类型无效`);let website='';if(columns[1]?.trim()){website=publicUrl(columns[1].trim()).href;if(website.length>2000)throw Error(`第 ${index+1} 行链接过长`);}const key=type+'\0'+normalized(name);if(seen.has(key)){duplicates++;continue;}seen.add(key);const existing=store.list('organizations').find(o=>o.type===type&&normalized(o.name)===normalized(name));rows.push({id:String(index),name,type,website,existingId:existing?.id||''});}
  const now=clock();for(const [id,item]of previews)if(item.expires<=now)previews.delete(id);if(previews.size>=10)previews.delete(previews.keys().next().value);const ticket=randomUUID();previews.set(ticket,{rows,expires:now+300000});return{ticket,rows,duplicates};
 }
 function adopt(input){const p=previews.get(input.ticket);if(!p||p.expires<=clock())throw Error('清单预览已失效，请重新预览');if(input.confirmed!==true)throw Error('请确认勾选的单位清单');if(!Array.isArray(input.ids)||!input.ids.length||input.ids.length>200||new Set(input.ids).size!==input.ids.length||input.ids.some(id=>!p.rows.some(r=>r.id===id)))throw Error('请勾选有效且不重复的单位');const result=store.transaction(()=>input.ids.map(id=>{const row=p.rows.find(r=>r.id===id),existing=store.list('organizations').find(o=>o.type===row.type&&normalized(o.name)===normalized(row.name)),org=existing||workflow.organization({name:row.name,type:row.type,website:row.website});workflow.watch({organizationId:org.id});return{id:org.id,name:org.name,created:!existing};}));previews.delete(input.ticket);return{organizations:result};}
 function bulkPlan(input){if(input.confirmed!==true)throw Error('请确认所选岗位 / 单位及计划安排');if(!Array.isArray(input.items)||!input.items.length||input.items.length>200)throw Error('请选择 1 至 200 个岗位或单位');const seen=new Set(),items=input.items.map(item=>{if(!item||!['organization','opportunity'].includes(item.kind)||typeof item.id!=='string')throw Error('计划选择无效');const key=item.kind+':'+item.id;if(seen.has(key))throw Error('计划选择重复');seen.add(key);const entity=store.get(item.kind==='opportunity'?'opportunities':'organizations',item.id);if(!entity)throw Error('所选记录已不存在，请刷新');return{...item,organizationId:item.kind==='opportunity'?entity.organizationId:entity.id};});if(input.reminderEnabled!==undefined&&typeof input.reminderEnabled!=='boolean')throw Error('计划提醒设置无效');const roleOrganizations=new Set(items.filter(i=>i.kind==='opportunity').map(i=>i.organizationId));
  // Validate shared fields even when all selections already have plans.
  if(typeof input.plannedOn!=='string'||!/^\d{4}-\d{2}-\d{2}$/.test(input.plannedOn)||!Number.isFinite(Date.parse(input.plannedOn))||new Date(input.plannedOn).toISOString().slice(0,10)!==input.plannedOn)throw Error('请选择有效计划申请日期');if(!['high','normal','low'].includes(input.priority))throw Error('计划优先级无效');
  return store.transaction(()=>{const created=[],existing=[],omitted=[];for(const item of items){workflow.watch({organizationId:item.organizationId});if(item.kind==='organization'&&roleOrganizations.has(item.id)){omitted.push(item.id);continue;}const old=store.list('plans').find(p=>item.kind==='opportunity'?p.opportunityId===item.id:p.organizationId===item.id&&!p.opportunityId);if(old){existing.push(old.id);continue;}created.push(workflow.plan({organizationId:item.organizationId,opportunityId:item.kind==='opportunity'?item.id:'',plannedOn:input.plannedOn,priority:input.priority,reminderEnabled:input.reminderEnabled!==false}).id);}return{created,existing,omitted};});
 }
 return{preview,adopt,bulkPlan,close(){previews.clear();}};
}
module.exports={createOpportunityActions};
