const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os'),zlib=require('node:zlib'),{createHash}=require('node:crypto');
const {createWorkbench}=require('../src/services/workbench.cjs');
function fixture(t){const root=fs.mkdtempSync(path.join(os.tmpdir(),'backup-review-'));fs.mkdirSync(path.join(root,'知识库'));fs.writeFileSync(path.join(root,'知识库/profile.json'),JSON.stringify({schemaVersion:1,demo:false,values:{basic:[{name:'测试'}]}}));const wb=createWorkbench(root);t.after(()=>{wb.close();fs.rmSync(root,{recursive:true,force:true});});return {root,wb,file:path.join(root,'backup.qzb')};}
function asset(wb){const bytes=Buffer.from('%PDF-1.4\nfixture'),hash=createHash('sha256').update(bytes).digest('hex');fs.writeFileSync(path.join(wb.store.directory,'assets',hash+'.pdf'),bytes);return wb.store.put('assets',{id:'asset-'+hash,hash,extension:'.pdf',size:bytes.length,name:'test.pdf',parseStatus:'processing'});}
test('export rejects an archive that its own preview cannot restore',t=>{const {root,wb,file}=fixture(t);fs.writeFileSync(path.join(root,'知识库/profile.json'),'{broken');assert.throws(()=>wb.backup.exportFile(file));});
test('asset directory symlink must not export external originals',t=>{const {root,wb,file}=fixture(t);asset(wb);const source=path.join(root,'external-originals');fs.renameSync(path.join(wb.store.directory,'assets'),source);fs.symlinkSync(source,path.join(wb.store.directory,'assets'),'dir');assert.throws(()=>wb.backup.exportFile(file),/链接/);});
test('restored parsing has no live worker and must not remain processing',t=>{const {root,wb,file}=fixture(t),item=asset(wb);wb.backup.exportFile(file);const {workspace}=wb.backup.restore(file,root,wb.backup.preview(file).sha256);const copy=createWorkbench(workspace);try{assert.notEqual(copy.store.get('assets',item.id).parseStatus,'processing');}finally{copy.close();}});
test('restored connections are disconnected even from an archive carrying live status',t=>{const {root,wb,file}=fixture(t);wb.store.put('connections',{id:'connection-1',status:'connected',secret:'test-secret'});wb.backup.exportFile(file);const data=JSON.parse(zlib.gunzipSync(fs.readFileSync(file)));assert.equal(data.database.collections.connections[0].secret,undefined);data.database.collections.connections[0].status='connected';data.database.collections.connections[0].secret='test-secret';fs.writeFileSync(file,zlib.gzipSync(JSON.stringify(data)));const {workspace}=wb.backup.restore(file,root,wb.backup.preview(file).sha256);const copy=createWorkbench(workspace);try{assert.equal(copy.store.get('connections','connection-1').status,'disconnected');assert.equal(copy.store.get('connections','connection-1').secret,undefined);}finally{copy.close();}});
test('restore refuses a missing managed original before creating directory',t=>{const {root,wb,file}=fixture(t);asset(wb);wb.backup.exportFile(file);const data=JSON.parse(zlib.gunzipSync(fs.readFileSync(file)));data.files=data.files.filter(entry=>!entry.path.startsWith('.workbench/assets/'));fs.writeFileSync(file,zlib.gzipSync(JSON.stringify(data)));assert.throws(()=>wb.backup.preview(file),/原件缺失/);assert.equal(fs.readdirSync(root).some(name=>name.startsWith('招聘工作台-恢复-')),false);});
test('restore interrupts active AI work without invoking providers',t=>{const {root,wb,file}=fixture(t);wb.store.put('aiJobs',{id:'ai-active',kind:'resume-ocr',status:'running'});wb.backup.exportFile(file);const {workspace}=wb.backup.restore(file,root,wb.backup.preview(file).sha256);const copy=createWorkbench(workspace);try{assert.equal(copy.store.get('aiJobs','ai-active').status,'interrupted');}finally{copy.close();}});
