'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),{randomUUID}=require('node:crypto');
const {createBriefings,validateBriefing}=require('../src/services/briefings.cjs');
const {openStore}=require('../src/services/store.cjs');
const url='https://example.invalid/company',body='公司公开产品说明：这是可逐字核验的产品资料。服务面向企业客户，具体团队职责仍需在面试中确认。';
const output=()=>({facts:[{sourceId:'S1',quote:'服务面向企业客户'}],hypotheses:['岗位可能涉及企业业务'],questions:['请问团队的职责是什么？']});
function deferred(){let resolve;const promise=new Promise(r=>resolve=r);return {promise,resolve};}
function setup(t,options={}){const root=fs.mkdtempSync(path.join(os.tmpdir(),'briefings-review-')),store=openStore(root);let reads=0;const facts={read(){reads++;return {hash:'profile-hash',profile:{values:{basic:[{name:'SECRET_NAME',phone:'SECRET_PHONE'}],education:[{school:'学校',major:'专业',phone:'SECRET_EDU_PHONE'}],internship:[{company:'企业',description:'允许发送的描述',reference:'SECRET_REFERENCE'}],projects:[],campus:[],skills:[{name:'技能',level:'熟悉'}]}}};}};store.put('organizations',{id:'org',name:'公司'});store.put('events',{id:'event',type:'interview',organizationId:'org',title:'一面',round:1,location:'SECRET_LOCATION',url:'https://private.invalid/meeting'});const service=createBriefings(store,facts,{read:()=>({enabled:true})},{reader:async()=>({url,body}),invoke:async()=>output(),...options});t.after(()=>{service.close();store.close();fs.rmSync(root,{recursive:true,force:true});});return {root,store,service,reads:()=>reads,input:(extra={})=>({eventId:'event',requestId:randomUUID(),urls:[url],confirmed:true,...extra})};}
test('facts must be exact source quotes; arbitrary model fact prose is discarded',()=>{assert.throws(()=>validateBriefing({...output(),facts:[{sourceId:'S2',quote:'服务面向企业客户'}]},[{id:'S1',text:body}]));assert.throws(()=>validateBriefing({...output(),facts:[{sourceId:'S1',quote:'公司已经录用你'}]},[{id:'S1',text:body}]));assert.throws(()=>validateBriefing({...output(),facts:[]},[{id:'S1',text:body}]));const result=validateBriefing({...output(),facts:[{sourceId:'S1',quote:'服务面向企业客户',claim:'恶意编造'}]},[{id:'S1',text:body}]);assert.deepEqual(result.facts,[{sourceId:'S1',quote:'服务面向企业客户'}]);});
test('default scope excludes profile, notes and event private fields; opt-in uses whitelist',async t=>{let sent;const x=setup(t,{invoke:async(_config,request)=>{sent=request.input;return output();}});await x.service.run(x.input());assert.equal(x.reads(),0);assert.equal(sent.experiences,null);assert.equal(JSON.stringify(sent).includes('SECRET'),false);await x.service.run(x.input({includeExperience:true}));assert.equal(x.reads(),1);assert.equal(JSON.stringify(sent).includes('SECRET'),false);assert.equal(sent.experiences.education[0].school,'学校');assert.equal(sent.experiences.internship[0].description,'允许发送的描述');});
test('confirmation and URL cardinality/protocol reject before any reader call',async t=>{let calls=0;const x=setup(t,{reader:async()=>{calls++;return {url,body};}});for(const extra of [{confirmed:false},{urls:[]},{urls:Array(6).fill(url)},{urls:['http://example.com']},{urls:['https://127.0.0.1']}])await assert.rejects(x.service.run(x.input(extra)));assert.equal(calls,0);assert.equal(x.store.list('aiJobs').length,0);});
test('same request ID coalesces concurrent and ready requests without repeated provider calls',async t=>{const gate=deferred();let calls=0;const x=setup(t,{invoke:async()=>{calls++;await gate.promise;return output();}}),input=x.input();const first=x.service.run(input);assert.equal((await x.service.run(input)).status,'running');gate.resolve();assert.equal((await first).status,'ready');assert.equal((await x.service.run(input)).status,'ready');assert.equal(calls,1);assert.equal(x.store.list('briefings').length,1);await assert.rejects(x.service.run({...input,includeExperience:true}),/其他范围/);});
test('generation retains source evidence, labels inference, preserves notes and survives reopen',async t=>{const x=setup(t);const note=x.store.put('notes',{id:'note',eventId:'event',body:'我的真实笔记'});const job=await x.service.run(x.input());assert.deepEqual(x.store.get('notes','note'),note);const b=x.store.get('briefings',job.briefingId);assert.equal(b.sources[0].text,body);assert.match(b.sources[0].contentHash,/^[a-f0-9]{64}$/);assert.match(b.body,/待核实推断：/);assert.match(b.body,/准备建议：/);x.service.close();x.store.close();const reopened=openStore(x.root);try{assert.equal(reopened.get('aiJobs',job.id).status,'ready');assert.equal(reopened.get('briefings',job.briefingId).body,b.body);}finally{reopened.close();}});
test('cancel while reader ignores abort rejects late data before model call',async t=>{const gate=deferred();let calls=0,signal;const x=setup(t,{reader:async(_url,options)=>{signal=options.signal;await gate.promise;return {url,body};},invoke:async()=>{calls++;return output();}}),input=x.input(),pending=x.service.run(input);assert.equal(x.service.cancel(input.requestId),true);assert.equal(signal.aborted,true);gate.resolve();await assert.rejects(pending,/取消/);assert.equal(calls,0);assert.equal(x.store.get('aiJobs',input.requestId).status,'cancelled');assert.equal(x.store.list('briefings').length,0);});
test('cancel during model invocation rejects ignored abort late result',async t=>{const entered=deferred(),gate=deferred();const x=setup(t,{invoke:async()=>{entered.resolve();await gate.promise;return output();}}),input=x.input(),pending=x.service.run(input);await entered.promise;x.service.cancel(input.requestId);gate.resolve();await assert.rejects(pending,/取消/);assert.equal(x.store.list('briefings').length,0);assert.equal(x.store.get('aiJobs',input.requestId).status,'cancelled');});
test('close marks interruption and late model result cannot write into reopened workspace',async t=>{const entered=deferred(),gate=deferred();const x=setup(t,{invoke:async()=>{entered.resolve();await gate.promise;return output();}}),input=x.input(),pending=x.service.run(input);await entered.promise;x.service.close();x.store.close();gate.resolve();await assert.rejects(pending,/取消/);const reopened=openStore(x.root);try{assert.equal(reopened.get('aiJobs',input.requestId).status,'interrupted');assert.equal(reopened.list('briefings').length,0);}finally{reopened.close();}});
test('startup marks persisted running briefing interrupted',t=>{const x=setup(t);x.store.put('aiJobs',{id:randomUUID(),kind:'interview-briefing',status:'running'});const second=createBriefings(x.store,{read(){throw Error('not expected')}},null);second.close();assert.equal(x.store.list('aiJobs')[0].status,'interrupted');});
test('failed same-ID replay remains failed without extra charge; UI must explicitly create retry ID',async t=>{let calls=0;const x=setup(t,{invoke:async()=>{calls++;throw Error('provider unavailable');}}),input=x.input();await assert.rejects(x.service.run(input),/provider unavailable/);assert.equal((await x.service.run(input)).status,'failed');assert.equal(calls,1);});
test('partial persistence failure rolls back generated briefing',async t=>{const x=setup(t),put=x.store.put;x.store.put=(collection,item,...args)=>{if(collection==='aiJobs'&&item.status==='ready')throw Error('injected save failure');return put(collection,item,...args)};await assert.rejects(x.service.run(x.input()),/injected/);assert.equal(x.store.list('briefings').length,0);assert.equal(x.store.list('aiJobs')[0].status,'failed');});
test('different request IDs cannot create simultaneous paid jobs for one event',async t=>{const gate=deferred();let reads=0;const x=setup(t,{reader:async()=>{reads++;await gate.promise;return {url,body};}});const pending=x.service.run(x.input());await assert.rejects(x.service.run(x.input()),/正在生成/);assert.equal(reads,1);gate.resolve();await pending;});
function editorHarness(api){const vm=require('node:vm'),source=fs.readFileSync(path.join(__dirname,'../src/ui/workbench.js'),'utf8'),start=source.indexOf('async function briefingEditor('),end=source.indexOf('async function interviewOpen(',start);let captured;const context={h:value=>String(value).replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c])),crypto:{randomUUID},api,modal:(title,subtitle,html,handler)=>{captured={title,subtitle,html,handler};},submit:text=>`<button type="submit">${text}</button>`,button:(action,text,id)=>`<button type="button" data-action="${action}" data-id="${id}">${text}</button>`,interviewOpen:()=>{}};vm.createContext(context);vm.runInContext(source.slice(start,end)+';this.open=briefingEditor',context);return {open:async()=>{await context.open('event');return captured;}};}
test('UI keeps cancel available in-flight and explicit retry uses a new request ID with cost notice',async()=>{const gate=deferred(),requests=[],h=editorHarness(async(_action,data)=>{requests.push(data);if(requests.length===1){await gate.promise;throw Error('network failure');}return {status:'ready'};}),panel=await h.open(),cancel={dataset:{}},submit={textContent:''},form={querySelector:s=>s.includes('briefing-cancel')?cancel:submit};assert.match(panel.html,/type="button" data-action="briefing-cancel"/);const pending=panel.handler({urls:url,confirmed:'on'},form);assert.ok(panel.html.includes(requests[0].requestId));gate.resolve();await assert.rejects(pending,/network failure/);assert.match(submit.textContent,/可能产生新的供应商费用/);assert.notEqual(cancel.dataset.id,requests[0].requestId);await panel.handler({urls:url,confirmed:'on'},form);assert.equal(requests[1].requestId,cancel.dataset.id);assert.notEqual(requests[1].requestId,requests[0].requestId);});
test('UI does not present persisted failed status as a successful delivery',async()=>{const h=editorHarness(async()=>({status:'failed',error:'failed record'})),panel=await h.open(),form={querySelector:()=>({dataset:{}})};await assert.rejects(panel.handler({urls:url,confirmed:'on'},form),/failed record/);});
test('personal evidence requires explicit opt-in and persists verified quote with tentative relevance',async t=>{const personalEvidence=[{group:'internship',index:0,field:'description',quote:'允许发送的描述',relevance:'可能与岗位要求有关，需进一步核对'}],x=setup(t,{invoke:async()=>({...output(),personalEvidence})});await assert.rejects(x.service.run(x.input()),/已授权依据/);assert.equal(x.reads(),0);assert.equal(x.store.list('briefings').length,0);const job=await x.service.run(x.input({includeExperience:true})),briefing=x.store.get('briefings',job.briefingId);assert.deepEqual(briefing.personalEvidence,personalEvidence);assert.equal(briefing.profileHash,'profile-hash');assert.match(briefing.body,/个人经历原文 \[internship\/1\/description\]：允许发送的描述/);assert.match(briefing.body,/待核实关联：可能与岗位要求有关/);});
test('fabricated, hidden-field, prototype and invalid-index personal evidence never delivers',async t=>{let personalEvidence;const x=setup(t,{invoke:async()=>({...output(),personalEvidence})}),base={group:'internship',index:0,field:'description',quote:'允许发送的描述',relevance:'待核实关联'};for(const change of [{quote:'编造的管理三十人经历'},{field:'reference',quote:'SECRET_REFERENCE'},{group:'basic',field:'phone',quote:'SECRET_PHONE'},{group:'__proto__'},{field:'toString',quote:'function'},{index:-1},{index:99},{index:'0'},{index:0.5}]){personalEvidence=[{...base,...change}];await assert.rejects(x.service.run(x.input({includeExperience:true})),/依据|引文/);}assert.equal(x.store.list('briefings').length,0);assert.ok(x.store.list('aiJobs').every(j=>j.status==='failed'));});
