'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const {openStore}=require('../src/services/store.cjs'),{createWorkflow}=require('../src/services/workflow.cjs');
function setup(t){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'calendar-history-review-')),store=openStore(dir),flow=createWorkflow(store,{read:()=>({profile:{values:{basic:[{}]}}})},{clock:()=> '2028-03-20T12:00:00Z'});store.put('organizations',{id:'org',name:'Company'});t.after(()=>{store.close();fs.rmSync(dir,{recursive:true,force:true});});return{store,flow};}
const eventInput={organizationId:'org',title:'Interview',type:'interview',timezone:'UTC'};
test('calendar review: successive event reschedules retain each historical destination across leap month',t=>{const {flow}=setup(t);let e=flow.event({...eventInput,startsAt:'2028-02-28T10:00:00Z'});e=flow.event({...e,startsAt:'2028-02-29T11:00:00Z'});e=flow.event({...e,startsAt:'2028-03-01T12:00:00Z'});const feb=flow.calendar('2028-02','UTC','planned'),mar=flow.calendar('2028-03','UTC','planned');assert.equal(feb.details['2028-02-28'].changes[0].to,'2028-02-29');assert.equal(feb.details['2028-02-29'].changes[0].to,'2028-03-01');assert.equal(feb.cells['2028-02-28'],undefined);assert.equal(mar.cells['2028-03-01'],1);assert.equal(Object.keys(feb.dayCoverage).length,29);});
test('calendar review: manual and plan tasks retain prior dates without increasing completed heat',t=>{const {store,flow}=setup(t);let task=flow.task({title:'Prepare',plannedOn:'2028-03-01'});task=flow.task({...task,plannedOn:'2028-03-02'});task=flow.task({...task,plannedOn:'2028-03-03'});store.put('opportunities',{id:'job',organizationId:'org',title:'Job'});let plan=flow.plan({organizationId:'org',opportunityId:'job',plannedOn:'2028-03-04'});flow.plan({...plan,plannedOn:'2028-03-05'});const c=flow.calendar('2028-03','UTC');assert.equal(c.details['2028-03-01'].changes[0].to,'2028-03-02');assert.equal(c.details['2028-03-02'].changes[0].to,'2028-03-03');assert.equal(c.details['2028-03-04'].changes[0].to,'2028-03-05');assert.deepEqual(c.cells,{});});
test('calendar review: actual completion day beats planned day and duplicate completion never inflates heat',t=>{const {store,flow}=setup(t);const e=flow.event({...eventInput,startsAt:'2028-02-29T10:00:00Z'});let task=store.get('tasks','task-event-'+e.id);task=flow.completeTask({id:task.id,revision:task.revision,completedAt:'2028-03-01T01:00:00Z',result:'Completed late'});flow.completeTask({id:task.id,revision:task.revision});assert.equal(flow.calendar('2028-02','UTC').completed,0);const c=flow.calendar('2028-03','UTC');assert.equal(c.cells['2028-03-01'],1);assert.equal(c.completed,1);assert.equal(c.details['2028-03-01'].completed[0].result,'Completed late');});
test('calendar review: cancellation and revoke remove completed heat while status history survives',t=>{const {flow}=setup(t);let task=flow.task({title:'Work',plannedOn:'2028-03-02'});task=flow.completeTask({id:task.id,revision:task.revision,completedAt:'2028-03-02T10:00:00Z'});task=flow.taskStatus({id:task.id,revision:task.revision,status:'pending'});assert.equal(flow.calendar('2028-03','UTC').completed,0);task=flow.taskStatus({id:task.id,revision:task.revision,status:'cancelled'});const c=flow.calendar('2028-03','UTC','planned');assert.equal(c.cells['2028-03-02'],undefined);assert.ok(c.details['2028-03-02'].changes.some(x=>x.status==='cancelled'));assert.throws(()=>flow.completeTask({id:task.id,revision:task.revision}),/取消/);});
test('calendar review: actual timestamps use chosen timezone at leap-day boundary',t=>{const {flow}=setup(t);const task=flow.task({title:'TZ',plannedOn:'2028-02-29'});flow.completeTask({id:task.id,revision:task.revision,completedAt:'2028-02-29T23:30:00Z'});assert.equal(flow.calendar('2028-02','UTC').cells['2028-02-29'],1);assert.equal(flow.calendar('2028-03','Asia/Shanghai').cells['2028-03-01'],1);assert.equal(flow.calendar('2028-03','Asia/Shanghai').activeDays,1);});
test('calendar review: successful mailbox polls do not establish zero-activity coverage; failures remain explicit',t=>{const {store,flow}=setup(t);for(const [id,status,day]of [['ok','completed','01'],['bad','failed','02'],['interrupted','interrupted','03']])store.put('syncRuns',{id,kind:'mail',status,startedAt:`2028-03-${day}T10:00:00Z`,finishedAt:`2028-03-${day}T11:00:00Z`});flow.task({title:'manual',plannedOn:'2028-03-02'});const c=flow.calendar('2028-03','UTC');assert.equal(c.dayCoverage['2028-03-01'].status,'unknown');assert.equal(c.dayCoverage['2028-03-02'].status,'sync_failed');assert.equal(c.dayCoverage['2028-03-03'].status,'sync_failed');assert.equal(c.dayCoverage['2028-03-04'].status,'unknown');assert.equal(c.dayCoverage['2028-03-21'].status,'future');assert.deepEqual(c.cells,{});});
test('calendar review: changing time within same date remains visible as reschedule history',t=>{const {flow}=setup(t);let e=flow.event({...eventInput,startsAt:'2028-03-03T09:00:00Z'});flow.event({...e,startsAt:'2028-03-03T15:00:00Z'});const c=flow.calendar('2028-03','UTC');assert.equal(c.details['2028-03-03'].changes.length,1);assert.equal(c.details['2028-03-03'].changes[0].original.startsAt,'2028-03-03T09:00:00.000Z');assert.equal(c.details['2028-03-03'].changes[0].original.toSchedule.startsAt,'2028-03-03T15:00:00.000Z');});
test('calendar review: email-confirmed reschedule and cancellation retain message evidence on original day',t=>{const {store,flow}=setup(t),mail=require('../src/services/mail.cjs').createMail(store,flow);t.after(()=>mail.close());let e=flow.event({...eventInput,startsAt:'2028-03-05T10:00:00Z'});store.put('messages',{id:'message-a',subject:'Rescheduled'});let c=store.put('confirmations',{id:'confirm-a',kind:'mail_event',messageId:'message-a',status:'pending'});mail.confirm({id:c.id,revision:c.revision,action:'reschedule',eventId:e.id,eventRevision:e.revision,event:{...e,startsAt:'2028-03-06T10:00:00Z'}});let day=flow.calendar('2028-03','UTC').details['2028-03-05'];assert.equal(day.changes[0].source,'mail_user_confirmed');assert.equal(day.changes[0].evidenceId,'message-a');assert.equal(day.changes[0].to,'2028-03-06');e=store.get('events',e.id);store.put('messages',{id:'message-b',subject:'Cancelled'});c=store.put('confirmations',{id:'confirm-b',kind:'mail_event',messageId:'message-b',status:'pending'});mail.confirm({id:c.id,revision:c.revision,action:'cancel',eventId:e.id,eventRevision:e.revision});day=flow.calendar('2028-03','UTC').details['2028-03-06'];assert.ok(day.changes.some(h=>h.status==='cancelled'&&h.evidenceId==='message-b'));assert.equal(flow.calendar('2028-03','UTC').completed,0);});
test('calendar review: title-only edit does not fabricate a reschedule but same-day end/deadline does',t=>{const {flow}=setup(t);let e=flow.event({...eventInput,startsAt:'2028-03-07T10:00:00Z',endsAt:'2028-03-07T11:00:00Z'});e=flow.event({...e,title:'New title'});assert.equal(flow.calendar('2028-03','UTC').details['2028-03-07'].changes.length,0);flow.event({...e,endsAt:'2028-03-07T12:00:00Z'});assert.equal(flow.calendar('2028-03','UTC').details['2028-03-07'].changes.length,1);});
