'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const {openStore}=require('../src/services/store.cjs'),{createHosted}=require('../src/services/hosted.cjs');
function setup(t,fetchImpl){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'cloud-client-review-')),store=openStore(dir),values=new Map([['hosted-token','account-token']]),vault={get:k=>values.get(k),set:(k,v)=>values.set(k,v),remove:k=>values.delete(k)};store.put('settings',{id:'hosted',baseUrl:'https://hosted.example',accountId:'a',email:'a@example.com'});const hosted=createHosted(store,{read(){throw Error('monitoring must never read personal facts');}},{vault,fetchImpl});t.after(()=>{hosted.close();store.close();fs.rmSync(dir,{recursive:true,force:true});});return{hosted,store,vault};}
const response=value=>new Response(JSON.stringify(value));

test('cloud review: missing consent rejects before any label or URL is sent',async t=>{let calls=0;const {hosted}=setup(t,async()=>{calls++;return response({});});for(const confirmed of [false,undefined])await assert.rejects(hosted.monitoring('add',{label:'Private selection',url:'https://recruit.example/path',confirmed}),/确认/);assert.equal(calls,0);});

test('cloud review: add sends only selected label/link/consent, never profile or application metadata',async t=>{let sent;const {hosted}=setup(t,async(url,options)=>{sent={url,data:JSON.parse(options.body)};return response({id:'monitor'});});await hosted.monitoring('add',{label:'Selected company',url:'https://recruit.example/path#fragment',confirmed:true,profile:{name:'PRIVATE_FACT'},applicationId:'PRIVATE_APP',cookie:'PRIVATE_COOKIE',password:'PRIVATE_PASSWORD'});assert.equal(sent.url,'https://hosted.example/monitoring/add');assert.deepEqual(sent.data,{label:'Selected company',url:'https://recruit.example/path',confirmed:true});assert.doesNotMatch(JSON.stringify(sent),/PRIVATE_/);});

test('cloud review: logout revokes session without silently pausing or deleting cloud monitors',async t=>{const calls=[];const {hosted,vault}=setup(t,async(url)=>{calls.push(url);return response({ok:true});});await hosted.logout();assert.deepEqual(calls,['https://hosted.example/auth/logout']);assert.equal(vault.get('hosted-token'),undefined);assert.equal(hosted.config().connected,false);});

function cloudUI(api,state={hosted:{connected:true,baseUrl:'https://hosted.example'}}){const lines=fs.readFileSync(path.join(__dirname,'../src/ui/workbench.js'),'utf8').split('\n');const source=lines.find(l=>l.includes('async function cloudOpen()'))+'\n'+lines.find(l=>l.includes('async function cloudAdd()'));const h=value=>String(value).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;');return new Function('api','state','h','modal','button','hostedLogin','field','submit','let cloudState=null;'+source+';return {cloudOpen,cloudAdd};')(api,state,h,(title,subtitle,html,submit)=>({title,subtitle,html,submit}),(action,label,id)=>`<button data-action="${action}">${label}</button>`,()=>({login:true}),()=>'',()=> '');}

test('cloud review: disabled service UI keeps stop/delete controls and explains ongoing cloud execution',async()=>{const ui=cloudUI(async()=>({enabled:false,lastTick:null,monitors:[{id:'m',label:'<script>evil</script>',url:'https://recruit.example',enabled:1,status:'success'}],notices:[]}));const panel=await ui.cloudOpen();assert.match(panel.html,/cloud-toggle/);assert.match(panel.html,/cloud-remove/);assert.doesNotMatch(panel.html,/data-action="cloud-add"/);assert.match(panel.html,/退出账号不暂停监控/);assert.match(panel.html,/不含邮箱同步、截止提醒或外部渠道推送/);assert.doesNotMatch(panel.html,/<script>/);assert.match(panel.html,/&lt;script&gt;/);});

test('cloud review: add UI visibly requires explicit ongoing authorization to named service',async()=>{const calls=[],ui=cloudUI(async(action,input)=>{calls.push({action,input});return{};});const panel=await ui.cloudAdd();assert.match(panel.html,/name="confirmed"[^>]*required/);assert.match(panel.html,/https:\/\/hosted.example/);assert.match(panel.html,/持续每日检查，直到我暂停或删除/);await panel.submit({label:'Company',url:'https://recruit.example',confirmed:'on'});assert.deepEqual(calls[0],{action:'cloud-monitoring',input:{action:'add',label:'Company',url:'https://recruit.example',confirmed:true}});});
