'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const {openStore}=require('../src/services/store.cjs'),{createSearch}=require('../src/services/search.cjs'),{buildSearchPlan,createDiscoverySearch}=require('../src/services/discovery-search.cjs');
const prefs=(conditions={route:['civil'],keyword:['技术']})=>({plans:[{id:'plan-a',name:'我的方案',conditions}]});
function deferred(){let resolve;const promise=new Promise(r=>resolve=r);return{promise,resolve};}
function fixture(t,preferences=prefs(),fetchOverride){const root=fs.mkdtempSync(path.join(os.tmpdir(),'daily-search-review-')),store=openStore(root),vaultData=new Map(),calls=[];let now=Date.parse('2026-10-03T00:00:00Z');store.put('preferences',{id:'main',...preferences});const search=createSearch(store,{vault:{get:id=>vaultData.get(id),set:(id,v)=>vaultData.set(id,v),remove:id=>vaultData.delete(id)},clock:()=>now,fetchImpl:async(url,options)=>{calls.push({url,options});return fetchOverride?fetchOverride(url,options):new Response(JSON.stringify({web:{results:[{title:'招聘线索',url:'https://example.org/job',description:'开放时间未知'}]}}));}});search.configure({enabled:true,confirmed:true,apiKey:'SYNTHETIC-KEY'});const daily=createDiscoverySearch(store,search,{clock:()=>now,autoStart:false});t.after(()=>{daily.close();search.close();store.close();fs.rmSync(root,{recursive:true,force:true});});const enable=(budget=2)=>daily.configure({enabled:true,budget,confirmed:true,signature:daily.preview().signature});const replace=p=>store.put('preferences',{...store.get('preferences','main'),...p},{expectedRevision:store.get('preferences','main').revision});return{store,search,daily,calls,enable,replace,clock:()=>now,advance:(ms=86400001)=>now+=ms};}
test('retrieval respects allowed and excluded routes while keeping conditions broad and old listings searchable',()=>{const p=buildSearchPlan({plans:[{id:'a',conditions:{route:['enterprise','civil','public'],direction:['技术'],city:['北京']}}],global:{route:['civil','public']},excluded:{route:['public']}});assert.ok(p.total>2);assert.ok(p.queries.every(q=>q.route==='civil'));assert.ok(p.queries.some(q=>q.query.includes('"软件"')));assert.ok(p.queries.some(q=>q.query.includes('"北京"')));assert.ok(p.queries.every(q=>!(q.query.includes('"软件"')&&q.query.includes('"北京"'))));assert.ok(p.queries.every(q=>!q.query.includes('2026')));});
test('multiple cards are interleaved and quoted original labels cannot inject operators or extra lines',()=>{const p=buildSearchPlan({plans:[{id:'a',conditions:{route:['civil'],direction:['技术']}},{id:'b',conditions:{route:['postgraduate'],keyword:['人工智能"\nsite:evil.test']}}]});assert.equal(p.queries[0].planId,'a');assert.equal(p.queries[1].planId,'b');assert.equal(p.queries[1].route,'postgraduate');assert.equal(p.queries[1].query.includes('\n'),false);assert.equal((p.queries[1].query.match(/"/g)||[]).length,2);});
test('single multi-route card gives each route early coverage despite many aliases',()=>{const p=buildSearchPlan(prefs({route:['enterprise','civil','public','postgraduate'],direction:['技术'],city:['北京']}));assert.equal(new Set(p.queries.slice(0,4).map(q=>q.route)).size,4);});
test('default is no calls; enabling requires visible current signature and confirmed 1-10 budget',async t=>{const x=fixture(t);await x.daily.tick();assert.equal(x.calls.length,0);for(const patch of [{confirmed:false},{signature:'old'},{budget:0},{budget:11}])assert.throws(()=>x.daily.configure({enabled:true,budget:2,confirmed:true,signature:x.daily.preview().signature,...patch}));assert.equal(x.calls.length,0);x.enable();assert.equal(x.daily.preview().settings.enabled,true);});
test('budget reserves full 24h window and repeated checks or reconfiguration cannot trigger extra calls',async t=>{const x=fixture(t,prefs({route:['civil'],direction:['技术']}));x.enable(3);await x.daily.tick();assert.equal(x.calls.length,3);await x.daily.tick();x.enable(5);await x.daily.tick();assert.equal(x.calls.length,3);x.advance();await x.daily.tick();assert.equal(x.calls.length,8);assert.ok(x.calls.every(c=>!new URL(c.url).searchParams.has('freshness')));});
test('paid results persist as evidence, deduplicate URL without inventing opportunities or open dates',async t=>{const x=fixture(t,prefs({route:['civil'],direction:['技术']}));x.enable(3);await x.daily.tick();assert.equal(x.store.list('snapshots').filter(s=>s.kind==='preference_search_result').length,3);const r=x.daily.results();assert.equal(r.length,1);assert.equal(r[0].evidence.length,3);assert.ok(r[0].firstDiscoveredAt);assert.equal(r[0].openedAt,undefined);assert.equal(x.store.list('opportunities').length,0);x.daily.close();const restarted=createDiscoverySearch(x.store,x.search,{clock:x.clock,autoStart:false});assert.deepEqual(restarted.results(),r);await restarted.tick();assert.equal(x.calls.length,3);restarted.close();});
test('changed preferences before cycle disable scheduling and require new approval without network',async t=>{const x=fixture(t);x.enable();x.replace(prefs({route:['postgraduate'],keyword:['物理']}));await x.daily.tick();assert.equal(x.calls.length,0);assert.equal(x.daily.preview().settings.enabled,false);assert.equal(x.daily.preview().requiresApproval,true);});
test('changed preferences during request discard late old-scope results and do not mark ready',async t=>{const d=deferred(),x=fixture(t,prefs(),()=>d.promise);x.enable(1);const run=x.daily.tick();x.replace(prefs({route:['postgraduate'],keyword:['物理']}));d.resolve(new Response(JSON.stringify({web:{results:[{title:'过期范围',url:'https://example.org/old'}]}})));await run;assert.equal(x.daily.results().length,0);assert.notEqual(x.store.list('discoveryRuns').find(r=>r.kind==='preference_search').status,'ready');});
test('cancel discards late response and preserves cost reservation without replay',async t=>{const d=deferred(),x=fixture(t,prefs(),()=>d.promise);x.enable(2);const run=x.daily.tick();x.daily.cancel();assert.equal(x.calls[0].options.signal.aborted,true);d.resolve(new Response(JSON.stringify({web:{results:[{title:'late',url:'https://example.org/late'}]}})));await run;assert.equal(x.daily.results().length,0);assert.equal(x.store.list('discoveryRuns').find(r=>r.kind==='preference_search').status,'cancelled');await x.daily.tick();assert.equal(x.calls.length,1);});
test('closing active daily search marks interrupted and restart never replays reserved cycle',async t=>{const d=deferred(),x=fixture(t,prefs(),()=>d.promise);x.enable();const run=x.daily.tick();x.daily.close();d.resolve(new Response(JSON.stringify({web:{results:[]}})));await run;assert.equal(x.store.list('discoveryRuns').find(r=>r.kind==='preference_search').status,'interrupted');const restarted=createDiscoverySearch(x.store,x.search,{clock:x.clock,autoStart:false});await restarted.tick();assert.equal(x.calls.length,1);restarted.close();});
test('request failure consumes reserved attempt and retains earlier successful results',async t=>{let n=0;const x=fixture(t,prefs({route:['civil'],direction:['技术']}),async()=>++n===2?new Response('',{status:503}):new Response(JSON.stringify({web:{results:[{title:'first',url:'https://example.org/first'}]}})));x.enable(3);await x.daily.tick();assert.equal(x.calls.length,2);assert.equal(x.daily.results().length,1);assert.equal(x.store.list('discoveryRuns').find(r=>r.kind==='preference_search').status,'failed');await x.daily.tick();assert.equal(x.calls.length,2);});
test('daily discovery shares manual rolling 20-attempt provider cap',async t=>{const x=fixture(t);for(let i=0;i<20;i++)x.store.put('discoveryRuns',{id:'manual-'+i,kind:'web_search',status:'failed',startedAt:x.clock()});x.enable();await x.daily.tick();assert.equal(x.calls.length,0);assert.equal(x.store.list('discoveryRuns').find(r=>r.kind==='preference_search').status,'failed');});
test('disabling daily config aborts active HTTP and cannot persist a late result',async t=>{const d=deferred(),x=fixture(t,prefs(),()=>d.promise);x.enable();const run=x.daily.tick();x.daily.configure({enabled:false,budget:2});assert.equal(x.calls[0].options.signal.aborted,true);d.resolve(new Response(JSON.stringify({web:{results:[{title:'late',url:'https://example.org/late'}]}})));await run;assert.equal(x.daily.results().length,0);assert.equal(x.daily.preview().settings.enabled,false);assert.equal(x.store.list('discoveryRuns').find(r=>r.kind==='preference_search').status,'cancelled');});
test('disabling search connection aborts active provider request and daily loop stops with no further dispatch',async t=>{const d=deferred(),x=fixture(t,prefs({route:['civil'],direction:['技术']}),()=>d.promise);x.enable(3);const run=x.daily.tick();x.search.configure({enabled:false});assert.equal(x.calls[0].options.signal.aborted,true);d.resolve(new Response(JSON.stringify({web:{results:[]}})));await run;assert.equal(x.daily.results().length,0);assert.equal(x.calls.length,1);x.advance();await x.daily.tick();assert.equal(x.calls.length,1);});
test('preferences changed inside reserved 24h window pause immediately instead of waiting until tomorrow',async t=>{const x=fixture(t);x.enable(1);await x.daily.tick();x.replace(prefs({route:['postgraduate'],keyword:['物理']}));await x.daily.tick();assert.equal(x.daily.preview().settings.enabled,false);assert.equal(x.calls.length,1);});
test('restart recovers running cycle without retry and next day resumes after uncertain cursor',async t=>{const x=fixture(t,prefs({route:['civil'],direction:['技术']}));x.enable(1);await x.daily.tick();const cycle=x.store.list('discoveryRuns').find(r=>r.kind==='preference_search');x.store.put('discoveryRuns',{...cycle,status:'running'},{expectedRevision:cycle.revision});const restarted=createDiscoverySearch(x.store,x.search,{clock:x.clock,autoStart:false});assert.equal(x.store.get('discoveryRuns',cycle.id).status,'interrupted');await restarted.tick();assert.equal(x.calls.length,1);x.advance();await restarted.tick();assert.equal(x.calls.length,2);assert.notEqual(new URL(x.calls[0].url).searchParams.get('q'),new URL(x.calls[1].url).searchParams.get('q'));restarted.close();});
test('later URL evidence updates description while preserving original discovery date and all queries',async t=>{let n=0;const x=fixture(t,prefs({route:['civil'],direction:['技术']}),async()=>new Response(JSON.stringify({web:{results:[{title:'版本'+(++n),url:'https://example.org/job',description:'描述'+n}]}})));x.enable(1);await x.daily.tick();const first=x.daily.results()[0];x.advance();await x.daily.tick();const later=x.daily.results()[0];assert.equal(later.firstDiscoveredAt,first.firstDiscoveredAt);assert.ok(later.lastDiscoveredAt>first.lastDiscoveredAt);assert.equal(later.title,'版本2');assert.equal(later.description,'描述2');assert.equal(later.evidence.length,2);});
test('postgraduate direction uses original research direction without enterprise recruiting alias expansion',()=>{const p=buildSearchPlan(prefs({route:['postgraduate'],direction:['技术']}));assert.ok(p.queries.some(q=>q.query.includes('"技术"')));assert.equal(p.queries.some(q=>/工程师|运维|售前/.test(q.query)),false);});
