'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const {openStore}=require('../src/services/store.cjs'),{createSearch}=require('../src/services/search.cjs'),{buildSearchPlan,createDiscoverySearch}=require('../src/services/discovery-search.cjs');
const preferences={id:'main',plans:[{id:'a',name:'技术路线',conditions:{route:['enterprise','civil'],direction:['技术']}},{id:'b',name:'上海销售',conditions:{route:['enterprise'],city:['上海'],direction:['销售']}}]};
function setup(t,fetchImpl){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'daily-search-')),store=openStore(dir);let now=Date.now();store.put('preferences',preferences);const secrets=new Map(),vault={get:k=>secrets.get(k),set:(k,v)=>secrets.set(k,v)},search=createSearch(store,{vault,fetchImpl,clock:()=>now});search.configure({enabled:true,confirmed:true,apiKey:'fixture'});let daily=createDiscoverySearch(store,search,{clock:()=>now,autoStart:false});t.after(()=>{daily.close();search.close();store.close();fs.rmSync(dir,{recursive:true,force:true});});return{store,search,get daily(){return daily;},advance:()=>now+=86400001,restart(){daily.close();daily=createDiscoverySearch(store,search,{clock:()=>now,autoStart:false});},enable(budget=4){daily.configure({enabled:true,budget,signature:daily.preview().signature,confirmed:true});}};}
test('query planner preserves route restrictions, rotates cards/routes, leaves dates unrestricted',()=>{const p=buildSearchPlan(preferences);assert.deepEqual(p.queries.slice(0,4).map(q=>[q.planId,q.route]),[['a','enterprise'],['b','enterprise'],['a','civil'],['b','enterprise']]);const restricted=buildSearchPlan({...preferences,global:{route:['civil']}});assert.ok(restricted.total>0);assert.ok(restricted.queries.every(q=>q.route==='civil'));assert.ok(p.queries.every(q=>q.query.length<=200&&!/[\r\n]/.test(q.query)));assert.ok(p.queries.some(q=>q.query.includes('软件')));assert.equal(buildSearchPlan({...preferences,excluded:{route:['enterprise','civil']}}).total,0);});
test('no network before explicit daily consent; bounded cycle persists all evidence and restart does not replay',async t=>{let calls=0;const f=setup(t,async()=>{calls++;return new Response(JSON.stringify({web:{results:[{title:'岗位',url:'https://example.com/job',description:'未核验'}]}}));});await f.daily.tick();assert.equal(calls,0);assert.throws(()=>f.daily.configure({enabled:true,budget:4,signature:f.daily.preview().signature}),/确认/);f.enable();await f.daily.tick();assert.equal(calls,4);assert.equal(f.daily.results().length,1);assert.equal(f.daily.results()[0].evidence.length,4);assert.equal(f.store.list('opportunities').length,0);f.restart();await f.daily.tick();assert.equal(calls,4);assert.equal(f.daily.results()[0].evidence.length,4);f.advance();await f.daily.tick();assert.equal(calls,8);assert.equal(f.daily.results()[0].evidence.length,8);});
test('changing preferences while awaiting search suspends schedule and discards obsolete result',async t=>{let resolve;const f=setup(t,()=>new Promise(r=>resolve=r));f.enable(1);const pending=f.daily.tick();const old=f.store.get('preferences','main');f.store.put('preferences',{...old,global:{city:['北京']}},{expectedRevision:old.revision});resolve(new Response(JSON.stringify({web:{results:[{title:'旧',url:'https://example.com/old'}]}})));await pending;assert.equal(f.daily.results().length,0);assert.equal(f.daily.preview().settings.enabled,false);assert.equal(f.store.list('discoveryRuns').find(r=>r.kind==='preference_search').status,'cancelled');});
test('cancel propagates to provider and never starts remaining queries',async t=>{let resolve,calls=0,signal;const f=setup(t,async(u,o)=>{calls++;signal=o.signal;return new Promise(r=>resolve=r);});f.enable(4);const pending=f.daily.tick();f.daily.cancel();assert.ok(signal.aborted);resolve(new Response(JSON.stringify({web:{results:[]}})));await pending;assert.equal(calls,1);assert.equal(f.daily.results().length,0);assert.equal(f.store.list('discoveryRuns').find(r=>r.kind==='preference_search').status,'cancelled');await f.daily.tick();assert.equal(calls,1);});
test('failed provider attempts consume shared budget and advance cursor, without claiming coverage',async t=>{let calls=0;const f=setup(t,async()=>{calls++;throw Error('secret-provider-error');});f.enable(10);await f.daily.tick();assert.equal(calls,1);assert.equal(f.daily.preview().cursor,1);assert.equal(f.store.list('discoveryRuns').find(r=>r.kind==='preference_search').status,'failed');assert.ok(!JSON.stringify(f.store.list('discoveryRuns')).includes('secret-provider-error'));await f.daily.tick();assert.equal(calls,1);});
