'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const {openStore}=require('../src/services/store.cjs'),{createWorkflow}=require('../src/services/workflow.cjs'),{createDiscovery,fingerprint,applyFeedback}=require('../src/services/discovery.cjs');
function setup(t){const root=fs.mkdtempSync(path.join(os.tmpdir(),'discovery-review-')),store=openStore(root);let now=Date.parse('2026-10-03T00:00:00Z');const clock=()=>new Date(now).toISOString(),profile={values:{basic:[{highestEducation:'本科'}]}};const workflow=createWorkflow(store,{read:()=>({profile})},{clock}),discovery=createDiscovery(store,{clock}),org=workflow.organization({name:'公司'});const job=workflow.opportunity({organizationId:org.id,title:'岗位',city:['北京','上海'],route:'enterprise',openStatus:'open',statusVerified:true,evidence:'官网申请入口',eligibility:{anyOf:[[{field:'highestEducation',operator:'minimum',values:['本科'],verified:true,evidence:'本科及以上'}]]}});t.after(()=>{store.close();fs.rmSync(root,{recursive:true,force:true});});return {store,workflow,discovery,job,profile,advance:ms=>now+=ms,current:()=>workflow.recommendations().find(o=>o.id===job.id),feedback:(extra={})=>discovery.feedback({id:job.id,revision:store.get('opportunities',job.id).revision,kind:'not_interested',reason:'个人选择',days:7,...extra})};}
test('feedback and restore preserve applied lifecycle plus plan/application records',t=>{const x=setup(t);const p=x.workflow.plan({organizationId:x.job.organizationId,opportunityId:x.job.id,plannedOn:'2026-10-05'});const app=x.workflow.startApplication(p.id);x.workflow.collect(x.job.id,'applied');const beforePlans=x.store.list('plans'),beforeApps=x.store.list('applications');x.feedback();assert.equal(x.current().userState,'applied');assert.equal(x.current().feedbackHidden,true);x.feedback({kind:'none',reason:'',days:0});assert.equal(x.current().userState,'applied');assert.equal(x.current().feedbackHidden,false);assert.deepEqual(x.store.list('plans'),beforePlans);assert.deepEqual(x.store.list('applications'),beforeApps);});
test('feedback restoration never overrides independently failed qualification',t=>{const x=setup(t);x.profile.values.basic[0].highestEducation='大专';assert.equal(x.current().match.included,false);x.feedback({kind:'condition_mismatch',reason:'学历暂不符'});assert.equal(x.current().match.filterOrigin,'user');assert.equal(x.current().qualificationMatch.qualification.state,'fail');x.feedback({kind:'none',reason:'',days:0});assert.equal(x.current().match.included,false);assert.equal(x.current().match.qualification.state,'fail');x.profile.values.basic[0].highestEducation='本科';assert.equal(x.current().match.included,true);});
test('seen remains visible; expiry occurs exactly at boundary; sibling opportunity is unaffected',t=>{const x=setup(t);const sibling=x.workflow.opportunity({organizationId:x.job.organizationId,title:'另一岗位'});x.feedback({kind:'seen'});assert.equal(x.current().feedbackHidden,false);x.feedback();assert.equal(x.workflow.recommendations().find(o=>o.id===sibling.id).feedbackHidden,false);x.advance(7*86400000-1);assert.equal(x.current().feedbackHidden,true);x.advance(1);assert.equal(x.current().feedbackHidden,false);});
test('material change restores opportunity once and acknowledgment suppresses repeat indicator',t=>{const x=setup(t);x.feedback({days:0});let o=x.store.get('opportunities',x.job.id);x.store.put('opportunities',{...o,deadline:'2026-11-01'},{expectedRevision:o.revision});assert.equal(x.current().feedbackHidden,false);assert.equal(x.current().feedbackChanged,true);x.discovery.acknowledge(x.job.id,x.store.get('opportunities',x.job.id).revision);assert.equal(x.current().feedbackChanged,false);assert.equal(x.current().feedbackHidden,false);o=x.store.get('opportunities',x.job.id);x.store.put('opportunities',{...o,deadline:'2026-11-02'},{expectedRevision:o.revision});assert.equal(x.current().feedbackChanged,true);});
test('cosmetic source evidence and description changes do not automatically remove manual feedback',t=>{const x=setup(t);x.feedback({days:0});const o=x.store.get('opportunities',x.job.id);x.store.put('opportunities',{...o,description:'包装文字变化',evidence:'更新抓取时间',lastVerifiedAt:'2026-10-04T00:00:00Z'},{expectedRevision:o.revision});assert.equal(x.current().feedbackHidden,true);assert.equal(x.current().feedbackChanged,false);});
test('legacy ignored records restore safely; invalid inputs never write user feedback',t=>{const x=setup(t);for(const extra of [{kind:'bad'},{reason:null},{reason:'x'.repeat(1001)},{kind:'condition_mismatch',reason:'   '},{days:-1},{days:'7'},{days:365}])assert.throws(()=>x.feedback(extra));assert.equal(x.store.list('userOpportunities').length,0);x.workflow.collect(x.job.id,'ignored');assert.equal(x.current().feedbackHidden,true);x.feedback({kind:'none',reason:'',days:0});assert.equal(x.current().feedbackHidden,false);assert.equal(x.current().userState,'new');});
test('set-valued tag reordering must not count as material change',t=>{const x=setup(t);x.feedback({days:0});const o=x.store.get('opportunities',x.job.id);x.store.put('opportunities',{...o,city:['上海','北京']},{expectedRevision:o.revision});assert.equal(x.current().feedbackHidden,true);assert.equal(x.current().feedbackChanged,false);});
test('stale feedback and acknowledgment cannot silently acknowledge unseen opportunity version',t=>{const x=setup(t);x.feedback();const old=x.store.get('opportunities',x.job.id);x.store.put('opportunities',{...old,deadline:'2026-11-01'},{expectedRevision:old.revision});const before=x.store.list('userOpportunities');assert.throws(()=>x.feedback({revision:old.revision}),/岗位已更新/);assert.throws(()=>x.discovery.acknowledge(x.job.id,old.revision),/岗位已更新/);assert.throws(()=>x.discovery.acknowledge(x.job.id),/岗位已更新/);assert.deepEqual(x.store.list('userOpportunities'),before);assert.equal(x.current().feedbackChanged,true);});
test('restored feedback does not generate phantom change prompts',t=>{const x=setup(t);x.feedback({kind:'none',reason:'',days:0});const old=x.store.get('opportunities',x.job.id);x.store.put('opportunities',{...old,deadline:'2026-11-01'},{expectedRevision:old.revision});assert.equal(x.current().feedbackHidden,false);assert.equal(x.current().feedbackChanged,false);});
test('real browser filtering places manual suppression in filtered view and restore returns it',t=>{const x=setup(t),browser=require('../src/ui/opportunity-browser.js');x.feedback();assert.equal(browser.browse(x.workflow.recommendations()).list.length,0);assert.equal(browser.browse(x.workflow.recommendations(),{tier:'excluded'}).list.length,1);x.feedback({kind:'none',reason:'',days:0});assert.equal(browser.browse(x.workflow.recommendations()).list.length,1);});
