'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),{randomUUID}=require('node:crypto');
const {openStore}=require('../src/services/store.cjs'),{createWorkflow}=require('../src/services/workflow.cjs'),{eventContext}=require('../src/services/event-context.cjs'),{createBriefings}=require('../src/services/briefings.cjs'),{createHosted}=require('../src/services/hosted.cjs');
function setup(t){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'event-association-review-')),store=openStore(dir),facts={read:()=>({hash:'h',profile:{values:{basic:[{}]}}})},flow=createWorkflow(store,facts);for(const id of ['org-a','org-b'])store.put('organizations',{id,name:id});for(const [id,org]of [['job-a','org-a'],['job-b','org-a'],['job-c','org-b']])store.put('opportunities',{id,organizationId:org,title:id,description:'JD '+id});for(const [id,job,org]of [['plan-a','job-a','org-a'],['plan-b','job-b','org-a'],['plan-c','job-c','org-b']])store.put('plans',{id,opportunityId:job,organizationId:org,status:'planned'});store.put('applications',{id:'app-a',organizationId:'org-a',planId:'plan-a',opportunityId:'job-a',status:'draft'});t.after(()=>{store.close();fs.rmSync(dir,{recursive:true,force:true});});return{store,flow,facts};}
const args={organizationId:'org-a',type:'interview',title:'技术一面'};
const change=(s,table,id,data)=>{const old=s.get(table,id);return s.put(table,{...old,...data},{expectedRevision:old.revision});};
test('event association review: same company different jobs selected exactly, no application creation',t=>{const {store,flow}=setup(t),count=store.list('applications').length;const a=flow.event({...args,applicationId:'app-a'}),b=flow.event({...args,planId:'plan-b'});assert.equal(a.planId,'plan-a');assert.equal(a.opportunityId,'job-a');assert.equal(b.applicationId,'');assert.equal(b.opportunityId,'job-b');assert.equal(eventContext(store,b).opportunity.description,'JD job-b');assert.equal(store.list('applications').length,count);assert.equal(store.get('plans','plan-b').status,'planned');});
test('event association review: legacy application-only event resolves JD and migration on edit',t=>{const {store,flow}=setup(t);const old=store.put('events',{id:'legacy',...args,applicationId:'app-a'});assert.equal(eventContext(store,old).opportunity.id,'job-a');const edited=flow.event({...old,title:'二面'});assert.equal(edited.planId,'plan-a');assert.equal(edited.opportunityId,'job-a');});
test('event association review: edits preserve history and reject cross-org or mixed application/plan',t=>{const {store,flow}=setup(t);const e=flow.event({...args,applicationId:'app-a'});assert.throws(()=>flow.event({...e,organizationId:'org-b'}),/机构/);assert.throws(()=>flow.event({...e,planId:'plan-b'}),/不一致/);assert.throws(()=>flow.event({...args,planId:'plan-c'}),/机构/);const next=flow.event({...e,applicationId:'',planId:'plan-b'});assert.equal(next.opportunityId,'job-b');assert.equal(next.history.at(-1).applicationId,'app-a');assert.equal(next.history.at(-1).opportunityId,'job-a');assert.equal(store.get('tasks','task-event-'+e.id).applicationId,'');});
test('event association review: plan rebind rejects stale event until explicit edit',t=>{const {store,flow}=setup(t);const e=flow.event({...args,planId:'plan-b'});change(store,'plans','plan-b',{opportunityId:'job-a'});assert.throws(()=>eventContext(store,e),/变化/);const next=flow.event({...e});assert.equal(next.opportunityId,'job-a');assert.equal(eventContext(store,next).opportunity.id,'job-a');});
test('event association review: both AI paths use plan-only JD and persist opportunity revision',async t=>{const {store,flow,facts}=setup(t),event=flow.event({...args,planId:'plan-b'}),sent=[];const briefings=createBriefings(store,facts,{read:()=>({enabled:true})},{reader:async url=>({url,body:'<p>Public evidence for product and service used for this test only.</p>'}),invoke:async(_c,x)=>{sent.push(x.input);return{facts:[{sourceId:'S1',quote:'Public evidence'}],questions:[],hypotheses:[]};}});t.after(()=>briefings.close());const job=await briefings.run({eventId:event.id,requestId:randomUUID(),urls:['https://example.com'],confirmed:true});assert.deepEqual(sent[0].opportunity,{title:'job-b',description:'JD job-b'});assert.equal(job.opportunityRevision,store.get('opportunities','job-b').revision);assert.equal(store.get('briefings',job.briefingId).opportunityId,'job-b');const secrets=new Map(),vault={get:k=>secrets.get(k),set:(k,v)=>secrets.set(k,v),remove:k=>secrets.delete(k)},client=createHosted(store,facts,{vault,fetchImpl:async(_url,o)=>{sent.push(JSON.parse(o.body));return new Response(JSON.stringify({id:'quote',units:1,expiresAt:Date.now()+60000,successDefinition:'validated'}));}});t.after(()=>client.close());client.configure({baseUrl:'https://hosted.example'});vault.set('hosted-token','fake');change(store,'settings','hosted',{accountId:'account',email:'test@example.com'});const q=await client.quoteBriefing({eventId:event.id,urls:['https://example.com'],confirmed:true});assert.equal(sent[1].payload.description,'JD job-b');assert.equal(store.get('aiJobs',q.id).opportunityId,'job-b');assert.equal(store.get('aiJobs',q.id).opportunityRevision,store.get('opportunities','job-b').revision);});
test('event association review: plan clearing its job also invalidates old event linkage',t=>{const {store,flow}=setup(t),e=flow.event({...args,planId:'plan-b'});change(store,'plans','plan-b',{opportunityId:''});assert.throws(()=>eventContext(store,e),/变化/);});
test('event association review: meeting URL retains query and fragment and rejects unsafe schemes',t=>{const {store,flow}=setup(t);const url='https://meeting.example/join?meeting=123&passcode=TEST#room';const e=flow.event({...args,url});assert.equal(e.url,url);for(const url of ['javascript:alert(1)','file:///tmp/a','http://meeting.example','https://user:pass@meeting.example','https://127.0.0.1/','https://meeting.example:444/'])assert.throws(()=>flow.event({...args,url}));assert.equal(store.list('events').length,1);});
test('event association review: stale link fails both AI paths before provider or page read',async t=>{const {store,flow,facts}=setup(t);const e=flow.event({...args,planId:'plan-b'});change(store,'plans','plan-b',{opportunityId:'job-a'});let calls=0;const briefings=createBriefings(store,facts,{read:()=>({enabled:true})},{reader:async()=>{calls++;throw Error('must not read')},invoke:async()=>{calls++;throw Error('must not invoke')}}),client=createHosted(store,facts,{fetchImpl:async()=>{calls++;throw Error('must not call')}});t.after(()=>{briefings.close();client.close()});const input={eventId:e.id,urls:['https://example.com'],confirmed:true,requestId:randomUUID()};await assert.rejects(briefings.run(input),/变化/);await assert.rejects(client.quoteBriefing(input),/变化/);assert.equal(calls,0);assert.equal(store.list('aiJobs').length,0);});
test('event association review: explicit clearing removes linkage and history keeps previous selection',t=>{const {store,flow}=setup(t);const e=flow.event({...args,applicationId:'app-a'}),cleared=flow.event({...e,applicationId:'',planId:''});assert.equal(cleared.opportunityId,'');assert.equal(cleared.applicationId,'');assert.equal(cleared.planId,'');assert.equal(eventContext(store,cleared).opportunity,null);assert.equal(cleared.history.at(-1).applicationId,'app-a');assert.equal(store.get('tasks','task-event-'+e.id).applicationId,'');});
