'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const {publicLink,publicUrl}=require('../src/services/public-page.cjs'),{meetingUrl}=require('../src/services/event-context.cjs'),{safeUrl}=require('../src/dashboard-import.cjs'),{openStore}=require('../src/services/store.cjs'),{createWorkflow}=require('../src/services/workflow.cjs'),{createSources,extractJobs}=require('../src/services/sources.cjs');
const page='https://jobs.example.invalid/list?campus=2027';
const job=url=>JSON.stringify({'@type':'JobPosting',title:'工程师',identifier:{value:'role42'},hiringOrganization:{name:'公司'},url});
function fixture(t){const root=fs.mkdtempSync(path.join(os.tmpdir(),'explicit-link-review-')),store=openStore(root),workflow=createWorkflow(store,{read:()=>({profile:{values:{basic:[{}]}}})});let body=job('/job?id=42&lang=zh#/apply/42?stage=1'),requested='';const sources=createSources(store,workflow,{autoStart:false,reader:async url=>{requested=url;return {url,body}}});t.after(()=>{sources.close();store.close();fs.rmSync(root,{recursive:true,force:true});});return {store,workflow,sources,set:url=>body=job(url),requested:()=>requested,preview:async(url=page)=>{const result=await sources.preview({url}),c=store.get('confirmations',result.candidates[0].id);return {id:c.id,revision:c.revision,company:'公司',batch:'2027',confirmed:true};}};}
test('explicit public links and meetings retain query and SPA hash while fetch URLs omit only hash',()=>{const value='https://jobs.example.invalid:443/job?id=42&filter=a%26b#/apply/42?round=2';const normalized='https://jobs.example.invalid/job?id=42&filter=a%26b#/apply/42?round=2';assert.equal(publicLink(value),normalized);assert.equal(meetingUrl(value),normalized);assert.equal(publicUrl(value).href,'https://jobs.example.invalid/job?id=42&filter=a%26b');});
test('explicit links reject unsafe schemes, credentials, local literals and unsupported ports',()=>{for(const value of ['javascript:alert(1)','data:text/html,x','file:///etc/passwd','http://example.com/job','https://a:b@example.com/job','https://127.0.0.1/','https://0x7f000001/','https://2130706433/','https://[::1]/','https://localhost/','https://host.local/','https://example.com:444/']){assert.throws(()=>publicLink(value),undefined,value);assert.throws(()=>meetingUrl(value),undefined,value);}});
test('manual organization opportunity and event preserve explicit link destinations',t=>{const x=fixture(t),website='https://jobs.example.invalid/company?companyId=3#/campus',link='https://jobs.example.invalid/job?jobId=42#/apply?step=2',meeting='https://meet.example.invalid/room?room=7&passcode=synthetic#join';const org=x.workflow.organization({name:'公司',website}),o=x.workflow.opportunity({organizationId:org.id,title:'岗位',url:link}),event=x.workflow.event({organizationId:org.id,title:'面试',type:'interview',url:meeting});assert.equal(org.website,website);assert.equal(o.url,link);assert.equal(event.url,meeting);assert.throws(()=>x.workflow.opportunity({organizationId:org.id,title:'不应写入',url:'javascript:alert(1)'}));assert.equal(x.store.list('opportunities').length,1);});
test('first source confirmation keeps resolved query and hash exactly',async t=>{const x=fixture(t),input=await x.preview(),p=x.store.get('confirmations',input.id).proposal;assert.equal(p.url,'https://jobs.example.invalid/job?id=42&lang=zh#/apply/42?stage=1');assert.equal(x.sources.review(input).kind,'create');const o=x.sources.confirm(input);assert.equal(o.url,p.url);assert.equal(o.openStatus,'unknown');});
test('adopting only source URL retains query/hash and snapshots prior destination',async t=>{const x=fixture(t),old=x.sources.confirm(await x.preview());x.set('/job?jobId=42&locale=en#/new/apply?round=3');const input=await x.preview(),review=x.sources.review(input);assert.equal(review.kind,'update');assert.equal(review.changes.find(c=>c.key==='url').before,old.url);const saved=x.sources.confirm({...input,targetOpportunityId:review.opportunityId,opportunityRevision:review.opportunityRevision,updateFields:['url'],resetVerification:false});assert.equal(saved.url,'https://jobs.example.invalid/job?jobId=42&locale=en#/new/apply?round=3');const snapshot=x.store.list('snapshots')[0];assert.equal(snapshot.previous.url,old.url);assert.equal(snapshot.patch.url,saved.url);});
test('missing or rejected posting URL falls back to actual fetched page, never invented input SPA route',async t=>{const x=fixture(t);x.set(undefined);const input=await x.preview(page+'#/unexecuted-route');assert.equal(x.requested(),page);assert.equal(x.store.get('confirmations',input.id).proposal.url,page);for(const value of ['javascript:alert(1)','http://private.invalid','https://127.0.0.1/admin','https://user:secret@example.com/job'])assert.equal(extractJobs(job(value),page)[0].url,page);assert.equal(extractJobs(job('#/job/42?mode=apply'),page)[0].url,page+'#/job/42?mode=apply');});
test('non-string JSON-LD URL values are not coerced into fabricated path segments',()=>{for(const value of [123,true,{path:'/job'},['/job/42'],{'@id':'https://jobs.example.invalid/job?id=42'}])assert.equal(extractJobs(job(value),page)[0].url,page,JSON.stringify(value));});
test('legacy dashboard URL sanitization remains distinct and unchanged',()=>{assert.equal(safeUrl('https://user:secret@example.com/jobs?token=synthetic#/resume'),'https://example.com/jobs#/resume');assert.equal(safeUrl('https://example.com/jobs?jobId=42#/job?id=42'),'https://example.com/jobs');});
test('publicLink rejects nontext, blank and oversized manual inputs before coercion',()=>{for(const value of [null,undefined,123,true,{},['https://example.com/'],new URL('https://example.com/'),'','  ','https://example.com/'+'a'.repeat(8192)])assert.throws(()=>publicLink(value));});
test('legacy HTTP record previews and migrates without newly introduced protocol rejection',t=>{const x=fixture(t),legacy=require('../src/services/legacy.cjs').createLegacy(x.store,x.workflow),file=path.join(x.store.directory,'legacy-http.json'),original='http://jobs.example.invalid/job?id=42#/apply';fs.writeFileSync(file,JSON.stringify([{'记录ID':'http-old','公司名称':'历史单位','投递岗位':'旧岗位','投递链接':original}]));const p=legacy.preview(file);assert.equal(p.rows[0].url,'http://jobs.example.invalid/job#/apply');assert.deepEqual(legacy.migrate(file,{hash:p.hash,ids:p.rows.map(r=>r.id),confirmed:true}),{imported:1,skipped:0});assert.equal(x.store.list('opportunities')[0].url,'http://jobs.example.invalid/job#/apply');assert.equal(legacy.record(p.rows[0].id).original['投递链接'],original);});
test('manual explicitWebLink retains HTTP and custom port without relaxing fetch or meeting policies',t=>{const x=fixture(t),{explicitWebLink}=require('../src/services/public-page.cjs'),value='http://jobs.example.invalid:8080/job?jobId=42#/apply';assert.equal(explicitWebLink(value),value);const org=x.workflow.organization({name:'旧站',website:value}),o=x.workflow.opportunity({organizationId:org.id,title:'旧站岗位',url:value});assert.equal(org.website,value);assert.equal(o.url,value);assert.throws(()=>publicUrl(value));assert.throws(()=>publicLink(value));assert.throws(()=>meetingUrl(value));for(const bad of ['javascript:alert(1)','file:///tmp/job','ftp://example.com/job','http://user:pass@example.com/job',{},['https://example.com']])assert.throws(()=>explicitWebLink(bad));});
