'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),vm=require('node:vm');
const mapping=require('../src/ai-mapping.cjs');
const {validatePayload,validateResult,createProcessor}=require('../../hosted-service/processors.cjs');
const {openDatabase}=require('../../hosted-service/store.cjs'),{createJobs}=require('../../hosted-service/jobs.cjs');
const {openStore}=require('../src/services/store.cjs'),{createHosted}=require('../src/services/hosted.cjs');
const url='https://application.example/form';
const field=(id='field-1')=>({id,status:'pending',label:'称谓',labels:['称谓'],headings:['基本信息'],section:'basic',tag:'input',type:'text',selector:'#'+id,frameUrl:url,recordIdentity:{}});
const scope=()=>({url,applicationId:'app-a',candidates:[field()]});
const valid={mappings:[{id:'field-1',group:'basic',key:'name',confidence:.95,reason:'Label correspondence'}]};
const quote={id:'quote-test',units:5,expiresAt:Date.now()+600000,successDefinition:'Only usable mapping is charged'};
const remote=(id='aaaaaaaa-aaaa-4aaa-aaaa-aaaaaaaaaaaa',status='ready')=>({id,kind:'field-mapping',status,units:5,result:status==='ready'?valid:null});
const response=value=>new Response(JSON.stringify(value));

test('mapping review: provider input is selected metadata and catalog only',async()=>{const candidate={...field(),observedValue:'PRIVATE_VALUE',selector:'PRIVATE_SELECTOR',frameUrl:url+'?session=PRIVATE_SESSION',recordIdentity:{name:'PRIVATE_NAME'},html:'PRIVATE_HTML'};const payload=validatePayload('field-mapping',{fields:[candidate],facts:[{value:'PRIVATE_FACT'}]});let received;const process=createProcessor({}, {invoke:async(_config,args)=>{received=args.input;return valid;}});const output=await process('field-mapping',payload,{signal:new AbortController().signal});assert.equal(output.mappings.length,1);assert.equal(received.fields.length,1);assert.ok(received.catalog.length>0);assert.doesNotMatch(JSON.stringify(received),/PRIVATE_/);assert.deepEqual(Object.keys(received.fields[0]).sort(),['headings','id','labels','section','tag','type']);});

test('mapping review: missing, duplicate, out-of-scope and manual mappings rejected',()=>{const payload=validatePayload('field-mapping',{fields:[field()]});for(const result of [{mappings:[]},{mappings:[{...valid.mappings[0],confidence:.7}]},{mappings:[{...valid.mappings[0],id:'other'}]},{mappings:[valid.mappings[0],valid.mappings[0]]},{mappings:[{...valid.mappings[0],group:'education',key:'school'}]},{mappings:[{...valid.mappings[0],key:'nonexistent'}]},{mappings:[{...valid.mappings[0],key:'idNumber'}]}])assert.throws(()=>validateResult('field-mapping',result,payload));assert.throws(()=>validatePayload('field-mapping',{fields:[]}));assert.throws(()=>validatePayload('field-mapping',{fields:[field(),field()]}));});

test('mapping review: no usable suggestion releases balance; usable result settles only once',async t=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'mapping-billing-review-')),db=openDatabase(dir);db.run('INSERT INTO accounts(id,email,password,salt,balance,created_at) VALUES(?,?,?,?,?,?)','a','a@example.com','unused','unused',20,new Date().toISOString());let calls=0,result={mappings:[]};const jobs=createJobs(db,{prices:{'field-mapping':5},validatePayload,validateResult,processJob:async()=>{calls++;return result;}});t.after(()=>{jobs.close();db.close();fs.rmSync(dir,{recursive:true,force:true});});const payload={fields:[field()]};const submit=rid=>{const q=jobs.quote('a',{kind:'field-mapping',payload});return jobs.start('a',{kind:'field-mapping',payload,quoteId:q.id,requestId:rid,confirmed:true});};const failed=submit('mapping_empty');await new Promise(r=>setImmediate(r));assert.equal(jobs.read('a',failed.id).status,'failed');assert.equal(db.get('SELECT balance,reserved FROM accounts WHERE id=?','a').balance,20);assert.equal(db.get('SELECT reserved FROM accounts WHERE id=?','a').reserved,0);result=valid;const good=submit('mapping_valid');await new Promise(r=>setImmediate(r));assert.equal(jobs.read('a',good.id).status,'ready');assert.equal(submit('mapping_valid').id,good.id);assert.equal(calls,2);assert.equal(db.get('SELECT balance FROM accounts WHERE id=?','a').balance,15);});

function handlers(scanFn){const source=fs.readFileSync(path.join(__dirname,'../src/main.cjs'),'utf8'),registered={},calls=[];const context={busy:false,teaching:{active:false},aiTicket:null,aiScopeTicket:{token:'scope-token',...scope(),expires:Date.now()+60000},aiAbort:null,aiPageEpoch:0,activeApplicationId:'app-a',profile:{},workspace:'unused',Date,AbortController,Error,TypeError,handle:(name,fn)=>registered[name]=fn,push:()=>{},executionProfile:()=>({}),getPage:async()=>({url:()=>url}),scanPage:scanFn|| (async()=>({url,items:[field()]})),aiSettings:{read:()=>({enabled:false})},workbench:{hosted:{config:()=>({connected:true}),quoteMapping:async s=>{calls.push(['quote',s]);return quote;},mappingJob:()=>({id:'mapping-local',status:'ready',scope:scope(),suggestions:mapping.validateMappings(valid,[field()])}),start:async()=>{calls.push(['start']);return remote();}}},require:name=>name==='./ai-mapping.cjs'?{...mapping,confirmMappings:()=>{context.saved=true;return 1;}}:require(name)};vm.runInNewContext(source.slice(source.indexOf("  handle('ai-cancel'"),source.indexOf("  handle('runtime-info'")),context);return{context,registered,calls};}

test('mapping review: quote IPC requires explicit consent, live scope token and original application',async()=>{for(const mutate of [h=>h.context.aiScopeTicket.expires=0,h=>h.context.activeApplicationId='app-b',h=>h.context.aiScopeTicket.token='different']){const h=handlers();mutate(h);await assert.rejects(h.registered['ai-hosted']({action:'quote',token:'scope-token',ids:['field-1'],confirmed:true}));assert.equal(h.calls.length,0);assert.equal(h.context.busy,false);}const h=handlers();await assert.rejects(h.registered['ai-hosted']({action:'quote',token:'scope-token',ids:['field-1'],confirmed:false}));assert.equal(h.calls.length,0);});

test('mapping review: navigation during pre-quote rescan stops sending and restores ordinary busy state',async()=>{let resolve;const h=handlers(()=>new Promise(r=>resolve=r)),pending=h.registered['ai-hosted']({action:'quote',token:'scope-token',ids:['field-1'],confirmed:true});await new Promise(r=>setImmediate(r));h.context.aiPageEpoch++;resolve({url,items:[field()]});await assert.rejects(pending,/变化/);assert.equal(h.calls.length,0);assert.equal(h.context.busy,false);});

test('mapping review: start rejects changed application or changed field before reserving',async()=>{for(const change of ['application','field']){const h=handlers(async()=>({url,items:[change==='field'?{...field(),labels:['Different label']}:field()]}));if(change==='application')h.context.activeApplicationId='app-b';await assert.rejects(h.registered['ai-hosted']({action:'start',id:'mapping-local',confirmed:true}));assert.equal(h.calls.length,0);assert.equal(h.context.busy,false);}});

test('mapping review: application switch after result ticket invalidates confirmation before rescan',async()=>{const h=handlers();const ticket=await h.registered['ai-hosted']({action:'result',id:'mapping-local'});h.context.activeApplicationId='app-b';await assert.rejects(h.registered['ai-confirm']({token:ticket.token,ids:['field-1']}));assert.notEqual(h.context.saved,true);});

function clientSetup(t,fetchImpl){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'mapping-client-review-')),store=openStore(dir),values=new Map([['hosted-token','token-a']]),vault={get:k=>values.get(k),set:(k,v)=>values.set(k,v),remove:k=>values.delete(k)};store.put('settings',{id:'hosted',baseUrl:'https://hosted.example',accountId:'account-a',email:'a@example.com'});const client=createHosted(store,{read(){throw Error('mapping must never read personal profile facts');}},{vault,fetchImpl});t.after(()=>{client.close();store.close();fs.rmSync(dir,{recursive:true,force:true});});return{client,store};}

test('mapping review: native quote sends no source URL, selector, record identity or value',async t=>{let sent;const {client}=clientSetup(t,async(_url,options)=>{sent=JSON.parse(options.body);return response(quote);});const s=scope();s.candidates[0]={...field(),selector:'PRIVATE_SELECTOR',frameUrl:'https://private.example?token=PRIVATE_TOKEN',recordIdentity:{name:'PRIVATE_NAME'},observedValue:'PRIVATE_VALUE'};await client.quoteMapping(s);assert.equal(sent.kind,'field-mapping');assert.doesNotMatch(JSON.stringify(sent),/PRIVATE_|applicationId|https:/);assert.equal(sent.payload.fields.length,1);});

test('mapping review: concurrent ambiguous starts cannot replace newly established remote identity',async t=>{const pending=[];const {client,store}=clientSetup(t,url=>url.endsWith('/quotes')?Promise.resolve(response(quote)):new Promise(r=>pending.push(r)));const q=await client.quoteMapping(scope()),first=client.start({id:q.id,confirmed:true}),second=client.start({id:q.id,confirmed:true});pending[0](response(remote()));await first;pending[1](response(remote('bbbbbbbb-bbbb-4bbb-bbbb-bbbbbbbbbbbb')));await assert.rejects(second);assert.equal(store.get('aiJobs',q.id).remoteId,'aaaaaaaa-aaaa-4aaa-aaaa-aaaaaaaaaaaa');});

test('mapping review: ordinary rule fill remains callable without hosted account or model',async()=>{const source=fs.readFileSync(path.join(__dirname,'../src/main.cjs'),'utf8'),registered={};let filled=0;const context={handle:(name,fn)=>registered[name]=fn,activeApplicationId:null,busy:false,teaching:{active:false},profile:null,stop:false,lastReport:null,userData:'unused',Date,Object,Number,Error,AbortController,fillController:null,takeoverView:{setVisible(){},webContents:{focus(){},isDestroyed:()=>false}},guest:{webContents:{focus(){},isDestroyed:()=>false}},path,fs:{mkdirSync(){},appendFileSync(){}},executionProfile:()=>({values:{basic:[{name:'Local fact'}]}}),push(){},getPage:async()=>({}),ensureRendering:async()=>({ready:true}),require:name=>{assert.equal(name,'./fill-execution.cjs');return {runFill:async(_page,profile,_selections,{signal})=>{assert.equal(signal.aborted,false);filled++;assert.equal(profile.values.basic[0].name,'Local fact');return{counts:{filled:1},elapsedMs:1};}};},withRuntime:value=>value};vm.runInNewContext(source.slice(source.indexOf("  handle('run',"),source.indexOf("  handle('handoff',")),context);const result=await registered.run({mode:'fill',selections:{basic:0}});assert.equal(filled,1);assert.equal(result.counts.filled,1);assert.equal(context.busy,false);});
