'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const {openStore}=require('../src/services/store.cjs'),{createHosted,endpoint}=require('../src/services/hosted.cjs');
const response=value=>new Response(JSON.stringify(value));
const quote={id:'quote-id',units:10,expiresAt:Date.now()+600000,successDefinition:'Validated result'};
const result={sources:[{id:'S1',url:'https://source.example/product',text:'A verified source quotation.',capturedAt:new Date().toISOString(),contentHash:'hash'}],facts:[{sourceId:'S1',quote:'verified source'}],hypotheses:[],questions:[]};
const remote=(status='ready',body=result)=>({id:'aaaaaaaa-aaaa-4aaa-aaaa-aaaaaaaaaaaa',kind:'briefing',status,units:10,result:body});
function setup(t,fetchImpl){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'hosted-client-review-')),store=openStore(dir),secrets=new Map(),vault={get:k=>secrets.get(k),set:(k,v)=>secrets.set(k,v),remove:k=>secrets.delete(k)};store.put('organizations',{id:'org',name:'Company'});store.put('events',{id:'interview',type:'interview',organizationId:'org',title:'Interview'});const facts={read:()=>({hash:'profile-hash',profile:{values:{basic:[{name:'PRIVATE_NAME',phone:'PRIVATE_PHONE'}],education:[{school:'University',referencePhone:'PRIVATE_REFEREE'}],projects:[{name:'Project',description:'Worked on analytics'}]}}})};const client=createHosted(store,facts,{vault,fetchImpl});client.configure({baseUrl:'https://hosted.example'});vault.set('hosted-token','token-a');store.put('settings',{...store.get('settings','hosted'),accountId:'account-a',email:'a@example.com'},{expectedRevision:store.get('settings','hosted').revision});t.after(()=>{client.close();store.close();fs.rmSync(dir,{recursive:true,force:true});});return{client,store,vault};}
const input={eventId:'interview',urls:['https://source.example/product'],confirmed:true};

test('hosted review: endpoint rejects remote plaintext and URL credentials',()=>{for(const value of ['http://hosted.example','https://user:pass@hosted.example','https://hosted.example/path','https://hosted.example?secret=1'])assert.throws(()=>endpoint(value));assert.equal(endpoint('https://hosted.example/'),'https://hosted.example');assert.equal(endpoint('http://127.0.0.1:4318'),'http://127.0.0.1:4318');});

test('hosted review: explicit scope consent and experience projection precede quote request',async t=>{const calls=[],{client}=setup(t,async(url,options)=>{calls.push({url,data:JSON.parse(options.body)});return response(quote);});await assert.rejects(client.quoteBriefing({...input,confirmed:false}),/确认/);assert.equal(calls.length,0);await client.quoteBriefing(input);assert.equal(calls[0].data.payload.includeExperience,false);assert.equal(calls[0].data.payload.experiences,undefined);await client.quoteBriefing({...input,includeExperience:true});const sent=JSON.stringify(calls[1]);assert.match(sent,/University/);assert.doesNotMatch(sent,/PRIVATE_/);});

test('hosted review: ambiguous submission persists requestId and retry reuses it',async t=>{const submitted=[];const {client,store}=setup(t,async(url,options)=>{if(url.endsWith('/quotes'))return response(quote);submitted.push(JSON.parse(options.body));if(submitted.length===1)throw Error('response lost');return response(remote('running',null));});const q=await client.quoteBriefing(input);await assert.rejects(client.start({id:q.id,confirmed:true}),/response lost/);assert.equal(store.get('aiJobs',q.id).status,'pending_remote');await client.start({id:q.id,confirmed:true});assert.equal(submitted.length,2);assert.equal(submitted[0].requestId,submitted[1].requestId);assert.equal(submitted[0].quoteId,submitted[1].quoteId);});

test('hosted review: endpoint switch rejects stale response and removes stored token',async t=>{let resolve;const {client,vault,store}=setup(t,()=>new Promise(r=>resolve=r));const pending=client.quoteBriefing(input);client.configure({baseUrl:'https://other.example'});resolve(response(quote));await assert.rejects(pending,/切换/);assert.equal(vault.get('hosted-token'),undefined);assert.equal(store.list('aiJobs').length,0);assert.equal(client.config().accountId,'');});

test('hosted review: account switch rejects in-flight quote from previous account',async t=>{let resolve;const {client,store}=setup(t,(url)=>url.endsWith('/auth/login')?Promise.resolve(response({token:'token-b',account:{id:'account-b',email:'b@example.com'}})):new Promise(r=>resolve=r));const pending=client.quoteBriefing(input);await client.login({email:'b@example.com',password:'password-123'});resolve(response(quote));await assert.rejects(pending,/切换|取消/);assert.equal(store.list('aiJobs').length,0);assert.equal(client.config().accountId,'account-b');});

test('hosted review: source URLs outside quoted scope cannot enter local briefings',async t=>{const wrong={...result,sources:[{...result.sources[0],url:'https://unrequested.example/fabrication'}]};const {client,store}=setup(t,async(url)=>response(url.endsWith('/quotes')?quote:remote('ready',wrong)));const q=await client.quoteBriefing(input);await assert.rejects(client.start({id:q.id,confirmed:true}));assert.equal(store.list('briefings').length,0);});

test('hosted review: validated briefing delivered once with local event binding',async t=>{const {client,store}=setup(t,async(url)=>response(url.endsWith('/quotes')?quote:remote()));const q=await client.quoteBriefing(input);await client.start({id:q.id,confirmed:true});await client.refresh(q.id);assert.equal(store.list('briefings').length,1);assert.equal(store.list('briefings')[0].eventId,'interview');assert.match(store.list('briefings')[0].body,/verified source/);});

test('hosted review: mismatched remote job identity cannot overwrite known task',async t=>{const {client,store}=setup(t,async(url)=>response(url.endsWith('/quotes')?quote:url.endsWith('/jobs')?remote('running',null):{...remote(),id:'bbbbbbbb-bbbb-4bbb-bbbb-bbbbbbbbbbbb'}));const q=await client.quoteBriefing(input);await client.start({id:q.id,confirmed:true});await assert.rejects(client.refresh(q.id));assert.equal(store.list('briefings').length,0);assert.equal(store.get('aiJobs',q.id).remoteId,'aaaaaaaa-aaaa-4aaa-aaaa-aaaaaaaaaaaa');});

test('hosted review: logout response from old account cannot clear a newer login',async t=>{let resolve;const {client,vault}=setup(t,url=>url.endsWith('/auth/logout')?new Promise(r=>resolve=r):Promise.resolve(response({token:'token-b',account:{id:'account-b',email:'b@example.com'}})));const quitting=client.logout();await client.login({email:'b@example.com',password:'password-123'});resolve(response({ok:true}));await quitting;assert.equal(client.config().accountId,'account-b');assert.equal(vault.get('hosted-token'),'token-b');});

test('hosted review: ready response missing result cannot claim delivered briefing',async t=>{const {client,store}=setup(t,async(url)=>response(url.endsWith('/quotes')?quote:remote('ready',null)));const q=await client.quoteBriefing(input);await assert.rejects(client.start({id:q.id,confirmed:true}));assert.notEqual(store.get('aiJobs',q.id).status,'ready');assert.equal(store.list('briefings').length,0);});

test('hosted review: untrusted account numeric HTML is rejected before rendering',async t=>{const base={account:{id:'account-a',balance:100,reserved:0,available:100},catalog:{enabled:false,mode:'test',packs:[]},ledger:[],jobs:[]};let value=base;const {client}=setup(t,async()=>response(value));assert.equal((await client.account()).account.available,100);value={...base,account:{...base.account,available:'<img src=x onerror=alert(1)>'}};await assert.rejects(client.account(),/响应无效/);value={...base,catalog:{enabled:true,mode:'test',packs:[{id:'x',units:'<img src=x>',amount:100,currency:'usd'}]}};await assert.rejects(client.account(),/响应无效/);});

test('hosted review: late running response cannot downgrade cancelled task',async t=>{let resolve;const {client,store}=setup(t,url=>{if(url.endsWith('/quotes'))return Promise.resolve(response(quote));if(url.endsWith('/cancel'))return Promise.resolve(response(remote('cancelled',null)));if(url.endsWith('/jobs'))return Promise.resolve(response(remote('running',null)));return new Promise(r=>resolve=r);});const q=await client.quoteBriefing(input);await client.start({id:q.id,confirmed:true});const refreshing=client.refresh(q.id);await client.cancel(q.id);resolve(response(remote('running',null)));await refreshing;assert.equal(store.get('aiJobs',q.id).status,'cancelled');});

test('hosted review: recreated client retries stored payload and original request identity',async t=>{let firstRequest;const {client,store,vault}=setup(t,async(url,options)=>{if(url.endsWith('/quotes'))return response(quote);firstRequest=JSON.parse(options.body);throw Error('network response lost');});const q=await client.quoteBriefing({...input,includeExperience:true});await assert.rejects(client.start({id:q.id,confirmed:true}));client.close();let retry;const restored=createHosted(store,{read(){throw Error('must not reconstruct previously confirmed scope');}},{vault,fetchImpl:async(_url,options)=>{retry=JSON.parse(options.body);return response(remote('running',null));}});t.after(()=>restored.close());await restored.start({id:q.id,confirmed:true});assert.deepEqual(retry,firstRequest);});

test('hosted review: quote UI does not label a terminal failure as submitted',async()=>{const source=fs.readFileSync(path.join(__dirname,'../src/ui/workbench.js'),'utf8'),line=source.split('\n').find(s=>s.includes('async function hostedQuote(q)'));const panels=[];const modal=(title,subtitle,html,submit)=>{const panel={title,subtitle,html,submit};panels.push(panel);return panel;};const make=new Function('api','modal','h','submit','button',line+'; return hostedQuote;');const ui=make(async()=>({status:'failed',error:'No deliverable result'}),modal,String,()=>'',()=> '');await ui({...quote,id:'local-job'});let after;try{after=await panels[0].submit({confirmed:'on'});}catch(error){assert.match(error.message,/No deliverable result|失败|未交付/);return;}if(typeof after==='function')await after();assert.ok(panels.slice(1).every(p=>!p.title.includes('任务已提交')),'terminal failure must not show submitted success panel');});
