const fs=require('node:fs'),path=require('node:path'),os=require('node:os'),assert=require('node:assert/strict');
const {_electron}=require('playwright-core');
(async()=>{
 const root=path.resolve(__dirname,'../..'),workspace=fs.mkdtempSync(path.join(os.tmpdir(),'workbench-integrations-'));
 require('../../tools/copy-tree.cjs').copyTree(path.join(root,'templates/blank-workspace'),workspace);
 const legacy=path.join(workspace,'投递记录.json');fs.writeFileSync(legacy,JSON.stringify([{'记录ID':'legacy-smoke','公司名称':'迁移测试公司','投递岗位':'旧岗位','当前状态':'二面','官方节点时间':'下周三'}]));
 const mail=path.join(workspace,'invitation.eml'),pdf=path.join(workspace,'original.pdf'),backup=path.join(workspace,'archive.qzb');
 fs.writeFileSync(mail,'From: hr@example.invalid\r\nTo: user@example.invalid\r\nMessage-ID: <smoke@example.invalid>\r\nSubject: 测试公司面试通知\r\nContent-Type: text/plain; charset=utf-8\r\n\r\n面试时间：2026-10-04T10:00:00+08:00');
 fs.writeFileSync(pdf,'%PDF-1.4\n1 0 obj << /Type /Catalog /Pages 2 0 R >> endobj\n2 0 obj << /Type /Pages /Kids [3 0 R] /Count 1 >> endobj\n3 0 obj << /Type /Page /Parent 2 0 R /MediaBox [0 0 200 200] >> endobj\ntrailer << /Root 1 0 R >>\n%%EOF');
 const seed=require('../src/services/workbench.cjs').createWorkbench(workspace,{sourceReader:async url=>({url,body:JSON.stringify({'@type':'JobPosting',title:'来源核验工程师',hiringOrganization:{name:'来源测试公司'},identifier:'S05-1',description:'测试用公开岗位原文'})})});
 await seed.sources.preview({url:'https://source.example.invalid/job'});seed.close();
 const env={...process.env,QIUZHAO_TEST:'1',QIUZHAO_WORKSPACE:workspace,QIUZHAO_USER_DATA:path.join(workspace,'browser')};delete env.ELECTRON_RUN_AS_NODE;
 const app=await _electron.launch({executablePath:process.env.QIUZHAO_TEST_EXECUTABLE||require('electron'),args:process.env.QIUZHAO_TEST_EXECUTABLE?[]:[path.join(root,'desktop')],env});let restored;
 try{
  await app.firstWindow();let ui;for(let i=0;i<100;i++){ui=app.context().pages().find(p=>p.url().includes('/ui/index.html'));if(ui)break;await new Promise(r=>setTimeout(r,100));}assert(ui);await ui.waitForFunction(()=>!!window.workbenchUI);
  const errors=[];ui.on('pageerror',e=>errors.push(e.message));
  await app.evaluate(({dialog},{mail,pdf,backup,workspace,legacy})=>{dialog.showSaveDialog=async()=>({canceled:false,filePath:backup});dialog.showOpenDialog=async(_window,options)=>({canceled:false,filePaths:[options.title.includes('旧版投递记录')?legacy:options.title.includes('导入邮件')?mail:options.title.includes('导入简历')?pdf:options.title.includes('恢复位置')?workspace:backup]});},{mail,pdf,backup,workspace,legacy});
  await ui.evaluate(()=>window.workbenchUI.show('confirmations'));
  await ui.locator('[data-action="source-confirm-open"]').click();
  await ui.locator('#panel-body input[name="batch"]').fill('2027 校招');
  await ui.locator('#panel-body input[name="confirmed"]').check();
  await ui.locator('#panel-body button[type="submit"]').click();
  await ui.locator('#panel-body input[name="confirmed"]').check();
  await ui.locator('#panel-body button[type="submit"]').click();
  await ui.waitForFunction(()=>window.workbenchUI.getState().opportunities.some(o=>o.title==='来源核验工程师'&&o.openStatus==='unknown'));
  await ui.evaluate(()=>window.workbenchUI.show('opportunities'));
  await ui.locator('[data-action="source-schedule"]').click();
  await ui.locator('#panel-body input[name="enabled"]').check();
  await ui.locator('#panel-body input[name="confirmed"]').check();
  const sourceOrg=(await ui.evaluate(()=>window.workbenchUI.getState())).organizations.find(o=>o.name==='来源测试公司');
  await ui.locator('#panel-body select[name="organizationId"]').selectOption(sourceOrg.id);
  await ui.locator('#panel-body button[type="submit"]').click();
  await ui.waitForFunction(()=>window.workbenchUI.getState().sources.some(s=>s.enabled&&s.organizationId));
  await ui.locator('[data-action="source-schedule"]').click();
  await ui.locator('#panel-body input[name="enabled"]').uncheck();
  await ui.locator('#panel-body button[type="submit"]').click();
  await ui.waitForFunction(()=>window.workbenchUI.getState().sources.every(s=>!s.enabled));
  const org=await ui.evaluate(()=>call('workbench',{action:'organization',data:{name:'测试公司'}}));
  await ui.evaluate(()=>window.workbenchUI.show('connections'));
  await ui.locator('[data-action="mail-import"]').click();
  await ui.locator('[data-action="mail-confirm-open"]').click();
  await ui.locator('#panel-body input[name="endsAt"]').fill('2026-10-04T11:00');
  await ui.locator('#panel-body input[name="location"]').fill('线上');
  await ui.locator('#panel-body button[type="submit"]').click();
  await ui.waitForFunction(()=>window.workbenchUI.getState().events.length===1);
  assert.equal((await ui.evaluate(()=>window.workbenchUI.getState())).tasks.find(t=>t.origin==='event').status,'pending');
  await ui.evaluate(()=>window.workbenchUI.show('reminders'));
  await ui.locator('#wb-reminders-form input[name="digestHour"]').fill('0');
  await ui.locator('#wb-reminders-form button[type="submit"]').click();
  await ui.waitForFunction(()=>window.workbenchUI.getState().reminders.some(r=>r.kind==='digest'&&r.status==='delivered'));
  await ui.locator('[data-action="reminder-read"]').first().click();
  await ui.waitForFunction(()=>window.workbenchUI.getState().reminders.some(r=>r.readAt));
  await ui.evaluate(()=>window.workbenchUI.show('assets'));
  await ui.locator('[data-action="asset-import"]').first().click();
  await ui.waitForFunction(()=>window.workbenchUI.getState().assets.length===1);
  const asset=(await ui.evaluate(()=>window.workbenchUI.getState())).assets[0];
  const application=await ui.evaluate(async({org,asset})=>{const opportunity=await call('workbench',{action:'opportunity',data:{organizationId:org.id,title:'上传测试',url:'https://upload.example.invalid/application'}});const plan=await call('workbench',{action:'plan',data:{organizationId:org.id,opportunityId:opportunity.id}});const draft=await call('workbench',{action:'application-start',data:{planId:plan.id}});await call('workbench',{action:'application-asset',data:{applicationId:draft.id,assetId:asset.id}});return draft;},{org,asset});
  const page=app.context().pages().find(p=>p.url().includes('/fixtures/demo.html'));assert(page);
  await page.route('https://upload.example.invalid/**',route=>route.fulfill({contentType:'text/html; charset=utf-8',body:'<label>简历<input id="resume" type="file" accept=".pdf"></label><label>姓名<input name="name" value="用户手工内容"></label><label>输入六位数字<input name="otp" autocomplete="one-time-code" value="731942"></label>'}));
  await ui.evaluate(async id=>{await call('workbench',{action:'application-open',data:{id}});await window.workbenchUI.show('browser');},application.id);
  await page.locator('#resume').waitFor();
  await ui.locator('[data-action="upload-open"]').click();
  await ui.locator('#panel-body input[name="siteMaxMB"]').fill('0.5');
  await ui.locator('#panel-body button[type="submit"]').click();
  await page.waitForFunction(()=>document.querySelector('#resume').files.length===1);
  await ui.locator('#close-panel').click();
  await ui.locator('[data-action="upload-confirm"]').click();
  await ui.locator('#panel-body input[name="confirmed"]').check();
  await ui.locator('#panel-body button[type="submit"]').click();
  await ui.locator('#overlay').waitFor({state:'hidden'});
  const readback=await ui.evaluate(()=>call('workbench',{action:'application-readback'}));
  assert.equal(readback.fields.some(f=>f.value==='731942'),false);assert.ok(readback.fields.some(f=>f.value==='用户手工内容'));
  const saved=await ui.evaluate(()=>call('workbench',{action:'snapshot'}));assert.equal(saved.applications.find(a=>a.id===application.id).upload.state,'user_confirmed_received');
  await ui.evaluate(()=>window.workbenchUI.show('reminders'));
  await ui.locator('[data-action="legacy-preview"]').click();
  await ui.locator('#panel-body input[name="confirmed"]').check();
  await ui.locator('#panel-body button[type="submit"]').click();
  await ui.locator('#panel-body input[name="row"]').check();
  await ui.locator('#panel-body button[type="submit"]').click();
  await ui.locator('[data-action="legacy-review"]').click();
  assert.ok((await ui.locator('#panel-body').innerText()).includes('下周三'));
  await ui.locator('#panel-body input[name="confirmed"]').check();
  await ui.locator('#panel-body button[type="submit"]').click();
  await ui.waitForFunction(()=>window.workbenchUI.getState().confirmations.some(c=>c.kind==='legacy-record'&&c.status==='reviewed'));
  assert.equal((await ui.evaluate(()=>window.workbenchUI.getState())).events.length,1);
  await ui.evaluate(()=>window.workbenchUI.show('reminders'));
  await ui.locator('[data-action="backup-export"]').click();
  await ui.waitForTimeout(100);assert.ok(fs.existsSync(backup));
  await ui.locator('[data-action="backup-preview"]').click();
  await ui.locator('#panel-body button[type="submit"]').click();
  await ui.locator('#panel-title').filter({hasText:'备份已恢复'}).waitFor();
  restored=fs.readdirSync(workspace).find(name=>name.startsWith('招聘工作台-恢复-'));assert(restored);
  assert.deepEqual(errors,[]);
  console.log('PASS source and legacy migration/review, email import -> event confirmation, reminder settings/read, real input file upload/readback/privacy, and backup restore with controlled native dialogs');
 }finally{await app.close();}
 try{const copy=require('../src/services/workbench.cjs').createWorkbench(path.join(workspace,restored));try{assert.equal(copy.store.list('events').length,1);assert.equal(copy.store.list('messages').length,1);assert.equal(copy.store.list('assets').length,1);}finally{copy.close();}}finally{fs.rmSync(workspace,{recursive:true,force:true});}
})().catch(error=>{console.error(error);process.exitCode=1;});
