'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const {summary,next,imminent}=require('../src/ui/interview-preparation.js'),{createInterviewMaterials}=require('../src/services/interview-materials.cjs'),{openStore}=require('../src/services/store.cjs');
function state(){return{briefings:[{id:'b',eventId:'e',status:'ready',createdAt:'2026-10-01T10:00:00Z',eventRevision:2,opportunityId:'o',opportunityRevision:1,profileHash:'profile-old'}],aiJobs:[],opportunities:[{id:'o',revision:1,title:'Old job'}],applications:[],plans:[],profileHash:'profile-old'};}
const event=()=>({id:'e',type:'interview',revision:2,opportunityId:'o'});
function setup(t){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'interview-materials-review-')),store=openStore(dir);store.put('organizations',{id:'org',name:'Org'});const e=store.put('events',{id:'e',type:'interview',organizationId:'org',title:'Interview'});t.after(()=>{store.close();fs.rmSync(dir,{recursive:true,force:true})});return{store,e,service:createInterviewMaterials(store)};}
test('materials review: state chronology keeps old ready briefing readable while newer job runs or fails',()=>{const s=state(),e=event();s.aiJobs=[{id:'oldfail',eventId:'e',kind:'interview-briefing',createdAt:'2026-09-30',status:'failed'}];assert.equal(summary(e,s).status,'ready');s.aiJobs.push({id:'new',eventId:'e',kind:'hosted-briefing',createdAt:'2026-10-02',status:'queued'});assert.equal(summary(e,s).status,'running');s.aiJobs[1].status='failed';assert.equal(summary(e,s).status,'failed');assert.equal(summary(e,s).briefing.id,'b');s.briefings=[];s.aiJobs[1].status='quoted';assert.equal(summary(e,s).status,'quoted');s.aiJobs=[];assert.equal(summary(e,s).status,'empty');});
test('materials review: event, job revision, missing job and changed personal facts all flag stale',()=>{for(const alter of [s=>{s.briefings[0].eventRevision=1},s=>{s.opportunities[0].revision=2},s=>{s.opportunities=[]},s=>{s.profileHash='profile-new'}]){const s=state();alter(s);assert.equal(summary(event(),s).stale,true);assert.equal(summary(event(),s).status,'stale');}});
test('materials review: stale plan rebind or clear is visible before attempting generation',()=>{for(const id of ['other','']){const s=state(),e={...event(),planId:'p'};s.plans=[{id:'p',opportunityId:id}];assert.equal(summary(e,s).stale,true);}});
test('materials review: newest briefing selected by timestamp rather than input ordering',()=>{const s=state();s.briefings.unshift({...s.briefings[0],id:'new',createdAt:'2026-10-02T10:00:00Z'});assert.equal(summary(event(),s).briefing.id,'new');});
test('materials review: next focus chooses ongoing/next valid interview and exact end is excluded',()=>{const now=Date.parse('2026-10-03T10:00:00Z'),base={type:'interview',status:'scheduled'};const list=[{...base,id:'cancel',status:'cancelled',startsAt:'2026-10-03T09:30:00Z'},{...base,id:'done',status:'completed',startsAt:'2026-10-03T09:30:00Z'},{...base,id:'ended',startsAt:'2026-10-03T09:00:00Z'},{...base,id:'invalid',startsAt:'n/a'},{...base,id:'later',startsAt:'2026-10-03T12:00:00Z'},{...base,id:'ongoing',startsAt:'2026-10-03T09:45:00Z'}];assert.equal(next(list,now).id,'ongoing');assert.equal(imminent(list.at(-1),now),true);assert.equal(imminent({...base,startsAt:'2026-10-03T10:30:00Z'},now),true);assert.equal(imminent({...base,startsAt:'2026-10-03T10:30:01Z'},now),false);assert.equal(imminent(list[2],now),false);assert.equal(next([],now),null);});
test('materials review: stored sources only, safe URL preserved, missing and dangerous records rejected',t=>{const {store,service,e}=setup(t);for(const [id,url]of [['safe','https://example.com/page?q=1#section'],['script','javascript:alert(1)'],['file','file:///tmp/a'],['local','https://127.0.0.1/'],['credential','https://user:pass@example.com/']])store.put('briefings',{id,eventId:'e',eventRevision:e.revision,status:'ready',sources:[{id:'S1',url}]});assert.equal(service.sourceUrl({briefingId:'safe',sourceId:'S1',url:'https://evil.example/'}),'https://example.com/page?q=1#section');for(const briefingId of ['script','file','local','credential','missing'])assert.throws(()=>service.sourceUrl({briefingId,sourceId:'S1'}));assert.throws(()=>service.sourceUrl({briefingId:'safe',sourceId:'missing'}));store.put('briefings',{id:'notready',status:'failed',sources:[{id:'S1',url:'https://example.com'}]});assert.throws(()=>service.sourceUrl({briefingId:'notready',sourceId:'S1'}));});
test('materials review: offline export preserves source dates and own notes without jobs mutation or AI configuration',t=>{const {store,service,e}=setup(t);store.put('notes',{id:'n',eventId:'e',title:'My note',body:'Observed this personally\nSecond line'});store.put('notes',{id:'other-note',eventId:'another',body:'OTHER-EVENT-NOTE'});store.put('briefings',{id:'b',eventId:'e',eventRevision:e.revision,status:'ready',facts:[{sourceId:'S1',quote:'Evidence'}],hypotheses:['Needs verification'],questions:['Try product'],personalEvidence:[{group:'projects',index:0,field:'description',quote:'My project',relevance:'Possible connection'}],sources:[{id:'S1',url:'https://example.com',capturedAt:'2026-10-01T03:00:00Z'}]});const before=JSON.stringify(store.list('notes')),output=service.exportMarkdown('e');for(const value of ['Evidence','Needs verification','Try product','My project','2026-10-01T03:00:00Z','Observed this personally\nSecond line'])assert.ok(output.content.includes(value));assert.ok(!output.content.includes('OTHER-EVENT-NOTE'));assert.equal(store.list('aiJobs').length,0);assert.equal(JSON.stringify(store.list('notes')),before);assert.equal(output.briefingId,'b');});
test('materials review: notes-only export works and non-interview export rejects',t=>{const {store,service}=setup(t);store.put('notes',{id:'n',eventId:'e',body:'Notes before AI'});assert.match(service.exportMarkdown('e').content,/Notes before AI/);assert.equal(service.exportMarkdown('e').briefingId,'');store.put('events',{id:'assessment',type:'assessment'});assert.throws(()=>service.exportMarkdown('assessment'));assert.throws(()=>service.exportMarkdown('missing'));});
test('materials review: export warns for changed or unreadable local profile while retaining notes and material',t=>{const {store,e}=setup(t);store.put('notes',{id:'n',eventId:'e',body:'KEEP-NOTE'});store.put('briefings',{id:'b',eventId:'e',eventRevision:e.revision,status:'ready',profileHash:'old-hash',body:'KEEP-BRIEF'});for(const profileHash of [()=> 'new-hash',()=>{throw Error('damaged local profile')}]){const materials=createInterviewMaterials(store,{profileHash}),output=materials.exportMarkdown('e');assert.match(output.content,/资料已变化/);assert.match(output.content,/KEEP-NOTE/);assert.match(output.content,/KEEP-BRIEF/);assert.equal(store.list('aiJobs').length,0);}});
test('materials review: missing, cross-organization and mixed association records cannot label briefing ready',()=>{for(const mutate of [s=>{s.applications=[]},s=>{s.plans=[]},s=>{s.applications[0].organizationId='wrong'},s=>{s.plans[0].organizationId='wrong'},s=>{s.applications[0].planId='other'}]){const s=state(),e={...event(),organizationId:'org',applicationId:'a',planId:'p'};s.applications=[{id:'a',organizationId:'org',planId:'p',opportunityId:'o'}];s.plans=[{id:'p',organizationId:'org',opportunityId:'o'}];mutate(s);assert.equal(summary(e,s).stale,true);assert.equal(summary(e,s).status,'stale');}});
