'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const {openStore}=require('../src/services/store.cjs');
const {createWorkflow}=require('../src/services/workflow.cjs');
const {createLegacy}=require('../src/services/legacy.cjs');
function fixture(t){const root=fs.mkdtempSync(path.join(os.tmpdir(),'legacy-review-')),store=openStore(root),workflow=createWorkflow(store,{}),legacy=createLegacy(store,workflow),file=path.join(root,'old.json');t.after(()=>{store.close();fs.rmSync(root,{recursive:true,force:true});});return{root,store,workflow,legacy,file,write(rows){fs.writeFileSync(file,JSON.stringify(rows));return legacy.preview(file);}};}
const row=(id,extra={})=>({'记录ID':id,'公司名称':'测试单位','投递岗位':'开发','当前状态':'技术二面','官方节点时间':'下周三下午','简历附件':'/unavailable/private/resume.pdf','备注':'<img src=x onerror=alert(1)>',...extra});
function migrate(f,p,ids=p.rows.map(r=>r.id)){return f.legacy.migrate(f.file,{confirmed:true,hash:p.hash,ids});}
test('review: selected rows preserve full evidence and source bytes without inferring application/events',t=>{const f=fixture(t),original=row('one',{'未知扩展字段':'完整保留'}),p=f.write([original,row('two')]),bytes=fs.readFileSync(f.file);assert.deepEqual(migrate(f,p,[p.rows[0].id]),{imported:1,skipped:0});assert.deepEqual(fs.readFileSync(f.file),bytes);assert.deepEqual(f.legacy.record(p.rows[0].id).original,original);const note=f.store.list('notes')[0];for(const [k,v] of Object.entries(original))assert.ok(note.body.includes(`${k}：${v}`));for(const c of ['applications','events','tasks','reminders','assets','activities'])assert.equal(f.store.list(c).length,0,c);assert.equal(f.store.list('confirmations')[0].status,'pending');assert.equal(f.store.list('opportunities')[0].statusVerified,false);assert.equal(f.store.list('opportunities')[0].openStatus,'unknown');});
test('review: replay is idempotent, changed IDs cannot overwrite, edited file requires new preview',t=>{const f=fixture(t),p=f.write([row('one')]);migrate(f,p);const before=f.store.exportData().collections;assert.deepEqual(migrate(f,p),{imported:0,skipped:1});assert.deepEqual(f.store.exportData().collections,before);const changed=f.write([row('one',{'备注':'changed'})]);assert.equal(changed.rows[0].state,'changed');assert.throws(()=>migrate(f,p),/文件已变化/);assert.throws(()=>migrate(f,changed),/不覆盖/);assert.deepEqual(f.store.exportData().collections,before);});
test('review: missing confirmation, unknown selection, duplicates and invalid source rejected without writes',t=>{const f=fixture(t),p=f.write([row('one')]);assert.throws(()=>f.legacy.migrate(f.file,{hash:p.hash,ids:[p.rows[0].id]}),/确认/);assert.throws(()=>migrate(f,p,[]),/选择/);assert.throws(()=>migrate(f,p,['unknown']),/预览/);assert.throws(()=>migrate(f,p,[p.rows[0].id,p.rows[0].id]),/选择/);assert.throws(()=>f.write([row('one'),row('one')]),/重复/);assert.throws(()=>f.write([row('one',{'备注':{nested:true}})]),/不支持|受支持/);assert.equal(f.store.list('evidence').length,0);});
test('review: late failure rolls back all selected rows and existing organization remains unchanged',t=>{const f=fixture(t),org=f.workflow.organization({name:'测试单位',type:'government',website:'https://example.test/'}),p=f.write([row('one'),row('two')]);const faulty=createLegacy(f.store,{...f.workflow,collect(id,state){if(id.includes(p.rows[1].id))throw Error('injected failure');return f.workflow.collect(id,state);}});assert.throws(()=>faulty.migrate(f.file,{hash:p.hash,ids:p.rows.map(r=>r.id),confirmed:true}),/injected/);for(const c of ['opportunities','evidence','notes','confirmations','userOpportunities'])assert.equal(f.store.list(c).length,0,c);assert.deepEqual(f.store.get('organizations',org.id),org);migrate(f,p);assert.deepEqual(f.store.get('organizations',org.id),org);});
test('review: untrusted URL remains only in evidence and attachment paths are never opened',t=>{const f=fixture(t),p=f.write([row('one',{'投递链接':'javascript:alert(1)','简历附件':f.root})]);migrate(f,p);assert.equal(f.store.list('opportunities')[0].url,'');assert.equal(f.legacy.record(p.rows[0].id).original['投递链接'],'javascript:alert(1)');assert.equal(f.store.list('assets').length,0);const link=path.join(f.root,'linked.json');fs.symlinkSync(f.file,link);assert.throws(()=>f.legacy.preview(link),/旧版 JSON/);});
test('review: acknowledgment requires confirmation and observed version and preserves evidence',t=>{const f=fixture(t),p=f.write([row('one')]);migrate(f,p);const c=f.store.list('confirmations')[0],e=f.legacy.record(p.rows[0].id);assert.throws(()=>f.legacy.acknowledge({id:c.id,revision:c.revision}),/确认/);assert.throws(()=>f.legacy.acknowledge({id:c.id,revision:c.revision+1,confirmed:true}),/更新/);assert.equal(f.legacy.acknowledge({id:c.id,revision:c.revision,confirmed:true}).status,'reviewed');assert.deepEqual(f.legacy.record(p.rows[0].id),e);assert.equal(f.store.list('applications').length,0);});
test('review: no-ID exact replay deduplicates; changed no-ID content is explicitly a new record',t=>{const f=fixture(t),r=row('');const p=f.write([r]);migrate(f,p);assert.equal(f.legacy.preview(f.file).rows[0].state,'imported');const changed=f.write([{...r,'备注':'new'}]);assert.equal(changed.rows[0].state,'new');assert.notEqual(changed.rows[0].id,p.rows[0].id);});
test('review: actual IPC ticket survives validation failure, binds hash, and is consumed on success',t=>{
 const vm=require('node:vm'),f=fixture(t),p=f.write([row('one')]);
 const source=fs.readFileSync(path.join(__dirname,'../src/main.cjs'),'utf8');
 const start=source.indexOf("    if(request?.action==='legacy-import'){");
 const end=source.indexOf("    if (request?.action === 'backup-export')",start);
 assert.ok(start>=0&&end>start);
 const context={Date,request:{action:'legacy-import',data:{token:'ticket',ids:[],confirmed:true,hash:'renderer-cannot-replace'}},legacyTicket:{token:'ticket',filename:f.file,hash:p.hash,expires:Date.now()+300000},workbench:{legacy:f.legacy}};
 vm.createContext(context);const script=new vm.Script('(function(){'+source.slice(start,end)+'})()');
 assert.throws(()=>script.runInContext(context),/请选择记录/);
 assert.ok(context.legacyTicket);
 context.request.data.ids=[p.rows[0].id];
 assert.equal(script.runInContext(context).imported,1);
 assert.equal(context.legacyTicket,null);
 assert.throws(()=>script.runInContext(context),/重新选择/);
});
