const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os');
const {createWorkbench}=require('../src/services/workbench.cjs');
function fixture(t){const root=fs.mkdtempSync(path.join(os.tmpdir(),'legacy-test-'));fs.mkdirSync(path.join(root,'知识库'));fs.writeFileSync(path.join(root,'知识库/profile.json'),JSON.stringify({schemaVersion:1,demo:false,values:{basic:[{}]}}));const wb=createWorkbench(root);t.after(()=>{wb.close();fs.rmSync(root,{recursive:true,force:true});});const filename=path.join(root,'投递记录.json');return{wb,filename};}
test('migration preserves original status, ambiguous dates and private attachment paths without creating fictional applications',t=>{
 const{wb,filename}=fixture(t),rows=[{'记录ID':'old-1','公司名称':'测试公司','投递岗位':'软件开发','当前状态':'二面','官方节点时间':'下周三','简历附件':'/private/do-not-read.pdf','备注':'原始备注','投递链接':'https://example.com/apply?id=123'}];const raw=JSON.stringify(rows);fs.writeFileSync(filename,raw);const preview=wb.legacy.preview(filename),input={hash:preview.hash,ids:preview.rows.map(r=>r.id),confirmed:true};assert.deepEqual(wb.legacy.migrate(filename,input),{imported:1,skipped:0});assert.equal(fs.readFileSync(filename,'utf8'),raw);assert.deepEqual(wb.legacy.record(input.ids[0]).original,rows[0]);assert.equal(wb.store.list('applications').length,0);assert.equal(wb.store.list('events').length,0);assert.equal(wb.store.list('tasks').length,0);assert.equal(wb.store.list('opportunities')[0].openStatus,'unknown');assert.equal(wb.store.list('confirmations')[0].status,'pending');assert.deepEqual(wb.legacy.migrate(filename,input),{imported:0,skipped:1});
 const c=wb.store.list('confirmations')[0];wb.legacy.acknowledge({id:c.id,revision:c.revision,confirmed:true});assert.equal(wb.store.list('confirmations')[0].status,'reviewed');assert.deepEqual(wb.legacy.record(input.ids[0]).original,rows[0]);
});
test('changed file rejects confirmation; changed imported ID never overwrites reviewed data',t=>{
 const{wb,filename}=fixture(t),row={'记录ID':'1','公司名称':'示例','投递岗位':'开发'};fs.writeFileSync(filename,JSON.stringify([row]));const first=wb.legacy.preview(filename);fs.writeFileSync(filename,JSON.stringify([{...row,'备注':'modified'}]));assert.throws(()=>wb.legacy.migrate(filename,{hash:first.hash,ids:[first.rows[0].id],confirmed:true}),/变化/);assert.equal(wb.store.list('opportunities').length,0);
 const next=wb.legacy.preview(filename);wb.legacy.migrate(filename,{hash:next.hash,ids:[next.rows[0].id],confirmed:true});fs.writeFileSync(filename,JSON.stringify([{...row,'备注':'new modification'}]));const changed=wb.legacy.preview(filename);assert.equal(changed.rows[0].state,'changed');assert.throws(()=>wb.legacy.migrate(filename,{hash:changed.hash,ids:[changed.rows[0].id],confirmed:true}),/覆盖/);assert.equal(wb.store.list('opportunities').length,1);
});
