'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),{randomUUID}=require('node:crypto');
const {openStore}=require('../src/services/store.cjs'),{createMailAI,validateMailResult,dateValue}=require('../src/services/mail-ai.cjs');
const raw='无关私人开头\n公司面试通知\n申请编号：A-1\n岗位：研发\n2026年10月12日10时00分\n面试地点：北京办公室\n原文末尾';
const output=(key='location',value='北京办公室',quote='面试地点：北京办公室')=>({changes:[{key,value,quote}]});
function deferred(){let resolve,reject;const promise=new Promise((a,b)=>{resolve=a;reject=b});return{promise,resolve,reject};}
function fixture(t,invoke=async()=>output()){
 const root=fs.mkdtempSync(path.join(os.tmpdir(),'mail-ai-review-')),store=openStore(root),settingsValue={enabled:true,baseUrl:'https://provider.example.invalid/v1',model:'model',apiKey:'AI-SECRET'},settings={read:()=>({...settingsValue})},calls=[];
 const message=store.put('messages',{id:'m',subject:'标题',text:raw,from:'hidden@example.invalid',attachments:[{filename:'秘密附件.pdf'}],mailPassword:'MAIL-SECRET'}),confirmation=store.put('confirmations',{id:'c',kind:'mail_event',messageId:message.id,status:'pending',proposal:{organizationId:'org',title:'原草稿',confidence:'structured',structuredUpdate:true,action:'create',type:'interview'}});
 store.put('organizations',{id:'org',name:'公司'});store.put('organizations',{id:'other',name:'他司'});
 store.put('opportunities',{id:'o',organizationId:'org',title:'研发'});store.put('plans',{id:'p',organizationId:'org',opportunityId:'o',status:'completed'});store.put('applications',{id:'a',organizationId:'org',opportunityId:'o',planId:'p',status:'submitted',referenceNumber:'A-1'});
 const ai=createMailAI(store,settings,{invoke:async(config,request)=>{calls.push({config,request});return invoke(config,request);}});
 t.after(()=>{ai.close();store.close();fs.rmSync(root,{recursive:true,force:true});});
 const input=(extra={})=>({confirmationId:confirmation.id,revision:confirmation.revision,text:'面试地点：北京办公室',offset:'',confirmed:true,fingerprint:ai.config().fingerprint,requestId:randomUUID(),...extra});return{store,ai,calls,input,settings,settingsValue,confirmation};
}
test('only selected original text and field names reach model input; public config and persisted job omit secrets',async t=>{const x=fixture(t),input=x.input();const job=await x.ai.run(input);assert.equal(job.status,'ready');assert.deepEqual(Object.keys(x.calls[0].request.input).sort(),['fields','text']);assert.equal(x.calls[0].request.input.text,input.text);assert.equal(x.calls[0].request.maxTokens,4000);assert.equal(x.calls[0].request.images,undefined);for(const value of ['AI-SECRET','MAIL-SECRET','秘密附件','hidden@example','无关私人开头']){assert.equal(JSON.stringify(x.ai.config()).includes(value),false);assert.equal(JSON.stringify(x.store.list('aiJobs')).includes(value),false);assert.equal(JSON.stringify(x.calls[0].request).includes(value),false);}assert.equal(x.calls[0].config.apiKey,'AI-SECRET');});
test('consent, fragment bounds, exact original substring, offset and stale confirmation are checked before invocation',async t=>{const x=fixture(t);for(const patch of [{confirmed:false},{text:''},{text:'改写北京办公室'},{text:'a'.repeat(20001)},{offset:'+09:00'},{revision:999}])await assert.rejects(x.ai.run(x.input(patch)));assert.equal(x.calls.length,0);assert.equal(x.store.list('aiJobs').length,0);});
test('same request is idempotent while running and after readiness; changed scope rejected without extra charges',async t=>{const d=deferred(),x=fixture(t,()=>d.promise),input=x.input(),running=x.ai.run(input);assert.equal((await x.ai.run(input)).status,'running');await assert.rejects(x.ai.run({...input,text:'北京办公室'}),/其他请求/);assert.equal(x.calls.length,1);d.resolve(output());const ready=await running;assert.equal((await x.ai.run(input)).id,ready.id);assert.equal(x.calls.length,1);});
test('malformed keys, duplicate fields, invented quote/value, empty changes and oversized fields are rejected',()=>{for(const result of [{changes:[]},output('notAllowed'),output('location','虚构'),output('location','北京办公室','不存在原文'),{changes:[...output().changes,...output().changes]},output('location','x'.repeat(2001),'x'.repeat(2001)),output('type','done'),output('action','complete')])assert.throws(()=>validateMailResult(result,raw,''));});
test('date conversion requires full original calendar and user offset; Offer dates stay distinct',()=>{assert.equal(dateValue('2026年10月12日10时00分','+08:00'),'2026-10-12T02:00:00.000Z');for(const [value,offset]of [['2026年10月12日10时00分',''],['10月12日10时00分','+08:00'],['明天十点','+08:00'],['2026年2月30日10时00分','+08:00']])assert.equal(dateValue(value,offset),'');const source='发出2026-10-01T10:00:00Z 回复2026-10-05T10:00:00Z 入职2026-11-01T10:00:00Z',changes=validateMailResult({changes:[{key:'offerIssuedAt',value:'2026-10-01T10:00:00Z',quote:source},{key:'offerReplyDeadline',value:'2026-10-05T10:00:00Z',quote:source},{key:'joiningAt',value:'2026-11-01T10:00:00Z',quote:source}]},source,'');assert.equal(new Set(changes.map(c=>c.normalized)).size,3);assert.throws(()=>validateMailResult(output('offerReceivedAt','2026-10-01T10:00:00Z',source),source,''));});
test('invalid date, unsafe URL and unparsed round remain visible but cannot be adopted',()=>{for(const [key,value]of [['startsAt','明天'],['url','javascript:alert(1)'],['round','一']]){const [change]=validateMailResult(output(key,value,value),value,'');assert.equal(change.adoptable,false);assert.ok(change.warning);assert.equal(change.value,value);}});
test('cancellation prevents late provider response from becoming ready or mutating confirmation',async t=>{const d=deferred(),x=fixture(t,()=>d.promise),input=x.input(),run=x.ai.run(input);assert.equal(x.ai.cancel(input.requestId),true);assert.equal(x.calls[0].request.signal.aborted,true);d.resolve(output());await assert.rejects(run,/取消/);assert.equal(x.ai.list('c')[0].status,'cancelled');assert.deepEqual(x.store.get('confirmations','c'),x.confirmation);assert.equal(x.store.list('events').length,0);});
test('closed running task remains recoverable as interrupted on restart and is never retried',async t=>{const d=deferred(),x=fixture(t,()=>d.promise),input=x.input(),run=x.ai.run(input);x.ai.close();d.resolve(output());await assert.rejects(run,/取消/);assert.equal(x.ai.list('c')[0].status,'running');let calls=0;const restarted=createMailAI(x.store,x.settings,{invoke:async()=>{calls++;return output();}});assert.equal(restarted.list('c')[0].status,'interrupted');assert.match(restarted.list('c')[0].error,/可能已计费/);assert.equal((await restarted.run(input)).status,'interrupted');assert.equal(calls,0);restarted.close();});
test('changed or accepted confirmation invalidates provider result and ready draft adoption',async t=>{const d=deferred(),x=fixture(t,()=>d.promise),run=x.ai.run(x.input());x.store.put('confirmations',{...x.confirmation,status:'ignored'},{expectedRevision:x.confirmation.revision});d.resolve(output());await assert.rejects(run,/已处理/);assert.equal(x.ai.list('c')[0].status,'failed');assert.equal(x.store.get('confirmations','c').status,'ignored');});
test('adopt chosen fields updates only pending proposal with evidence and cannot repeat',async t=>{const x=fixture(t,async()=>({changes:[...output().changes,{key:'title',value:'公司面试通知',quote:'公司面试通知'}]})),job=await x.ai.run(x.input({text:raw})),beforeApps=x.store.list('applications'),saved=x.ai.adopt({jobId:job.id,ids:[job.changes[0].id],confirmed:true});assert.equal(saved.status,'pending');assert.equal(saved.proposal.location,'北京办公室');assert.equal(saved.proposal.title,'原草稿');assert.equal(saved.proposal.confidence,'needs_review');assert.equal(saved.proposal.structuredUpdate,false);assert.deepEqual(saved.proposalHistory[0].proposal,x.confirmation.proposal);assert.equal(saved.aiEvidence[0].quote,'面试地点：北京办公室');assert.equal(x.ai.list('c')[0].status,'adopted');assert.equal(x.store.list('events').length,0);assert.equal(x.store.list('tasks').length,0);assert.equal(x.store.list('activities').length,0);assert.deepEqual(x.store.list('applications'),beforeApps);assert.throws(()=>x.ai.adopt({jobId:job.id,ids:[job.changes[1].id],confirmed:true}));});
test('selection requires explicit consent, known unique adoptable IDs and current confirmation revision',async t=>{const x=fixture(t),j=await x.ai.run(x.input());for(const patch of [{confirmed:false},{ids:[]},{ids:['unknown']},{ids:[j.changes[0].id,j.changes[0].id]}])assert.throws(()=>x.ai.adopt({jobId:j.id,ids:[j.changes[0].id],confirmed:true,...patch}));x.store.put('confirmations',{...x.confirmation,proposal:{...x.confirmation.proposal,title:'手改'}},{expectedRevision:x.confirmation.revision});assert.throws(()=>x.ai.adopt({jobId:j.id,ids:[j.changes[0].id],confirmed:true}),/已变化/);assert.equal(x.ai.list('c')[0].status,'ready');});
test('adoption final job-write failure rolls back confirmation and audit draft together',async t=>{const x=fixture(t),j=await x.ai.run(x.input()),put=x.store.put;x.store.put=(collection,item,...args)=>{if(collection==='aiJobs'&&item.status==='adopted')throw Error('injected final write');return put(collection,item,...args);};assert.throws(()=>x.ai.adopt({jobId:j.id,ids:[j.changes[0].id],confirmed:true}),/injected/);x.store.put=put;assert.deepEqual(x.store.get('confirmations','c'),x.confirmation);assert.equal(x.ai.list('c')[0].status,'ready');});
test('adopted reference re-evaluates application and clears stale thread target without creating event',async t=>{const x=fixture(t,async()=>output('applicationReference','A-1','申请编号：A-1'));x.confirmation=x.store.put('confirmations',{...x.confirmation,proposal:{...x.confirmation.proposal,eventId:'old-event'}},{expectedRevision:x.confirmation.revision});const j=await x.ai.run(x.input({text:raw,revision:x.confirmation.revision})),c=x.ai.adopt({jobId:j.id,ids:[j.changes[0].id],confirmed:true});assert.equal(c.proposal.applicationId,'a');assert.equal(c.proposal.planId,'p');assert.equal(c.proposal.eventId,'');assert.equal(c.proposal.applicationMatch.status,'matched');assert.equal(x.store.list('events').length,0);});
test('organization mismatch stays conflicted and unlinked',async t=>{const x=fixture(t,async()=>({changes:[{key:'organizationName',value:'他司',quote:'他司'},{key:'applicationReference',value:'A-1',quote:'申请编号：A-1'}]}));const m=x.store.get('messages','m');x.store.put('messages',{...m,text:raw+'\n他司'},{expectedRevision:m.revision});const j=await x.ai.run(x.input({text:raw+'\n他司'})),c=x.ai.adopt({jobId:j.id,ids:j.changes.map(c=>c.id),confirmed:true});assert.equal(c.proposal.organizationId,'other');assert.equal(c.proposal.applicationMatch.status,'conflict');assert.equal(c.proposal.applicationId,'');assert.equal(c.proposal.planId,'');});
test('provider, model or API key changes after consent block invocation until new fingerprint is reviewed',async t=>{const x=fixture(t);for(const [key,value]of [['baseUrl','https://different.example.invalid/v1'],['model','other-model'],['apiKey','NEW-SECRET']]){const input=x.input();x.settingsValue[key]=value;await assert.rejects(x.ai.run(input),/配置已变化/);}assert.equal(x.calls.length,0);assert.equal(x.store.list('aiJobs').length,0);assert.equal((await x.ai.run(x.input())).status,'ready');});
test('unknown organization selection rolls back other selected fields and leaves job ready',async t=>{const x=fixture(t,async()=>({changes:[...output().changes,{key:'organizationName',value:'原文末尾',quote:'原文末尾'}]})),j=await x.ai.run(x.input({text:raw}));assert.throws(()=>x.ai.adopt({jobId:j.id,ids:j.changes.map(c=>c.id),confirmed:true}),/未唯一匹配/);assert.deepEqual(x.store.get('confirmations','c'),x.confirmation);assert.equal(x.ai.list('c')[0].status,'ready');});
test('invented model result produces failed job but no proposal or event modification',async t=>{const x=fixture(t,async()=>output('location','编造地点'));await assert.rejects(x.ai.run(x.input()),/改写/);assert.equal(x.ai.list('c')[0].status,'failed');assert.deepEqual(x.store.get('confirmations','c'),x.confirmation);assert.equal(x.store.list('events').length,0);});
test('manual adoption of type or action always invalidates previous thread event target',async t=>{const x=fixture(t,async()=>output('action','reschedule','公司面试通知'));x.confirmation=x.store.put('confirmations',{...x.confirmation,proposal:{...x.confirmation.proposal,eventId:'old-event'}},{expectedRevision:x.confirmation.revision});const j=await x.ai.run(x.input({text:raw,revision:x.confirmation.revision})),c=x.ai.adopt({jobId:j.id,ids:[j.changes[0].id],confirmed:true});assert.equal(c.proposal.action,'reschedule');assert.equal(c.proposal.eventId,'');assert.match(c.proposal.linkReason,/重新核对/);assert.equal(c.status,'pending');assert.equal(x.store.list('events').length,0);});
