'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const {openStore}=require('../src/services/store.cjs'),{createWorkflow}=require('../src/services/workflow.cjs'),{createMail}=require('../src/services/mail.cjs'),{proposeMail}=require('../src/services/mail-rules.cjs');
function fixture(t){const root=fs.mkdtempSync(path.join(os.tmpdir(),'mail-update-independent-')),store=openStore(root),workflow=createWorkflow(store,{read:()=>({profile:{values:{basic:[{}]}}})},{clock:()=> '2026-10-20T00:00:00.000Z'}),secrets=new Map(),mail=createMail(store,workflow,{vault:{get:id=>secrets.get(id),set:(id,v)=>secrets.set(id,v),remove:id=>secrets.delete(id)}});workflow.organization({name:'公司'});const config={address:'a@example.invalid',host:'imap.example.invalid',password:'synthetic',keywords:['面试'],consent:true,enabled:true,autoCreate:true,autoUpdate:true,senderAddresses:['hr@example.invalid']},connection=mail.configure(config);t.after(()=>{mail.close();store.close();fs.rmSync(root,{recursive:true,force:true});});const ingest=(id,day,subject='公司面试改期',body='面试时间：2026-10-12T10:00:00Z',extra={})=>{const sent=extra.sent||`2026-10-${String(day).padStart(2,'0')}T08:00:00Z`,ref=extra.ref===undefined?'root':extra.ref;const raw=Buffer.from(`From: ${extra.from||'hr@example.invalid'}\r\nSubject: ${subject}\r\nDate: ${new Date(sent).toUTCString()}\r\nMessage-ID: <${id}@example.invalid>\r\n${ref?`In-Reply-To: <${ref}@example.invalid>\r\n`:''}Content-Type: text/plain; charset=utf-8\r\n\r\n${body}`);return mail.ingest(raw,{connectionId:extra.connectionId||connection.id,address:'a@example.invalid',receivedAt:extra.received||`2026-10-${String(day).padStart(2,'0')}T09:00:00Z`});};return {store,workflow,mail,config,connection,ingest,seed:()=>ingest('root',1,'公司面试通知','面试时间：2026-10-10T10:00:00Z',{ref:''}),event:()=>store.list('events')[0],pending:()=>store.list('confirmations').filter(c=>c.status==='pending')};}
test('opted-in unique thread reschedules pending event, retains audit evidence and never completes it',async t=>{const x=fixture(t);await x.seed();const before=x.event();await x.ingest('move',2);const after=x.event();assert.equal(x.store.list('events').length,1);assert.equal(after.id,before.id);assert.equal(after.startsAt,'2026-10-12T10:00:00.000Z');assert.equal(after.status,'scheduled');assert.equal(x.store.get('tasks','task-event-'+after.id).status,'pending');assert.equal(after.history.at(-1).source,'mail_user_configured_rule');assert.ok(after.history.at(-1).evidenceId);assert.equal(after.messageIds.length,2);assert.equal(x.store.list('activities').length,0);});
test('explicit cancellation cancels reminder and task, never records completion activity',async t=>{const x=fixture(t);await x.seed();const e=x.event();x.store.put('reminders',{id:'old-pending-reminder',taskId:'task-event-'+e.id,status:'pending'});await x.ingest('cancel',2,'公司面试已取消','本次通知确认取消。');assert.equal(x.event().status,'cancelled');assert.equal(x.store.get('tasks','task-event-'+e.id).status,'cancelled');assert.equal(x.store.get('reminders','old-pending-reminder').status,'cancelled');assert.equal(x.store.list('activities').length,0);});
test('autoUpdate opt-out leaves follow-up pending without creating duplicate event',async t=>{const x=fixture(t);await x.seed();x.mail.configure({...x.config,autoUpdate:false});const before=x.event();await x.ingest('manual',2);assert.deepEqual(x.event(),before);assert.equal(x.pending().length,1);assert.equal(x.store.list('events').length,1);});
test('sender, connection and ambiguous thread identities prevent automatic target selection',async t=>{const x=fixture(t);await x.seed();const before=x.event();await x.ingest('sender',2,undefined,undefined,{from:'other@example.invalid'});const second=x.mail.configure({...x.config,address:'b@example.invalid'});await x.ingest('mailbox',3,undefined,undefined,{connectionId:second.id});x.store.put('events',{...before,id:'another-thread-event'});await x.ingest('ambiguous',4);assert.deepEqual(x.store.get('events',before.id),before);assert.equal(x.pending().length,3);});
test('strict sent and server receipt ordering prevents stale or tied updates',async t=>{const x=fixture(t);await x.seed();const before=x.event();await x.ingest('same-sent',2,undefined,undefined,{sent:'2026-10-01T08:00:00Z'});await x.ingest('same-received',3,undefined,undefined,{received:'2026-10-01T09:00:00Z'});await x.ingest('older-sent',4,undefined,undefined,{sent:'2026-09-30T08:00:00Z'});assert.deepEqual(x.event(),before);assert.equal(x.pending().length,3);});
test('known end time forces review instead of moving start alone',async t=>{const x=fixture(t);await x.seed();const e=x.event();x.store.put('events',{...e,endsAt:'2026-10-10T11:00:00Z'},{expectedRevision:e.revision});const before=x.event();await x.ingest('with-end',2);assert.deepEqual(x.event(),before);assert.equal(x.pending().length,1);});
test('manual event modification prevents automatic update',async t=>{const x=fixture(t);await x.seed();let e=x.event();e=x.workflow.event({...e,location:'手改会议室'});await x.ingest('edited',2);assert.equal(x.event().location,'手改会议室');assert.equal(x.event().startsAt,e.startsAt);assert.equal(x.pending().length,1);});
test('manually cancelled then restored rule event remains protected from later automatic mail',async t=>{const x=fixture(t);await x.seed();let task=x.store.get('tasks','task-event-'+x.event().id);x.workflow.taskStatus({id:task.id,revision:task.revision,status:'cancelled'});task=x.store.get('tasks',task.id);x.workflow.taskStatus({id:task.id,revision:task.revision,status:'pending'});const before=x.event();await x.ingest('after-user-restore',2);assert.deepEqual(x.event(),before);assert.equal(x.pending().length,1);});
test('revoked cancellation and cancellation with date-only target are never structured automatic changes',()=>{for(const subject of ['公司面试取消通知撤回','公司面试取消通知作废','公司面试取消通知（2026-10-06场次）']){const p=proposeMail({subject,text:'请核对通知',attachments:[]},[{id:'org',name:'公司'}]);assert.equal(p.structuredUpdate,false,subject);}});
test('update failure rolls back message, confirmation and event modifications together',async t=>{const x=fixture(t);await x.seed();const before=x.event(),put=x.store.put;x.store.put=function(collection,item,...args){if(collection==='confirmations'&&item.method==='user_configured_update')throw Error('injected');return put(collection,item,...args)};await assert.rejects(x.ingest('rollback',2),/injected/);x.store.put=put;assert.deepEqual(x.event(),before);assert.equal(x.store.list('messages').length,1);assert.equal(x.store.list('confirmations').length,1);});
test('completed and user-reopened task are never auto-completed or rescheduled',async t=>{const x=fixture(t);await x.seed();let task=x.store.get('tasks','task-event-'+x.event().id);x.workflow.completeTask({id:task.id,revision:task.revision,completedAt:'2026-10-10T10:30:00Z',result:'面试完成'});const before=x.event();await x.ingest('after-done',2);assert.deepEqual(x.event(),before);task=x.store.get('tasks',task.id);x.workflow.taskStatus({id:task.id,revision:task.revision,status:'pending'});const reopened=x.event();await x.ingest('after-reopen',3);assert.deepEqual(x.event(),reopened);assert.equal(x.pending().length,2);assert.equal(x.store.list('activities').filter(a=>!a.revoked).length,0);});
test('extra date-only, invalid ISO and natural language time keep reschedule pending',()=>{for(const text of ['面试时间：2026-10-12T10:00:00Z；另一个时间2026-10-14','面试时间：2026-10-12T10:00:00Z；面试时间：2026-99-01T10:00:00Z','面试时间：2026-10-12T10:00:00Z；明天再通知']){const p=proposeMail({subject:'公司面试改期',text,attachments:[]},[{id:'org',name:'公司'}]);assert.equal(p.structuredUpdate,false,text);}});
test('final-round mention cannot silently change an earlier first-round event',async t=>{const x=fixture(t);await x.ingest('root',1,'公司面试（一面）通知','面试时间：2026-10-10T10:00:00Z',{ref:''});assert.equal(x.event().round,1);const before=x.event();await x.ingest('final-conflict',2,'公司面试（终面）改期通知');assert.deepEqual(x.event(),before);assert.equal(x.pending().length,1);});
test('Chinese eleven is not first round and final-only wording does not invent numeric round',()=>{const propose=subject=>proposeMail({subject,text:'面试时间：2026-10-12T10:00:00Z',attachments:[]},[{id:'org',name:'公司'}]);assert.equal(propose('公司第十一轮面试改期').round,11);assert.equal(propose('公司最后一轮面试改期').final,true);assert.equal(propose('公司最后一轮面试改期').round,null);assert.equal(propose('公司第二十一轮面试改期').structuredUpdate,false);assert.equal(propose('公司复试面试改期').structuredUpdate,false);});
test('extra unparsed date prevents automatic creation as well as updates',()=>{const p=proposeMail({subject:'公司面试通知',text:'面试时间：2026-10-12T10:00:00Z；另一个安排2026-10-14',attachments:[]},[{id:'org',name:'公司'}]);assert.equal(p.confidence,'needs_review');assert.equal(p.structuredUpdate,false);});
