'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const {createWorkbench}=require('../src/services/workbench.cjs');
const {createSecretVault}=require('../src/services/secret-vault.cjs');
const {proposeMail}=require('../src/services/mail-rules.cjs');
function setup(t,factory){const root=fs.mkdtempSync(path.join(os.tmpdir(),'mail-review-'));fs.mkdirSync(path.join(root,'知识库'));fs.writeFileSync(path.join(root,'知识库/profile.json'),JSON.stringify({schemaVersion:1,demo:false,values:{basic:[{}]}}));const secrets=new Map();const wb=createWorkbench(root,{vault:{get:id=>secrets.get(id),set:(id,value)=>secrets.set(id,value),remove:id=>secrets.delete(id)},mailClientFactory:factory});t.after(()=>{wb.close();fs.rmSync(root,{recursive:true,force:true});});return {wb,root,secrets};}
function configure(wb){return wb.mail.configure({address:'a@example.invalid',host:'imap.example.invalid',keywords:['Offer'],consent:true,enabled:true,password:'SECRET-ONLY'});}
const eml=(id,extra='')=>Buffer.from(`From: hr@example.invalid\r\nMessage-ID: <${id}@example.invalid>\r\nSubject: Offer\r\n${extra}Content-Type: text/plain; charset=utf-8\r\n\r\nBody`);
function client(search,fetchOne){return {on(){},mailbox:{uidValidity:2n},async connect(){},async getMailboxLock(){return {release(){}}},search,fetchOne,close(){}};}
test('50-item pagination resumes and same validity replay creates no duplicates',async t=>{let wb,queries=[];({wb}=setup(t,()=>client(async q=>{queries.push(q.uid);return Array.from({length:55},(_,i)=>i+1)},async(uid,q)=>q.source?{source:eml(uid)}:{envelope:{subject:'Offer'},size:100})));const c=configure(wb);assert.equal((await wb.mail.sync(c.id)).hasMore,true);assert.equal(wb.store.list('messages').length,50);assert.equal((await wb.mail.sync(c.id)).imported,5);assert.equal((await wb.mail.sync(c.id)).imported,0);assert.deepEqual(queries,['1:*','51:*','56:*']);});
test('empty UIDVALIDITY rollover resets cursor before subsequent new UIDs',async t=>{let count=0,queries=[];const {wb}=setup(t,()=>client(async q=>{queries.push(q.uid);return ++count===1?[]:[1]},async(uid,q)=>q.source?{source:eml(uid)}:{envelope:{subject:'Offer'},size:100}));const c=configure(wb);wb.store.put('connections',{...c,uidValidity:'1',cursor:100},{expectedRevision:c.revision});await wb.mail.sync(c.id);await wb.mail.sync(c.id);assert.deepEqual(queries,['1:*','1:*']);assert.equal(wb.store.list('messages').length,1);});
test('stop during pending fetch rejects concurrent sync and prevents all subsequent writes',async t=>{let release,started;const pending=new Promise(r=>release=r),waiting=new Promise(r=>started=r);const {wb,secrets}=setup(t,()=>client(async()=>[1],async()=>{started();await pending;return {envelope:{subject:'Offer'},size:1}}));const c=configure(wb),run=wb.mail.sync(c.id);await waiting;await assert.rejects(wb.mail.sync(c.id),/正在同步/);wb.mail.disconnect(c.id);release();await assert.rejects(run,/未完成/);assert.equal(wb.store.list('messages').length,0);assert.equal(wb.store.get('connections',c.id).cursor,0);assert.equal(wb.store.get('connections',c.id).status,'disconnected');assert.equal(secrets.has(c.id),false);});
test('distinct original without Message-ID retains changed attachment',async t=>{const {wb}=setup(t);function source(content){return Buffer.from(`From: hr@example.invalid\r\nSubject: Offer\r\nMIME-Version: 1.0\r\nContent-Type: multipart/mixed; boundary=x\r\n\r\n--x\r\nContent-Type: text/plain\r\n\r\nBody\r\n--x\r\nContent-Type: text/plain\r\nContent-Disposition: attachment; filename=offer.txt\r\n\r\n${content}\r\n--x--`)}await wb.mail.ingest(source('first deadline'));const second=await wb.mail.ingest(source('changed deadline'));assert.equal(second.duplicate,false);assert.equal(wb.store.list('messages').length,2);});
test('unrelated deadline phrase never promotes Offer issue timestamp',()=>{const proposal=proposeMail({subject:'公司Offer',text:'发出时间 2026-10-03T08:00:00+08:00。回复截止时间将在附件中另行通知。',attachments:[]},[{id:'org',name:'公司'}]);assert.equal(proposal.deadline,'');assert.equal(proposal.confidence,'needs_review');});
test('confirmation transaction rolls back event and task on evidence write failure',async t=>{const {wb}=setup(t);const org=wb.workflow.organization({name:'公司'});await wb.mail.ingest(eml('rollback'));const c=wb.store.list('confirmations')[0],original=wb.store.put;wb.store.put=function(collection,item,...args){if(collection==='events'&&item.source==='mail_user_confirmed')throw Error('injected');return original(collection,item,...args)};assert.throws(()=>wb.mail.confirm({id:c.id,revision:c.revision,action:'create',event:{organizationId:org.id,title:'Offer',type:'offer'}}),/injected/);wb.store.put=original;assert.equal(wb.store.list('events').length,0);assert.equal(wb.store.list('tasks').length,0);assert.equal(wb.store.get('confirmations',c.id).status,'pending');});
test('raw eml survives backup restore and connection secrets are excluded',async t=>{const {wb,root}=setup(t);configure(wb);const first=await wb.mail.ingest(eml('backup'));const backup=path.join(root,'mail.qzb');wb.backup.exportFile(backup);const preview=wb.backup.preview(backup);const restored=wb.backup.restore(backup,root,preview.sha256);assert.deepEqual(fs.readFileSync(path.join(restored.workspace,'.workbench/messages',first.message.rawHash+'.eml')),eml('backup'));const data=JSON.parse(require('node:zlib').gunzipSync(fs.readFileSync(backup)));assert.equal(JSON.stringify(data).includes('SECRET-ONLY'),false);assert.equal(data.database.collections.connections[0].status,'disconnected');assert.equal(data.database.collections.connections[0].enabled,undefined);});
test('vault rejects plaintext backend and encrypted file does not contain secret',t=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'vault-review-'));t.after(()=>fs.rmSync(root,{recursive:true,force:true}));const storage={isEncryptionAvailable:()=>true,getSelectedStorageBackend:()=> 'basic_text',encryptString:s=>Buffer.from(s).reverse(),decryptString:b=>Buffer.from(b).reverse().toString()};const vault=createSecretVault(root,storage);assert.throws(()=>vault.set('test','SECRET-ONLY'),/钥匙串/);storage.getSelectedStorageBackend=()=> 'keychain';vault.set('test','SECRET-ONLY');assert.equal(fs.readFileSync(path.join(root,'connection-secrets.json'),'utf8').includes('SECRET-ONLY'),false);assert.equal(vault.get('test'),'SECRET-ONLY');vault.remove('test');assert.equal(vault.get('test'),'');});
test('oversize messages create review notices without downloading body',async t=>{let bodies=0;const {wb}=setup(t,()=>client(async()=>[1],async(uid,q)=>{if(q.source){bodies++;throw Error('oversize body downloaded')}return {envelope:{subject:'Offer'},size:2*1024*1024+1}}));const c=configure(wb);const result=await wb.mail.sync(c.id);assert.equal(result.skipped,1);assert.equal(bodies,0);assert.equal(wb.store.list('confirmations')[0].kind,'mail_oversize');assert.equal(wb.store.get('connections',c.id).cursor,1);});
test('reschedule partial payload retains original location, URL and end time',async t=>{const {wb}=setup(t),org=wb.workflow.organization({name:'公司'});const event=wb.workflow.event({organizationId:org.id,title:'面试',startsAt:'2026-10-03T08:00:00Z',endsAt:'2026-10-03T09:00:00Z',location:'room 1',url:'https://example.invalid/meeting'});await wb.mail.ingest(eml('reschedule'));const c=wb.store.list('confirmations')[0];wb.mail.confirm({id:c.id,revision:c.revision,action:'reschedule',eventId:event.id,eventRevision:event.revision,event:{organizationId:org.id,title:'面试改期',type:'interview',startsAt:'2026-10-03T08:30:00Z',deadline:'',round:'',timezone:'Asia/Shanghai'}});const updated=wb.store.get('events',event.id);assert.equal(updated.location,'room 1');assert.equal(updated.url,'https://example.invalid/meeting');assert.equal(updated.endsAt,'2026-10-03T09:00:00.000Z');assert.equal(updated.messageIds.length,1);});
test('explicit interview start and response deadline remain separate',()=>{const p=proposeMail({subject:'公司面试通知',text:'面试时间：2026-10-05T10:00:00+08:00。回复截止：2026-10-04T08:00:00+08:00',attachments:[]},[{id:'org',name:'公司'}]);assert.equal(p.startsAt,'2026-10-05T02:00:00.000Z');assert.equal(p.deadline,'2026-10-04T00:00:00.000Z');});
function ruleConnection(wb,extra={}){return wb.mail.configure({address:'a@example.invalid',host:'imap.example.invalid',keywords:['面试'],consent:true,enabled:true,password:'SECRET-ONLY',autoCreate:true,senderAddresses:['hr@example.invalid'],...extra});}
function ruleSource(id,subject='公司面试通知',body='面试时间：2026-10-05T10:00:00+08:00',from='hr@example.invalid'){return Buffer.from(`From: ${from}\r\nSubject: ${subject}\r\nMessage-ID: <${id}@example.invalid>\r\nContent-Type: text/plain; charset=utf-8\r\n\r\n${body}`)}
test('auto-create requires opt-in, exact sender and creates one pending task idempotently',async t=>{const {wb}=setup(t);wb.workflow.organization({name:'公司'});assert.throws(()=>ruleConnection(wb,{senderAddresses:[]}),/发件/);const c=ruleConnection(wb);const metadata={connectionId:c.id,address:c.address};const source=ruleSource('auto');await wb.mail.ingest(source,metadata);await wb.mail.ingest(source,metadata);assert.equal(wb.store.list('events').length,1);assert.equal(wb.store.list('tasks')[0].status,'pending');assert.equal(wb.store.list('activities').length,0);assert.equal(wb.store.list('confirmations')[0].method,'user_configured_rule');assert.equal(wb.store.list('events')[0].source,'mail_user_configured_rule');});
test('auto-create excludes imported mail, unlisted/multiple senders and default-disabled config',async t=>{const {wb}=setup(t);wb.workflow.organization({name:'公司'});const c=ruleConnection(wb);await wb.mail.ingest(ruleSource('import'));await wb.mail.ingest(ruleSource('unlisted',undefined,undefined,'other@example.invalid'),{connectionId:c.id,address:c.address});await wb.mail.ingest(ruleSource('multi',undefined,undefined,'hr@example.invalid, other@example.invalid'),{connectionId:c.id,address:c.address});ruleConnection(wb,{autoCreate:false});await wb.mail.ingest(ruleSource('disabled'),{connectionId:c.id,address:c.address});assert.equal(wb.store.list('events').length,0);assert.equal(wb.store.list('confirmations').every(c=>c.status==='pending'),true);});
test('auto-create transaction rolls back mail, confirmation, event and task together',async t=>{const {wb}=setup(t);wb.workflow.organization({name:'公司'});const c=ruleConnection(wb),original=wb.store.put;wb.store.put=function(collection,item,...args){if(collection==='events'&&item.source==='mail_user_configured_rule')throw Error('injected');return original(collection,item,...args)};await assert.rejects(wb.mail.ingest(ruleSource('failure'),{connectionId:c.id,address:c.address}),/injected/);wb.store.put=original;for(const name of ['events','tasks','messages','confirmations'])assert.equal(wb.store.list(name).length,0);});
test('body cancellation cannot trigger auto-create',async t=>{const {wb}=setup(t);wb.workflow.organization({name:'公司'});const c=ruleConnection(wb);await wb.mail.ingest(ruleSource('body-cancel','公司面试通知','本次面试已取消。原面试时间：2026-10-05T10:00:00+08:00'),{connectionId:c.id,address:c.address});assert.equal(wb.store.list('events').length,0);assert.equal(wb.store.list('confirmations')[0].status,'pending');});
test('auto-create leaves reschedule, historical, uncertain and attachment mail pending',async t=>{const {wb}=setup(t);wb.workflow.organization({name:'公司'});const c=ruleConnection(wb),metadata={connectionId:c.id,address:c.address};const bodies=['面试改期。面试时间：2026-10-05T10:00:00+08:00','之前面试时间：2026-10-05T10:00:00+08:00','不是面试时间：2026-10-05T10:00:00+08:00','面试时间：明天下午三点'];for(let i=0;i<bodies.length;i++)await wb.mail.ingest(ruleSource('review-'+i,'公司面试通知',bodies[i]),metadata);const attached=Buffer.from('From: hr@example.invalid\r\nSubject: 公司面试通知\r\nMessage-ID: <attach@example.invalid>\r\nMIME-Version: 1.0\r\nContent-Type: multipart/mixed; boundary=x\r\n\r\n--x\r\nContent-Type: text/plain; charset=utf-8\r\n\r\n面试时间：2026-10-05T10:00:00+08:00\r\n--x\r\nContent-Type: text/plain\r\nContent-Disposition: attachment; filename=offer.txt\r\n\r\nattachment\r\n--x--');await wb.mail.ingest(attached,metadata);assert.equal(wb.store.list('events').length,0);assert.equal(wb.store.list('confirmations').every(c=>c.status==='pending'),true);});
test('enabling auto-create does not retroactively create from existing pending message',async t=>{const {wb}=setup(t);wb.workflow.organization({name:'公司'});const c=ruleConnection(wb,{autoCreate:false}),metadata={connectionId:c.id,address:c.address},source=ruleSource('before-opt-in');await wb.mail.ingest(source,metadata);ruleConnection(wb);const replay=await wb.mail.ingest(source,metadata);assert.equal(replay.duplicate,true);assert.equal(wb.store.list('events').length,0);assert.equal(wb.store.list('confirmations')[0].status,'pending');});
