const test=require('node:test');
const assert=require('node:assert/strict');
const {createOnboarding,STEPS}=require('../src/services/onboarding.cjs');
function fixture(){
 const db=new Map(),profile={hash:'confirmed-v1',profile:{demo:false,values:{basic:[{}]}}};
 const store={get:(type,id)=>structuredClone(db.get(type+':'+id)),list:type=>[...db].filter(([k])=>k.startsWith(type+':')).map(([,v])=>structuredClone(v)),put(type,value,{expectedRevision}={}){const key=type+':'+value.id,old=db.get(key);if(expectedRevision!==undefined&&expectedRevision!==(old?.revision||0))throw Error('revision conflict');const next={...structuredClone(value),revision:(old?.revision||0)+1};db.set(key,next);return structuredClone(next);}};
 const facts={read:()=>structuredClone(profile)},assets={file:id=>{if(id==='missing')throw Error('file missing');return '/readable/original';}};
 const make=()=>createOnboarding(store,facts,assets,{clock:()=> '2026-10-04T00:00:00.000Z'});let svc=make();
 const act=(kind,extra={})=>svc.act({revision:svc.status().revision,step:svc.status().current,kind,confirmed:true,...extra});
 return{store,profile,make,get svc(){return svc},act,reopen(){svc=make();}};
}
test('review: six explicit skips persist and resume chooses first skipped step',()=>{const f=fixture();assert.equal(f.svc.status().suggested,true);f.act('begin');f.act('skip');f.act('defer');f.reopen();assert.equal(f.svc.status().current,'profile');assert.equal(f.svc.status().status,'deferred');f.act('begin');for(let i=1;i<STEPS.length;i++)f.act('skip');assert.equal(f.svc.status().status,'completed');for(const step of STEPS)assert.equal(f.svc.status().steps[step].status,'skipped');f.act('begin');assert.equal(f.svc.status().current,'import');});
test('review: explicit confirmation and current revision required without partial advancement',()=>{const f=fixture();f.act('begin');assert.throws(()=>f.act('skip',{confirmed:false}),/明确/);assert.throws(()=>f.act('skip',{revision:0}),/进度/);assert.equal(f.svc.status().current,'import');});
test('review: parser failure with readable original allows manual continuation and unknown profile remains blank',()=>{const f=fixture();f.store.put('assets',{id:'original',parseStatus:'failed',extension:'.docx'});f.act('begin');f.act('next');assert.equal(f.svc.status().current,'profile');assert.throws(()=>f.act('next',{profileHash:'stale'}),/资料已变化/);f.act('next',{profileHash:f.profile.hash});assert.equal(f.svc.status().steps.profile.unknownAllowed,true);assert.deepEqual(f.profile.profile.values.basic,[{}]);f.act('skip');assert.throws(()=>f.act('next'),/预览并保存/);const prefs=f.store.put('preferences',{id:'main',plans:[]});f.act('next',{preferencesRevision:prefs.revision});f.act('skip');f.act('skip');assert.equal(f.svc.status().status,'completed');});
test('review: missing original and unavailable default PDF do not fake success',()=>{const f=fixture();f.store.put('assets',{id:'missing',default:true,extension:'.pdf'});f.act('begin');assert.throws(()=>f.act('next'),/可读取/);f.act('skip');f.act('skip');assert.throws(()=>f.act('next'),/file missing/);assert.equal(f.svc.status().current,'pdf');f.act('skip');assert.equal(f.svc.status().current,'preferences');});
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
function uiHarness(extra={}){
 const source=fs.readFileSync(path.join(__dirname,'../src/ui/workbench.js'),'utf8');
 const fn=source.slice(source.indexOf('  async function onboardingAction('),source.indexOf('  function taskDay('));
 const calls=[],ctx={state:{onboarding:{status:'active',current:'preferences',revision:4},preferences:{revision:7},profile:{hash:'shown-version'}},route:'onboarding',profileDraft:null,preferenceDraft:null,$:id=>id==='wb-preferences-form'&&ctx.route==='preferences'?{}:null,api:async(action,data)=>{calls.push({action,data});return{preferences:{revision:8},profile:{hash:'new-unseen-version'}}},refresh:async()=>{},show:async(route)=>{calls.push({show:route});ctx.route=route;},preferencePreview:async()=>{calls.push({preview:true})},...extra};vm.createContext(ctx);vm.runInContext(fn,ctx);return{ctx,calls};
}
test('review: leaving unsaved preferences routes back to real preview instead of confirming saved old version',async()=>{const {ctx,calls}=uiHarness({preferenceDraft:{plans:[{name:'unsaved'}]}});await ctx.onboardingAction('next');assert.ok(calls.some(c=>c.show==='preferences'));assert.ok(calls.some(c=>c.preview));assert.equal(calls.some(c=>c.action==='onboarding-action'),false);});
test('review: profile confirmation submits displayed version, never an unseen fresh snapshot',async()=>{const {ctx,calls}=uiHarness();ctx.state.onboarding.current='profile';await ctx.onboardingAction('next');const action=calls.find(c=>c.action==='onboarding-action');assert.equal(action.data.profileHash,'shown-version');});
test('review: repeated defer is accepted after reopening and preserves current step and evidence',()=>{const f=fixture();f.act('begin');f.act('skip');f.act('defer');const before=f.svc.status();f.reopen();f.act('defer');const after=f.svc.status();assert.equal(after.status,'deferred');assert.equal(after.current,'profile');assert.deepEqual(after.steps,before.steps);assert.ok(after.revision>before.revision);f.act('begin');assert.equal(f.svc.status().status,'active');assert.equal(f.svc.status().current,'profile');});
