'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const {openStore}=require('../src/services/store.cjs'),{createOnboarding}=require('../src/services/onboarding.cjs');
function setup(t){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'onboarding-')),store=openStore(dir);let profile={hash:'profile-1',profile:{demo:false,values:{basic:[{name:''}]}}};const facts={read:()=>profile},assets={file:id=>{if(id==='broken')throw Error('file missing');return '/fixture/'+id;}};let flow=createOnboarding(store,facts,assets);t.after(()=>{store.close();fs.rmSync(dir,{recursive:true,force:true});});return{store,get flow(){return flow;},act(kind,more={}){const o=flow.status();return flow.act({kind,revision:o.revision,step:o.current,confirmed:true,profileHash:profile.hash,preferencesRevision:store.get('preferences','main')?.revision,...more});},restart(){flow=createOnboarding(store,facts,assets);},profile:p=>profile=p};}
test('fresh workspace suggests first use; explicit begin, defer and restart preserve exact step without external services',t=>{const x=setup(t);assert.equal(x.flow.status().suggested,true);x.act('begin');assert.equal(x.flow.status().current,'import');x.act('skip');assert.equal(x.flow.status().current,'profile');x.act('defer');x.restart();assert.equal(x.flow.status().status,'deferred');assert.equal(x.flow.status().current,'profile');x.act('begin');assert.equal(x.flow.status().steps.import.status,'skipped');assert.equal(x.store.list('aiJobs').length,0);assert.equal(x.store.list('connections').length,0);});
test('progress rejects stale revisions, wrong steps and implicit skip; original parser failure still permits manual path',t=>{const x=setup(t);x.act('begin');assert.throws(()=>x.flow.act({kind:'skip',step:'import',revision:0,confirmed:true}),/进度/);assert.throws(()=>x.act('skip',{step:'profile'}),/步骤/);assert.throws(()=>x.act('skip',{confirmed:false}),/明确/);assert.throws(()=>x.act('next'),/原件/);x.store.put('assets',{id:'broken',archived:false,parseStatus:'failed'});assert.throws(()=>x.act('next'),/可读取/);x.store.put('assets',{id:'saved',archived:false,parseStatus:'failed'});x.act('next');assert.equal(x.flow.status().current,'profile');assert.deepEqual(x.flow.status().steps.import.assetIds,['saved']);assert.throws(()=>x.act('next',{profileHash:'old'}),/资料已变化/);x.act('next');assert.equal(x.flow.status().steps.profile.unknownAllowed,true);});
test('default PDF and saved preferences must exist; disabled/disconnected email does not claim a working connection',t=>{const x=setup(t);x.act('begin');x.act('skip');x.act('next');assert.throws(()=>x.act('next'),/默认 PDF/);x.store.put('assets',{id:'pdf',extension:'.pdf',default:true,archived:false});x.act('next');assert.throws(()=>x.act('next'),/预览/);const p=x.store.put('preferences',{id:'main',plans:[]});assert.throws(()=>x.act('next',{preferencesRevision:p.revision+1}),/预览/);x.act('next');assert.throws(()=>x.act('next'),/关注/);x.act('skip');x.store.put('connections',{id:'disconnected',kind:'imap',status:'disconnected',credentialsMissing:true});assert.throws(()=>x.act('next'),/连接/);x.store.put('connections',{id:'mail',kind:'imap',status:'configured',enabled:false,credentialsMissing:false});x.act('next');assert.equal(x.flow.status().status,'completed');assert.equal(x.flow.status().steps.mail.verification,'configuration_only');assert.equal(x.flow.status().steps.watch.status,'skipped');});
test('all steps can be explicitly skipped, completed survives restart, resume visits first skipped step',t=>{const x=setup(t);x.act('begin');for(let i=0;i<6;i++)x.act('skip');x.restart();assert.equal(x.flow.status().status,'completed');assert.equal(Object.keys(x.flow.status().steps).length,6);x.act('begin');assert.equal(x.flow.status().current,'import');assert.equal(x.flow.status().status,'active');});
test('corrupt existing profile keeps recovery as the first entry instead of suggesting a blank setup',t=>{const x=setup(t);const flow=createOnboarding(x.store,{read(){throw Error('corrupt');}},{});assert.equal(flow.status().suggested,false);assert.equal(flow.status().status,'not_started');});
