const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const {openStore}=require('../src/services/store.cjs'),{createReminders}=require('../src/services/reminders.cjs'),{dateAtHour}=require('../src/services/local-time.cjs');
function setup(t){const root=fs.mkdtempSync(path.join(os.tmpdir(),'reminder-date-review-')),store=openStore(root);let now=new Date('2026-10-01T00:00:00Z');const engine=createReminders(store,{clock:()=>now});engine.configure({...engine.settings(),digest:false});t.after(()=>{engine.close();store.close();fs.rmSync(root,{recursive:true,force:true});});return{store,engine,advance:at=>now=new Date(at)};}
test('local date conversion handles quarter-hour offsets, leap days and invalid dates',()=>{assert.deepEqual(dateAtHour('2026-10-03',9,'Asia/Kathmandu'),{at:'2026-10-03T03:15:00.000Z',adjusted:false});assert.equal(dateAtHour('2028-02-29',0,'Asia/Shanghai').at,'2028-02-28T16:00:00.000Z');assert.throws(()=>dateAtHour('2026-02-29',9,'UTC'));assert.throws(()=>dateAtHour('2026-10-03',24,'UTC'));});
test('DST fold picks first occurrence; one-hour and half-hour gaps move to first valid minute',()=>{assert.deepEqual(dateAtHour('2026-11-01',1,'America/New_York'),{at:'2026-11-01T05:00:00.000Z',adjusted:false});assert.deepEqual(dateAtHour('2026-03-08',2,'America/New_York'),{at:'2026-03-08T07:00:00.000Z',adjusted:true});assert.deepEqual(dateAtHour('2026-10-04',2,'Australia/Lord_Howe'),{at:'2026-10-03T15:30:00.000Z',adjusted:true});});
test('manual and plan date-only tasks fire at configured local hour and deduplicate',async t=>{const f=setup(t);f.engine.configure({...f.engine.settings(),plannedHour:17});for(const origin of ['manual','plan'])f.store.put('tasks',{id:origin,origin,status:'pending',title:origin,plannedOn:'2026-10-03'});await f.engine.tick();for(const r of f.store.list('reminders')){assert.equal(r.kind,'planned');assert.equal(r.dueAt,'2026-10-03T09:00:00.000Z');assert.equal(r.timeBasis,'date_only_reminder_time');assert.equal(r.status,'pending');}f.advance('2026-10-03T09:00:00Z');await f.engine.tick();await f.engine.tick();assert.equal(f.store.list('reminders').filter(r=>r.status==='delivered').length,2);});
test('opportunity date-only deadline remains separate from planned date and exact times',async t=>{const f=setup(t);f.store.put('opportunities',{id:'opportunity',deadline:'2026-10-06'});f.store.put('tasks',{id:'plan',origin:'plan',status:'pending',title:'Apply',plannedOn:'2026-10-03',opportunityId:'opportunity'});await f.engine.tick();const records=f.store.list('reminders');assert.equal(records.length,2);const deadline=records.find(r=>r.kind==='deadline_date');assert.equal(deadline.targetAt,'2026-10-06T01:00:00.000Z');assert.equal(deadline.dueAt,'2026-10-05T01:00:00.000Z');assert.equal(deadline.timeBasis,'date_only_reminder_time');assert.equal(f.store.get('opportunities','opportunity').deadline,'2026-10-06');});
test('interview start and distinct action deadline generate two schedules; equal times only one',async t=>{const f=setup(t);f.store.put('tasks',{id:'interview',status:'pending',title:'Interview',kind:'interview',startsAt:'2026-10-03T03:00:00Z',dueAt:'2026-10-02T03:00:00Z'});f.store.put('tasks',{id:'same',status:'pending',title:'Same',kind:'interview',startsAt:'2026-10-03T03:00:00Z',dueAt:'2026-10-03T03:00:00Z'});await f.engine.tick();const reminders=f.store.list('reminders').filter(r=>r.taskId==='interview');assert.equal(reminders.length,2);assert.equal(reminders.find(r=>r.kind==='interview').dueAt,'2026-10-03T02:00:00.000Z');assert.equal(reminders.find(r=>r.kind==='deadline').dueAt,'2026-10-01T03:00:00.000Z');assert.equal(f.store.list('reminders').filter(r=>r.taskId==='same').length,1);});
test('changing timezone revokes old pending local schedule and preserves DST adjustment provenance',async t=>{const f=setup(t);f.advance('2026-03-01T00:00:00Z');f.engine.configure({...f.engine.settings(),plannedHour:2});f.store.put('tasks',{id:'dst',origin:'manual',status:'pending',title:'DST',plannedOn:'2026-03-08'});await f.engine.tick();const old=f.store.list('reminders')[0];f.engine.configure({...f.engine.settings(),timezone:'America/New_York'});await f.engine.tick();assert.equal(f.store.get('reminders',old.id).status,'cancelled');const current=f.store.list('reminders').find(r=>r.status==='pending');assert.equal(current.dueAt,'2026-03-08T07:00:00.000Z');assert.equal(current.clockAdjusted,true);assert.throws(()=>f.engine.configure({...f.engine.settings(),plannedHour:24}));});
test('legacy delivered identity survives adding reminder kinds to the identity scheme',async t=>{const f=setup(t),{createHash}=require('node:crypto'),target='2026-10-03T03:00:00Z';f.store.put('tasks',{id:'legacy',status:'pending',title:'Legacy',dueAt:target});const id='reminder-'+createHash('sha256').update(JSON.stringify(['legacy',target,1440])).digest('hex').slice(0,32);f.store.put('reminders',{id,taskId:'legacy',title:'Legacy',targetAt:target,dueAt:'2026-10-02T03:00:00.000Z',kind:'deadline',status:'delivered',deliveredAt:'2026-10-02T03:00:00.000Z'});f.advance('2026-10-03T12:00:00Z');await f.engine.tick();assert.equal(f.store.list('reminders').length,1);assert.equal(f.store.list('reminders')[0].id,id);});
test('a nonexistent whole local date is surfaced without blocking other tasks',async t=>{const f=setup(t);f.engine.configure({...f.engine.settings(),timezone:'Pacific/Apia'});f.store.put('tasks',{id:'missing-date',status:'pending',title:'Missing date',plannedOn:'2011-12-30'});f.store.put('tasks',{id:'valid-date',status:'pending',title:'Valid date',plannedOn:'2026-09-30'});await f.engine.tick();assert.equal(f.store.list('reminders').filter(r=>r.taskId==='valid-date'&&r.status==='delivered').length,1);const scheduler=f.store.get('settings','scheduler');assert.equal(scheduler.state,'attention');assert.equal(scheduler.issues.length,1);assert.equal(scheduler.issues[0].taskId,'missing-date');});
