const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const {openStore}=require('../src/services/store.cjs'),{createReminders}=require('../src/services/reminders.cjs'),{createWorkflow}=require('../src/services/workflow.cjs');
function fixture(t){const root=fs.mkdtempSync(path.join(os.tmpdir(),'reminders-review-')),store=openStore(root);let now=new Date('2026-10-03T02:00:00Z');t.after(()=>{store.close();fs.rmSync(root,{recursive:true,force:true});});const engine=createReminders(store,{clock:()=>now});engine.configure({...engine.settings(),digest:false});return{root,store,engine,advance:date=>now=new Date(date)};}
test('disabling then enabling restores a future reminder exactly once',async t=>{const f=fixture(t);f.store.put('tasks',{id:'future',title:'Future',status:'pending',dueAt:'2026-10-06T02:00:00Z'});await f.engine.tick();f.engine.configure({...f.engine.settings(),enabled:false});await f.engine.tick();assert.equal(f.store.list('reminders')[0].status,'cancelled');f.engine.configure({...f.engine.settings(),enabled:true});await f.engine.tick();assert.equal(f.store.list('reminders')[0].status,'pending');f.advance('2026-10-07T02:00:00Z');await f.engine.tick();await f.engine.tick();assert.equal(f.store.list('reminders').length,1);assert.equal(f.store.list('reminders')[0].status,'delivered');});
test('editing a manual task title does not deliver the same deadline again',async t=>{const f=fixture(t),workflow=createWorkflow(f.store,{});let task=workflow.task({title:'Before',dueAt:'2026-10-03T03:00:00Z'});await f.engine.tick();workflow.task({...task,title:'After'});await f.engine.tick();assert.equal(f.store.list('reminders').filter(r=>r.taskId===task.id&&r.status==='delivered').length,1);});
test('pending titles follow edits while delivered history retains its original title',async t=>{const f=fixture(t),workflow=createWorkflow(f.store,{});let task=workflow.task({title:'Before',dueAt:'2026-10-06T03:00:00Z'});await f.engine.tick();task=workflow.task({...task,title:'Current'});await f.engine.tick();assert.equal(f.store.list('reminders')[0].title,'Current');f.advance('2026-10-07T02:00:00Z');await f.engine.tick();workflow.task({...task,title:'Later'});await f.engine.tick();assert.equal(f.store.list('reminders')[0].title,'Current');});
test('closing while native delivery is pending prevents late database access',async t=>{const f=fixture(t);let release;const engine=createReminders(f.store,{notify:()=>new Promise(resolve=>release=resolve)});engine.configure({...engine.settings(),digest:true,native:true,digestHour:0});const pending=engine.tick();assert.deepEqual(await engine.tick(),{state:'busy'});engine.close();f.store.close();release({state:'requested'});assert.deepEqual(await pending,{state:'closed'});assert.deepEqual(await engine.tick(),{state:'closed'});});
test('digest follows selected timezone and preference hour',async t=>{const f=fixture(t);f.store.put('preferences',{id:'main',plans:[],notification:{enabled:true,hour:23}});f.engine.configure({...f.engine.settings(),timezone:'America/New_York'});await f.engine.tick();assert.equal(f.store.list('reminders').length,0);f.advance('2026-10-03T03:00:00Z');await f.engine.tick();assert.equal(f.store.list('reminders')[0].day,'2026-10-02');await f.engine.tick();assert.equal(f.store.list('reminders').length,1);});
test('first reminder settings survive opening and saving preferences',t=>{const {createWorkbench}=require('../src/services/workbench.cjs'),root=fs.mkdtempSync(path.join(os.tmpdir(),'reminder-prefs-')),w=createWorkbench(root);t.after(()=>{w.close();fs.rmSync(root,{recursive:true,force:true});});w.reminders.configure({...w.reminders.settings(),digest:false,digestHour:17});const snapshot=w.snapshot();assert.deepEqual(snapshot.preferences.notification,{enabled:false,hour:17});w.command({action:'preferences',data:snapshot.preferences});assert.equal(w.reminders.settings().digest,false);assert.equal(w.reminders.settings().digestHour,17);});
test('reopening the database compensates overdue reminders without repeating delivered ones',async t=>{const f=fixture(t);f.store.put('tasks',{id:'future',title:'Future',status:'pending',dueAt:'2026-10-06T02:00:00Z'});await f.engine.tick();f.engine.close();f.store.close();let count=0;const reopened=openStore(f.root);t.after(()=>reopened.close());const options={clock:()=>new Date('2026-10-07T02:00:00Z'),notify:async()=>{count++;return {state:'requested'};}},engine=createReminders(reopened,options);engine.configure({...engine.settings(),native:true});await engine.tick();assert.equal(count,1);assert.equal(reopened.list('reminders')[0].late,true);await createReminders(reopened,options).tick();assert.equal(count,1);});
