'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),{randomUUID}=require('node:crypto');
const {createSearch}=require('../src/services/search.cjs');
function fixture(fetchImpl,clock=()=>2000000000000){const rows=new Map(),secrets=new Map();const store={get:(table,id)=>rows.get(table+':'+id),list:table=>[...rows].filter(([k])=>k.startsWith(table+':')).map(([,v])=>v),put:(table,item)=>{rows.set(table+':'+item.id,{...item,revision:(rows.get(table+':'+item.id)?.revision||0)+1});return item;}};const vault={get:k=>secrets.get(k),set:(k,v)=>secrets.set(k,v),remove:k=>secrets.delete(k)};const search=createSearch(store,{vault,fetchImpl,clock});return{search,store,vault,rows};}
const input=()=>({query:'公开公司产品',requestId:randomUUID(),confirmed:true});
const response=results=>new Response(JSON.stringify({web:{results}}));
const enable=s=>s.configure({enabled:true,confirmed:true,apiKey:'review-fake-secret'});
test('review: no network before consent; payload only explicit keyword and fixed headers',async()=>{let calls=0;const f=fixture(async(url,opts)=>{calls++;const u=new URL(url);assert.equal(u.origin,'https://api.search.brave.com');assert.equal(u.pathname,'/res/v1/web/search');assert.equal(u.searchParams.get('count'),'10');assert.equal(u.searchParams.get('q'),'公开公司产品');assert.equal(opts.redirect,'error');assert.equal(opts.body,undefined);assert.equal(opts.headers['X-Subscription-Token'],'review-fake-secret');return response([]);});f.search.config();enable(f.search);assert.equal(calls,0);await assert.rejects(f.search.run({...input(),confirmed:false}),/确认/);await assert.rejects(f.search.run({...input(),query:'x'.repeat(201)}));await assert.rejects(f.search.run({...input(),query:'line\nline'}));assert.equal(calls,0);await f.search.run({...input(),profile:'not-sent',email:'not-sent',browser:'not-sent'});assert.equal(calls,1);assert.equal(JSON.stringify([...f.rows]).includes('review-fake-secret'),false);assert.equal(JSON.stringify([...f.rows]).includes('公开公司产品'),false);});
test('review: request id cannot change query or replay after process restart',async()=>{let calls=0;const f=fixture(async()=>{calls++;return response([])});enable(f.search);const request=input();await f.search.run(request);await f.search.run(request);assert.equal(calls,1);await assert.rejects(f.search.run({...request,query:'different'}),/标识/);f.search.close();const again=createSearch(f.store,{vault:f.vault,fetchImpl:async()=>{calls++;return response([])}});await assert.rejects(again.run(request),/重新确认/);assert.equal(calls,1);again.close();});
test('review: 20-call rolling limit includes failures and does not leak provider error',async()=>{let calls=0;const f=fixture(async()=>{calls++;return new Response('review-fake-secret',{status:401})});enable(f.search);for(let i=0;i<20;i++)await assert.rejects(f.search.run(input()),e=>!e.message.includes('review-fake-secret'));await assert.rejects(f.search.run(input()),/20 次/);assert.equal(calls,20);});
test('review: cancel, reconfigure and close reject late response without publishing cache',async()=>{for(const mode of ['cancel','configure','close']){let finish,signal;const f=fixture(async(_u,o)=>{signal=o.signal;return await new Promise(r=>finish=r)});enable(f.search);const request=input(),pending=f.search.run(request);if(mode==='cancel')f.search.cancel();if(mode==='configure')f.search.configure({enabled:false});if(mode==='close')f.search.close();assert.equal(signal.aborted,true);finish(response([{title:'late',url:'https://company.example/page'}]));await assert.rejects(pending,/取消/);assert.notEqual(f.store.get('discoveryRuns','search-'+request.requestId).status,'ready');}});
test('review: first-page result filtering preserves strings but rejects unsafe links and duplicates',async()=>{const f=fixture(async()=>response([{title:'<img src=x onerror=alert(1)>',url:'https://company.example/page',description:'</textarea><script>alert(1)</script>'},{title:'dupe',url:'https://company.example/page#x'},{title:'local',url:'https://127.0.0.1'},{title:'script',url:'javascript:alert(1)'},{title:'credential',url:'https://user:secret@company.example/'}]));enable(f.search);const result=await f.search.run(input());assert.equal(result.results.length,1);assert.equal(result.results[0].url,'https://company.example/page');assert.ok(result.results[0].title.includes('<img'));});
test('review: persisted in-flight request becomes interrupted and cannot silently retry',async()=>{const f=fixture(async()=>response([]));enable(f.search);const req=input();const hash=require('node:crypto').createHash('sha256').update(req.query).digest('hex');f.store.put('discoveryRuns',{id:'search-'+req.requestId,kind:'web_search',status:'running',requestHash:hash});let called=false;const next=createSearch(f.store,{vault:f.vault,fetchImpl:async()=>{called=true;return response([])}});assert.equal(f.store.get('discoveryRuns','search-'+req.requestId).status,'interrupted');await assert.rejects(next.run(req),/重新确认/);assert.equal(called,false);});
