const fs=require('node:fs'),path=require('node:path'),os=require('node:os'),assert=require('node:assert/strict');
const {_electron}=require('playwright-core');
(async()=>{const root=path.resolve(__dirname,'../..'),workspace=fs.mkdtempSync(path.join(os.tmpdir(),'workbench-search-ui-'));require('../../tools/copy-tree.cjs').copyTree(path.join(root,'templates/blank-workspace'),workspace);const env={...process.env,QIUZHAO_TEST:'1',QIUZHAO_WORKSPACE:workspace,QIUZHAO_USER_DATA:path.join(workspace,'browser')};delete env.ELECTRON_RUN_AS_NODE;const app=await _electron.launch({executablePath:require('electron'),args:[path.join(root,'desktop')],env});try{await app.firstWindow();let ui;for(let i=0;i<100;i++){ui=app.context().pages().find(p=>p.url().includes('/ui/index.html'));if(ui)break;await new Promise(r=>setTimeout(r,100));}assert(ui);await ui.waitForFunction(()=>!!window.workbenchUI);const errors=[];ui.on('pageerror',e=>errors.push(e.message));
 // UI-only fixture at the native IPC boundary; service transport is verified separately by search*.test.cjs.
 await app.evaluate(({ipcMain,safeStorage})=>{safeStorage.isEncryptionAvailable=()=>true;safeStorage.encryptString=v=>Buffer.from('TEST:'+v);safeStorage.decryptString=v=>v.toString().slice(5);const original=ipcMain._invokeHandlers.get('workbench');ipcMain.removeHandler('workbench');ipcMain.handle('workbench',async(event,request)=>{if(request.action==='search-run'){if(request.data.confirmed!==true)throw Error('missing consent');return{id:'fixture',provider:'Brave Search',query:request.data.query,capturedAt:new Date().toISOString(),results:[{title:'<img src=x onerror=alert(1)>官网',url:'https://example.com/product',description:'搜索摘要，不代表事实'}]};}return original(event,request);});});
 await ui.evaluate(()=>window.workbenchUI.show('settings'));await ui.locator('[data-action="search-config"]').click();await ui.locator('#panel-body input[name="apiKey"]').fill('fake-search-key');await ui.locator('#panel-body input[name="enabled"]').check();await ui.locator('#panel-body input[name="confirmed"]').check();await ui.locator('#panel-body button[type="submit"]').click();await ui.waitForFunction(()=>window.workbenchUI.getState().search?.hasKey);
 const interview=await ui.evaluate(async()=>{const organization=await call('workbench',{action:'organization',data:{name:'搜索测试公司'}});return call('workbench',{action:'event',data:{organizationId:organization.id,type:'interview',title:'产品面试'}});});
 await ui.evaluate(()=>window.workbenchUI.show('interviews'));await ui.evaluate(id=>{const b=document.createElement('button');b.dataset.action='search-open';b.dataset.id=id;document.body.append(b);b.click();b.remove();},interview.id);await ui.locator('#panel-body input[name="query"]').fill('搜索测试公司 产品 官网');await ui.locator('#panel-body input[name="confirmed"]').check();await ui.locator('#panel-body button[type="submit"]').click();await ui.locator('#panel-body input[name="url"]').waitFor();assert.equal(await ui.locator('#panel-body img').count(),0);await ui.locator('#panel-body input[name="url"]').check();await ui.locator('#panel-body button[type="submit"]').click();await ui.locator('#panel-body textarea[name="urls"]').waitFor();assert.equal(await ui.locator('#panel-body textarea[name="urls"]').inputValue(),'https://example.com/product');assert.equal(await ui.locator('#panel-body input[name="confirmed"]').isChecked(),false);
 await ui.locator('#close-panel').click();await ui.evaluate(()=>window.workbenchUI.show('opportunities'));await ui.locator('[data-action="search-open"]').click();await ui.locator('[data-action="search-reopen"]').click();await ui.locator('#panel-body input[name="url"]').waitFor();assert.deepEqual(errors,[]);console.log('Search GUI passed with mocked search IPC: encrypted test key setting, query consent, escaped results, link selection, separate generation confirmation, result recovery.');
 }finally{await app.close();fs.rmSync(workspace,{recursive:true,force:true});}})().catch(e=>{console.error(e);process.exitCode=1;});
