const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const {createWorkbench}=require('../src/services/workbench.cjs');
const {extractJobs}=require('../src/services/sources.cjs');
const {publicUrl,publicAddress}=require('../src/services/public-page.cjs');
const job={'@type':'JobPosting',title:'工程师',hiringOrganization:{name:'示例公司'},identifier:{value:'A1'},datePosted:'2026-08-01',validThrough:'2026-11-01',jobLocation:{address:{addressLocality:'上海'}},description:'<p>开发系统</p>'};
function setup(t,reader){const root=fs.mkdtempSync(path.join(os.tmpdir(),'source-test-'));fs.mkdirSync(path.join(root,'知识库'));fs.writeFileSync(path.join(root,'知识库/profile.json'),JSON.stringify({schemaVersion:1,values:{basic:[{}]}}));const wb=createWorkbench(root,{sourceReader:reader});t.after(()=>{wb.close();fs.rmSync(root,{force:true,recursive:true});});return wb;}
test('public reader rejects internal URL forms and reserved network ranges',()=>{for(const u of ['http://example.com','https://127.0.0.1','https://[::1]','https://u:p@example.com','https://example.com:444','https://localhost','https://test.local'])assert.throws(()=>publicUrl(u));for(const ip of ['127.0.0.1','10.1.1.1','169.254.169.254','172.16.1.2','192.168.1.2','100.64.0.1','0.0.0.0','::1','224.0.0.1'])assert.equal(publicAddress(ip),false,ip);assert.equal(publicAddress('8.8.8.8'),true);});
test('structured dates remain unknown when invalid; dates never infer openness',()=>{const parsed=extractJobs(JSON.stringify({'@graph':[job,{...job,datePosted:'2026-02-30',validThrough:'明年'}]}),'https://example.com/job');assert.equal(parsed.length,2);assert.equal(parsed.find(x=>!x.openedOn).deadline,'');assert.equal(parsed[0].openStatus,undefined);});
test('read preserves evidence, confirm idempotently creates unknown-state role and never overwrites edited role',async t=>{const wb=setup(t,async url=>({url,body:JSON.stringify(job)}));const result=await wb.command({action:'source-preview',data:{url:'https://example.com/job'}});assert.equal(result.candidates.length,1);assert.equal(wb.store.list('opportunities').length,0);const c=wb.store.list('confirmations')[0];const input={id:c.id,revision:c.revision,company:'示例公司',batch:'2027校招',confirmed:true};const o=wb.sources.confirm(input);assert.equal(o.openStatus,'unknown');assert.equal(o.statusVerified,false);assert.equal(o.openedOn,'2026-08-01');const edited=wb.workflow.opportunity({...o,route:'enterprise',title:'手动调整名称'});assert.equal(wb.sources.confirm(input).title,edited.title);await wb.sources.preview({url:'https://example.com/job'});assert.equal(wb.store.list('confirmations').length,1);assert.equal(wb.sources.evidence(c.evidenceId).body,JSON.stringify(job));});
test('failed refresh preserves last good evidence, zero jobs does not close roles',async t=>{let mode=0;const wb=setup(t,async url=>{if(mode===1)throw Error('HTTP 403');return{url,body:mode===2?'<html>需登录</html>':JSON.stringify(job)};});await wb.sources.preview({url:'https://example.com/job'});const before=wb.store.list('sources')[0];mode=1;await assert.rejects(()=>wb.sources.preview({url:before.url}));assert.equal(wb.store.list('sources')[0].lastSuccessAt,before.lastSuccessAt);assert.equal(wb.store.list('sources')[0].evidenceId,before.evidenceId);mode=2;const empty=await wb.sources.preview({url:before.url});assert.equal(empty.candidates.length,0);assert.equal(wb.store.list('sources')[0].status,'manual_required');});
test('changed source evidence with query link and no external ID never overwrites hand-edited import',async t=>{let revision=0;const wb=setup(t,async url=>({url,body:JSON.stringify({...job,identifier:undefined,description:revision?'来源更新':'来源初版'})}));await wb.sources.preview({url:'https://example.com/job?id=42'});let c=wb.store.list('confirmations')[0];const o=wb.sources.confirm({id:c.id,revision:c.revision,company:'示例公司',batch:'2027校招',confirmed:true});wb.workflow.opportunity({...o,route:'enterprise',title:'手改标题',description:'手工补充'});revision++;await wb.sources.preview({url:'https://example.com/job?id=42'});c=wb.store.list('confirmations').find(x=>x.status==='pending');const input={id:c.id,revision:c.revision,company:'示例公司',batch:'2027校招',confirmed:true};assert.throws(()=>wb.sources.confirm(input),/选择/);input.targetOpportunityId=o.id;const review=wb.sources.review(input);const saved=wb.sources.confirm({...input,targetOpportunityId:review.opportunityId,opportunityRevision:review.opportunityRevision,updateFields:[],resetVerification:false});assert.equal(saved.title,'手改标题');assert.equal(saved.description,'手工补充');assert.equal(wb.store.list('opportunities').length,1);});
