'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const {createWorkbench}=require('../src/services/workbench.cjs');
const {extractJobs}=require('../src/services/sources.cjs');
const {publicUrl,publicAddress}=require('../src/services/public-page.cjs');
const url='https://jobs.example.invalid/jobs';
const job=(extra={})=>({'@type':'JobPosting',title:'工程师',identifier:{value:'job-1'},hiringOrganization:{name:'测试公司'},jobLocation:{address:{addressLocality:'上海'}},url:'/job/1',...extra});
function setup(t,reader){const root=fs.mkdtempSync(path.join(os.tmpdir(),'sources-review-'));fs.mkdirSync(path.join(root,'知识库'));fs.writeFileSync(path.join(root,'知识库/profile.json'),JSON.stringify({schemaVersion:1,demo:false,values:{basic:[{}]}}));const wb=createWorkbench(root,{sourceReader:reader});t.after(()=>{wb.close();fs.rmSync(root,{recursive:true,force:true});});return {root,wb};}
async function preview(wb){return wb.command({action:'source-preview',data:{url}});}
function accept(wb,id){const c=wb.store.get('confirmations',id),input={id,revision:c.revision,confirmed:true,company:'测试公司',batch:'2027 校招'},review=wb.command({action:'source-review',data:input});assert.notEqual(review.kind,'choose');return wb.command({action:'source-confirm',data:{...input,...(review.kind==='update'?{targetOpportunityId:review.opportunityId,opportunityRevision:review.opportunityRevision,updateFields:[],resetVerification:false}:{})}});}
test('URL and address boundary rejects local, credentials, protocols and nonstandard ports',()=>{for(const value of ['http://example.com','https://localhost','https://127.0.0.1','https://[::1]','https://user:pass@example.com','https://example.com:444','https://foo.local'])assert.throws(()=>publicUrl(value));for(const address of ['10.1.2.3','127.0.0.1','169.254.169.254','172.16.0.1','192.168.1.1','100.64.0.1','::1','224.1.1.1'])assert.equal(publicAddress(address),false);assert.equal(publicAddress('8.8.8.8'),true);assert.equal(publicUrl('https://example.com/x#fragment').href,'https://example.com/x');});
test('JSON-LD graph extracts bounded candidates without inferred dates or unsafe links',()=>{const body=`<script type="application/ld+json">${JSON.stringify({'@graph':[job({url:'javascript:alert(1)',datePosted:'2026-02-30',validThrough:'2027-01-01',description:'<b>要求</b>'}),job({url:'javascript:alert(1)',datePosted:'2026-02-30',validThrough:'2027-01-01',description:'<b>要求</b>'})]})}</script>`;const items=extractJobs(body,url);assert.equal(items.length,1);assert.equal(items[0].url,url);assert.equal(items[0].openedOn,'');assert.equal(items[0].deadline,'2027-01-01');assert.equal(items[0].description,'要求');assert.throws(()=>extractJobs('x'.repeat(1024*1024+1),url),/过大/);assert.throws(()=>extractJobs(JSON.stringify(Array.from({length:101},(_,i)=>job({title:'岗位'+i}))),url),/100/);});
test('source preview needs explicit review and creates unknown status with evidence',async t=>{const {wb}=setup(t,async()=>({url,body:JSON.stringify(job())}));const result=await preview(wb),id=result.candidates[0].id,c=wb.store.get('confirmations',id);assert.equal(wb.store.list('opportunities').length,0);assert.throws(()=>wb.sources.confirm({id,revision:c.revision,company:'测试公司',batch:'2027 校招'}),/核对/);const opp=accept(wb,id);assert.equal(opp.openStatus,'unknown');assert.equal(opp.statusVerified,false);assert.equal(opp.openedOn,'');assert.match(opp.evidence,/SHA256/);assert.equal(wb.command({action:'source-evidence',data:{id:c.evidenceId}}).body,JSON.stringify(job()));});
test('unchanged preview and changed description preserve user-edited imported opportunity',async t=>{let body=JSON.stringify(job());const {wb}=setup(t,async()=>({url,body}));let r=await preview(wb);const first=accept(wb,r.candidates[0].id);wb.store.put('opportunities',{...first,title:'手工标题',description:'手工备注'},{expectedRevision:first.revision});assert.equal((await preview(wb)).candidates[0].status,'accepted');body=JSON.stringify(job({description:'新官网描述'}));r=await preview(wb);const duplicate=accept(wb,r.candidates[0].id);assert.equal(duplicate.id,first.id);assert.equal(duplicate.title,'手工标题');assert.equal(duplicate.description,'手工备注');assert.equal(wb.store.list('opportunities').length,1);});
test('read failure retains last successful evidence, candidate and opportunity',async t=>{let fail=false;const {wb}=setup(t,async()=>{if(fail)throw Error('network failure');return {url,body:JSON.stringify(job())}});const r=await preview(wb);accept(wb,r.candidates[0].id);const before=wb.store.list('sources')[0];fail=true;await assert.rejects(preview(wb),/network failure/);const after=wb.store.list('sources')[0];assert.equal(after.status,'failed');assert.equal(after.evidenceId,before.evidenceId);assert.equal(after.lastSuccessAt,before.lastSuccessAt);assert.equal(wb.store.list('opportunities')[0].openStatus,'unknown');assert.equal(wb.store.list('confirmations').length,1);});
test('empty or dynamic page means manual_required and never means closed',async t=>{const {wb}=setup(t,async()=>({url,body:'<div id="app"></div>'}));assert.equal((await preview(wb)).candidates.length,0);assert.equal(wb.store.list('sources')[0].status,'manual_required');assert.equal(wb.store.list('discoveryRuns')[0].paginationComplete,false);});
test('confirmation failure rolls back organization and opportunity atomically',async t=>{const {wb}=setup(t,async()=>({url,body:JSON.stringify(job())}));const r=await preview(wb),original=wb.store.put;wb.store.put=function(collection,item,...args){if(collection==='confirmations'&&item.status==='accepted')throw Error('injected');return original(collection,item,...args)};assert.throws(()=>accept(wb,r.candidates[0].id),/injected/);wb.store.put=original;assert.equal(wb.store.list('organizations').length,0);assert.equal(wb.store.list('opportunities').length,0);assert.equal(wb.store.get('confirmations',r.candidates[0].id).status,'pending');});
test('close aborts active read and late completion writes no candidates',async t=>{let release,signal;const pending=new Promise(r=>release=r);const {wb,root}=setup(t,async(_url,options)=>{signal=options.signal;await pending;return {url,body:JSON.stringify(job())}});const run=preview(wb);await assert.rejects(preview(wb),/正在读取/);wb.close();assert.equal(signal.aborted,true);release();await assert.rejects(run,/取消/);const reopened=createWorkbench(root);try{assert.equal(reopened.store.list('confirmations').length,0);}finally{reopened.close();}});
test('same manual external ID and batch should reuse existing opportunity',async t=>{const {wb}=setup(t,async()=>({url,body:JSON.stringify(job())}));const org=wb.workflow.organization({name:'测试公司'});const manual=wb.workflow.opportunity({organizationId:org.id,title:'工程师',externalId:'job-1',batch:'2027 校招',city:['上海'],description:'手改'});const r=await preview(wb);assert.equal(accept(wb,r.candidates[0].id).id,manual.id);});
test('stable external ID survives source title change',async t=>{let body=JSON.stringify(job());const {wb}=setup(t,async()=>({url,body}));const first=accept(wb,(await preview(wb)).candidates[0].id);body=JSON.stringify(job({title:'工程师（研发）'}));assert.equal(accept(wb,(await preview(wb)).candidates[0].id).id,first.id);});
test('reopened source does not falsely remain checking after close',async t=>{let release;const pending=new Promise(r=>release=r);const {wb,root}=setup(t,async()=>{await pending;return {url,body:JSON.stringify(job())}});const run=preview(wb);wb.close();release();await assert.rejects(run);const reopened=createWorkbench(root);try{assert.notEqual(reopened.store.list('sources')[0].status,'checking');}finally{reopened.close();}});
test('startup recovers persisted unfinished reads and preserves successful evidence',t=>{const {wb,root}=setup(t);wb.store.put('sources',{id:'source-crashed',url,status:'checking',lastSuccessAt:'2026-10-01T00:00:00Z',evidenceId:'old-evidence'});wb.store.put('discoveryRuns',{id:'run-crashed',sourceId:'source-crashed',status:'running'});wb.close();const reopened=createWorkbench(root);try{const s=reopened.store.get('sources','source-crashed');assert.equal(s.status,'interrupted');assert.equal(s.lastSuccessAt,'2026-10-01T00:00:00Z');assert.equal(s.evidenceId,'old-evidence');assert.equal(reopened.store.get('discoveryRuns','run-crashed').status,'interrupted');}finally{reopened.close();}});
test('malformed DateTime never supplies a date and valid offset retains source calendar day',()=>{for(const value of ['2026-10-03Tgarbage','2026-10-03T99:00:00Z','2026-02-30T08:00:00Z','2026-10-03T08:00:00'])assert.equal(extractJobs(JSON.stringify(job({datePosted:value})),url)[0].openedOn,'');const p=extractJobs(JSON.stringify(job({datePosted:'2026-10-03T00:30:00+08:00',validThrough:'2026-10-04T23:30:00-08:00'})),url)[0];assert.equal(p.openedOn,'2026-10-03');assert.equal(p.deadline,'2026-10-04');});
