'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),vm=require('node:vm');
const {openStore}=require('../src/services/store.cjs'),{createSources,extractJobs}=require('../src/services/sources.cjs');
const body=extra=>JSON.stringify({'@type':'JobPosting',title:'工程师',identifier:{value:'role-1'},...extra});
function setup(t,reader){const root=fs.mkdtempSync(path.join(os.tmpdir(),'source-daily-review-')),store=openStore(root);let now=Date.parse('2026-10-03T00:00:00Z'),calls=0;const options={autoStart:false,clock:()=>new Date(now).toISOString(),reader:async(url,opt)=>{calls++;return reader?reader(url,opt):{url,body:body()}}};let sources=createSources(store,{},options);t.after(()=>{sources.close();store.close();fs.rmSync(root,{recursive:true,force:true});});return {root,store,get sources(){return sources;},advance:ms=>now+=ms,calls:()=>calls,restart:()=>{sources.close();sources=createSources(store,{},options);return sources;}};}
async function add(x,n=0){const r=await x.sources.preview({url:`https://example.invalid/jobs/${n}`});return x.store.get('sources',r.sourceId);}
function config(x,source,extra={}){return x.sources.configure({id:source.id,revision:source.revision,enabled:true,confirmed:true,...extra});}
test('fresh and disabled sources never schedule network; consent and 20-page cap apply before writes',async t=>{const x=setup(t);await x.sources.tick();assert.equal(x.calls(),0);const initial=await add(x);assert.throws(()=>config(x,initial,{confirmed:false}),/确认/);x.advance(172800000);await x.sources.tick();assert.equal(x.calls(),1);config(x,initial);for(let i=1;i<20;i++)config(x,await add(x,i));const last=await add(x,20);assert.throws(()=>config(x,last),/20/);assert.equal(x.store.list('sources').filter(s=>s.enabled).length,20);assert.equal(x.store.get('sources',last.id).enabled,undefined);});
test('restart catches up overdue once while explicit preview can run before due',async t=>{const x=setup(t);config(x,await add(x));await x.sources.tick();assert.equal(x.calls(),1);x.advance(5*86400000);x.restart();await x.sources.tick();assert.equal(x.calls(),2);await x.sources.tick();assert.equal(x.calls(),2);await add(x);assert.equal(x.calls(),3);await x.sources.tick();assert.equal(x.calls(),3);assert.equal(x.store.list('discoveryRuns').length,3);});
test('disabling an active check cancels late result without new evidence or proposals',async t=>{let block=false,release,signal;const pending=new Promise(r=>release=r);const x=setup(t,async(url,opt)=>{if(block){signal=opt.signal;await pending;}return {url,body:body(block?{description:'new'}:{})}});const s=config(x,await add(x));block=true;x.advance(86400000);const run=x.sources.tick();const current=x.store.get('sources',s.id);config(x,current,{enabled:false,confirmed:false});assert.equal(signal.aborted,true);release();await run;assert.equal(x.store.list('evidence').length,1);assert.equal(x.store.list('confirmations').length,1);assert.equal(x.store.get('sources',s.id).enabled,false);assert.equal(x.store.get('sources',s.id).status,'interrupted');});
test('pause of queued second source prevents its request; overlapping ticks do not double read',async t=>{let block=false,release;const pending=new Promise(r=>release=r);const x=setup(t,async(url)=>{if(block&&url.endsWith('/0'))await pending;return {url,body:body()}});config(x,await add(x,0));x.advance(1);const second=config(x,await add(x,1));x.advance(86400000);block=true;const run=x.sources.tick();await x.sources.tick();config(x,x.store.get('sources',second.id),{enabled:false,confirmed:false});release();await run;assert.equal(x.calls(),3);});
test('close during first scheduled page prevents writes and remaining queued network calls',async t=>{let block=false,release,signal;const pending=new Promise(r=>release=r);const x=setup(t,async(url,opt)=>{if(block){signal=opt.signal;await pending;}return {url,body:body()}});config(x,await add(x,0));config(x,await add(x,1));x.advance(86400000);block=true;const run=x.sources.tick();x.sources.close();assert.equal(signal.aborted,true);release();await run;assert.equal(x.calls(),3);assert.equal(x.store.list('confirmations').length,2);assert.equal(x.store.list('discoveryRuns').filter(r=>r.status==='interrupted').length,1);});
test('legacy proposal identity is reused with its original evidence after page wrapper changes',async t=>{let wrapper=0;const x=setup(t,async url=>({url,body:`<p>${wrapper}</p><script type="application/ld+json">${body()}</script>`}));const s=await add(x),old=x.store.list('confirmations')[0];x.store.remove('confirmations',old.id,old.revision);x.store.put('confirmations',{...old,id:'legacy-source-proposal',status:'accepted',opportunityId:'manual-original'});const legacySource={...x.store.get('sources',s.id)};delete legacySource.proposalIds;x.store.put('sources',legacySource,{expectedRevision:legacySource.revision});wrapper++;await add(x);const records=x.store.list('confirmations');assert.equal(records.length,1);assert.equal(records[0].id,'legacy-source-proposal');assert.equal(records[0].status,'accepted');assert.equal(records[0].evidenceId,old.evidenceId);assert.notEqual(x.store.get('sources',s.id).evidenceId,old.evidenceId);assert.equal(x.store.list('evidence').length,2);});
test('source association requires existing organization and does not change candidate company',async t=>{const x=setup(t);const s=await add(x);assert.throws(()=>config(x,s,{organizationId:'missing'}),/不存在/);x.store.put('organizations',{id:'org-linked',name:'用户选定单位',type:'enterprise'});config(x,s,{organizationId:'org-linked'});assert.equal(x.store.list('confirmations')[0].proposal.company,'');assert.equal(x.store.list('opportunities').length,0);});
test('coverage text distinguishes disabled, partial, failed and stale pages without claiming whole-company coverage',()=>{const file=fs.readFileSync(path.join(__dirname,'../src/ui/workbench.js'),'utf8');const match=file.match(/function sourceCoverage\(organizationId\)\{[^\n]+\}/);assert.ok(match);const context={state:{sources:[]},Date};vm.createContext(context);vm.runInContext(match[0],context);const text=()=>context.sourceCoverage('org');assert.match(text(),/尚未接入/);context.state.sources=[{organizationId:'org',enabled:true,lastSuccessAt:new Date().toISOString(),status:'needs_review'}];assert.match(text(),/未核验整体覆盖/);context.state.sources[0].status='manual_required';assert.match(text(),/人工补查/);context.state.sources[0].status='failed';assert.match(text(),/失败/);context.state.sources[0].status='needs_review';context.state.sources[0].lastSuccessAt='2020-01-01T00:00:00Z';assert.match(text(),/陈旧/);});
test('automatic startup microtask performs due catch-up with persisted consent',async t=>{const x=setup(t);const s=config(x,await add(x));x.sources.close();const current=x.store.get('sources',s.id);x.store.put('sources',{...current,nextCheckAt:'2020-01-01T00:00:00Z'},{expectedRevision:current.revision});let calls=0;const automatic=createSources(x.store,{}, {reader:async url=>{calls++;return {url,body:body()}}});try{await new Promise(resolve=>setImmediate(resolve));assert.equal(calls,1);assert.equal(x.store.get('sources',s.id).status,'needs_review');assert.equal(x.store.get('settings','source-scheduler').mode,'app_running');}finally{automatic.close();}});
