'use strict';
const {randomUUID}=require('node:crypto'),{hash}=require('./accounts.cjs');
function requestId(v){if(typeof v!=='string'||!/^[a-zA-Z0-9_-]{8,100}$/.test(v))throw Error('请求标识无效');return v;}
function createJobs(db,{prices={},validatePayload,processJob,validateResult,clock=Date.now,recover=true,jobTimeoutMs=180000}={}){
 if(!Number.isInteger(jobTimeoutMs)||jobTimeoutMs<1||jobTimeoutMs>600000)throw Error('任务时限无效');
 let closed=false;const controllers=new Map();
 const now=()=>new Date(clock()).toISOString();
 function ledger(accountId,kind,reference,balanceDelta,reservedDelta){db.run('UPDATE accounts SET balance=balance+?,reserved=reserved+? WHERE id=?',balanceDelta,reservedDelta,accountId);db.run('INSERT INTO ledger VALUES(?,?,?,?,?,?,?)',randomUUID(),accountId,kind,reference,balanceDelta,reservedDelta,now());}
 function quote(accountId,input){if(closed)throw Error('服务已关闭');if(db.get('SELECT frozen FROM accounts WHERE id=?',accountId)?.frozen)throw Error('账号额度暂被冻结，请联系运营方核对支付');const units=prices[input.kind];if(!Number.isSafeInteger(units)||units<1||units>100000)throw Error('此服务尚未定价或未开放');const payload=validatePayload(input.kind,input.payload),payloadHash=hash(JSON.stringify(payload)),id=randomUUID();db.run('INSERT INTO quotes VALUES(?,?,?,?,?,?)',id,accountId,input.kind,units,payloadHash,clock()+10*60000);return{id,kind:input.kind,units,expiresAt:clock()+10*60000,payloadHash,successDefinition:input.kind==='mail-parse'?'交付至少一项有片段原文依据、通过结构校验且可逐项采用的邮件字段；类型和动作含义仍需人工核对，采用与事件处理需另行确认。空结果、仅返回无法确认的日期等不可采用字段、失败或未交付取消不结算':input.kind==='field-correction'?'交付至少一项对应本次可用资料字段的纠错建议；网页现值与资料值留在本机，采用和网站保存需另行确认。无可用建议、失败或取消且未交付不结算':'返回通过结构与来源校验的完整结果；失败或取消且未交付不结算'};}
 function read(accountId,id){const j=db.get('SELECT * FROM jobs WHERE id=? AND account_id=?',id,accountId);if(!j)throw Error('任务不存在');return{id:j.id,kind:j.kind,status:j.status,units:j.units,error:j.error||'',result:j.result?JSON.parse(j.result):null,createdAt:j.created_at,updatedAt:j.updated_at};}
 function release(j,status,error){if(!['queued','running'].includes(j.status))return;ledger(j.account_id,'release',j.id,0,-j.units);db.run('UPDATE jobs SET status=?,error=?,updated_at=? WHERE id=?',status,error,now(),j.id);}
 if(recover)for(const j of db.all("SELECT * FROM jobs WHERE status IN ('queued','running')"))db.transaction(()=>release(j,'interrupted','服务中断，预留额度已返还；未自动重试'));
 async function execute(job,payload){const controller=new AbortController();controllers.set(job.id,controller);const timeout=setTimeout(()=>{controller.abort();if(!closed)db.transaction(()=>release(db.get('SELECT * FROM jobs WHERE id=?',job.id),'failed','任务超时，预留额度已返还'));controllers.delete(job.id);},jobTimeoutMs);timeout.unref?.();db.run("UPDATE jobs SET status='running',updated_at=? WHERE id=?",now(),job.id);
  try{const output=await processJob(job.kind,payload,{signal:controller.signal});if(closed||controller.signal.aborted)return;const result=validateResult(job.kind,output,payload);const json=JSON.stringify(result);if(Buffer.byteLength(json)>2*1024*1024)throw Error('结果过大，未交付');
   db.transaction(()=>{const current=db.get('SELECT * FROM jobs WHERE id=?',job.id);if(current.status!=='running')return;if(db.get('SELECT frozen FROM accounts WHERE id=?',job.account_id)?.frozen){release(current,'failed','支付待核对，预留额度已返还');return;}ledger(job.account_id,'settle',job.id,-job.units,-job.units);db.run("UPDATE jobs SET status='ready',result=?,updated_at=? WHERE id=?",json,now(),job.id);});
  }catch(error){if(!closed)db.transaction(()=>release(db.get('SELECT * FROM jobs WHERE id=?',job.id),controller.signal.aborted?'cancelled':'failed',controller.signal.aborted?'已取消，预留额度已返还':'未得到可用结果，预留额度已返还'));}finally{clearTimeout(timeout);controllers.delete(job.id);}}
 function start(accountId,input){if(closed)throw Error('服务已关闭');if(input.confirmed!==true)throw Error('请先确认本次额度与发送范围');const rid=requestId(input.requestId),payload=validatePayload(input.kind,input.payload),payloadHash=hash(JSON.stringify(payload));
  const job=db.transaction(()=>{const existing=db.get('SELECT * FROM jobs WHERE account_id=? AND request_id=?',accountId,rid);if(existing){if(existing.kind!==input.kind||existing.payload_hash!==payloadHash)throw Error('请求标识已用于其他范围');return{...existing,replayed:true};}
   const byQuote=db.get('SELECT * FROM jobs WHERE account_id=? AND quote_id=?',accountId,input.quoteId);if(byQuote){if(byQuote.kind!==input.kind||byQuote.payload_hash!==payloadHash)throw Error('报价已用于其他范围');return{...byQuote,replayed:true};}
   const q=db.get('SELECT * FROM quotes WHERE id=? AND account_id=?',input.quoteId,accountId);if(!q||q.expires<clock()||q.kind!==input.kind||q.payload_hash!==payloadHash)throw Error('报价已过期或范围变化，请重新确认');
   const a=db.get('SELECT * FROM accounts WHERE id=?',accountId);if(a?.frozen)throw Error('账号额度暂被冻结，请联系运营方核对支付');if(!a||a.balance-a.reserved<q.units)throw Error('可用额度不足');const id=randomUUID();ledger(accountId,'reserve',id,0,q.units);db.run('INSERT INTO jobs(id,account_id,request_id,quote_id,kind,units,status,payload_hash,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?)',id,accountId,rid,q.id,q.kind,q.units,'queued',payloadHash,now(),now());return db.get('SELECT * FROM jobs WHERE id=?',id);});
  if(!job.replayed)void execute(job,payload);return read(accountId,job.id);
 }
 function cancel(accountId,id){db.transaction(()=>{const j=db.get('SELECT * FROM jobs WHERE id=? AND account_id=?',id,accountId);if(!j)throw Error('任务不存在');release(j,'cancelled','用户取消，预留额度已返还');});controllers.get(id)?.abort();return read(accountId,id);}
 function refund(accountId,id){return db.transaction(()=>{const j=db.get('SELECT * FROM jobs WHERE id=? AND account_id=?',id,accountId);if(!j||!['ready','refunded'].includes(j.status))throw Error('该任务未结算');if(j.status==='ready'){ledger(accountId,'refund',id,j.units,0);db.run("UPDATE jobs SET status='refunded',updated_at=? WHERE id=?",now(),id);}return read(accountId,id);});}
 function grant(accountId,units,reference){if(!Number.isSafeInteger(units)||units<1||units>1000000)throw Error('额度无效');return db.transaction(()=>{if(!db.get('SELECT id FROM ledger WHERE account_id=? AND kind=? AND reference=?',accountId,'grant',reference))ledger(accountId,'grant',reference,units,0);return true;});}
 function close(){if(closed)return;closed=true;for(const[id,c]of controllers){c.abort();db.transaction(()=>release(db.get('SELECT * FROM jobs WHERE id=?',id),'interrupted','服务关闭，预留额度已返还'));}}
 return{quote,start,read,cancel,refund,grant,close};
}
module.exports={createJobs,requestId};
