'use strict';
const {randomUUID,createHash}=require('node:crypto');
const {publicUrl,readPublicPage}=require('../desktop/src/services/public-page.cjs');
const {extractJobs}=require('../desktop/src/services/sources.cjs');
const DAY=86400000;
function createMonitoring(db,{enabled=false,reader=readPublicPage,clock=Date.now,autoStart=true}={}){
 db.db.exec(`CREATE TABLE IF NOT EXISTS monitors(id TEXT PRIMARY KEY,account_id TEXT NOT NULL REFERENCES accounts(id),label TEXT NOT NULL,url TEXT NOT NULL,enabled INTEGER NOT NULL DEFAULT 1,status TEXT NOT NULL DEFAULT 'pending',last_attempt INTEGER,last_success INTEGER,next_check INTEGER NOT NULL,content_hash TEXT,error TEXT NOT NULL DEFAULT '',revision INTEGER NOT NULL DEFAULT 1,UNIQUE(account_id,url));
 CREATE TABLE IF NOT EXISTS monitor_notices(id TEXT PRIMARY KEY,account_id TEXT NOT NULL REFERENCES accounts(id),monitor_id TEXT NOT NULL REFERENCES monitors(id) ON DELETE CASCADE,kind TEXT NOT NULL,message TEXT NOT NULL,created_at INTEGER NOT NULL,read INTEGER NOT NULL DEFAULT 0);
 CREATE TABLE IF NOT EXISTS monitor_attempts(account_id TEXT NOT NULL REFERENCES accounts(id),url_hash TEXT NOT NULL,last_attempt INTEGER NOT NULL,PRIMARY KEY(account_id,url_hash));
 CREATE TABLE IF NOT EXISTS monitor_health(id INTEGER PRIMARY KEY CHECK(id=1),last_tick INTEGER NOT NULL);`);
 const active=new Map();let closed=false,ticking=false,timer;
 db.run("UPDATE monitors SET status='interrupted',error='服务重启，上次检查未完成',next_check=? WHERE status='checking'",clock());
 function requireEnabled(){if(!enabled)throw Error('此服务尚未启用云端监控');if(closed)throw Error('监控服务已关闭');}
 function own(accountId,id){const row=db.get('SELECT * FROM monitors WHERE id=? AND account_id=?',id,accountId);if(!row)throw Error('监控不存在');return row;}
 function list(accountId){return{enabled,intervalHours:24,scope:'selected_public_pages',channel:'inbox',lastTick:db.get('SELECT last_tick FROM monitor_health WHERE id=1')?.last_tick||null,monitors:db.all('SELECT * FROM monitors WHERE account_id=? ORDER BY rowid DESC LIMIT 20',accountId),notices:db.all('SELECT * FROM monitor_notices WHERE account_id=? ORDER BY rowid DESC LIMIT 100',accountId)};}
 function add(accountId,input){requireEnabled();if(input.confirmed!==true)throw Error('请确认上传单位名称和公开链接并每日检查');const url=publicUrl(input.url).href,label=typeof input.label==='string'?input.label.trim():'';if(!label||label.length>150||url.length>2000)throw Error('名称或链接长度无效');return db.transaction(()=>{const existing=db.get('SELECT * FROM monitors WHERE account_id=? AND url=?',accountId,url);if(existing)return existing;if(db.get('SELECT COUNT(*) AS n FROM monitors WHERE account_id=?',accountId).n>=20)throw Error('每个账号最多监控 20 个公开页面');const id=randomUUID();db.run('INSERT INTO monitors(id,account_id,label,url,next_check) VALUES(?,?,?,?,?)',id,accountId,label,url,clock());return own(accountId,id);});}
 function update(accountId,input){if(closed)throw Error('监控服务已关闭');const row=own(accountId,input.id);if(input.revision!==row.revision)throw Error('监控已变化，请刷新');if(typeof input.enabled!=='boolean')throw Error('请选择开启或暂停');if(input.enabled)requireEnabled();if(Boolean(row.enabled)===input.enabled)return row;active.get(row.id)?.abort();db.run("UPDATE monitors SET enabled=?,revision=revision+1,status=?,next_check=? WHERE id=?",input.enabled?1:0,input.enabled?'pending':'paused',Math.max(row.next_check,(row.last_attempt??(clock()-DAY))+DAY),row.id);return own(accountId,row.id);}
 function remove(accountId,input){if(closed)throw Error('监控服务已关闭');const row=own(accountId,input.id);if(input.revision!==row.revision)throw Error('监控已变化，请刷新');active.get(row.id)?.abort();db.run('DELETE FROM monitors WHERE id=? AND account_id=?',row.id,accountId);return{removed:true};}
 function read(accountId,input){if(closed)throw Error('监控服务已关闭');const n=db.get('SELECT * FROM monitor_notices WHERE id=? AND account_id=?',input.id,accountId);if(!n)throw Error('通知不存在');db.run('UPDATE monitor_notices SET read=1 WHERE id=? AND account_id=?',n.id,accountId);return{read:true};}
 function notice(row,kind,message){db.run('INSERT INTO monitor_notices(id,account_id,monitor_id,kind,message,created_at) VALUES(?,?,?,?,?,?)',randomUUID(),row.account_id,row.id,kind,message,clock());db.run('DELETE FROM monitor_notices WHERE account_id=? AND id NOT IN (SELECT id FROM monitor_notices WHERE account_id=? ORDER BY rowid DESC LIMIT 100)',row.account_id,row.account_id);}
 async function check(row){const now=clock(),urlHash=createHash('sha256').update(row.url).digest('hex'),recent=db.get('SELECT last_attempt FROM monitor_attempts WHERE account_id=? AND url_hash=?',row.account_id,urlHash),budget=db.get('SELECT COUNT(*) AS n,MIN(last_attempt) AS first FROM monitor_attempts WHERE account_id=? AND last_attempt>?',row.account_id,now-DAY);const allowedAt=Math.max(recent?recent.last_attempt+DAY:0,budget.n>=20?budget.first+DAY:0);if(allowedAt>now){db.run('UPDATE monitors SET next_check=? WHERE id=?',allowedAt,row.id);return;}db.run('INSERT INTO monitor_attempts(account_id,url_hash,last_attempt) VALUES(?,?,?) ON CONFLICT(account_id,url_hash) DO UPDATE SET last_attempt=excluded.last_attempt',row.account_id,urlHash,now);const controller=new AbortController();active.set(row.id,controller);db.run("UPDATE monitors SET status='checking',last_attempt=? WHERE id=?",clock(),row.id);
  try{const page=await reader(row.url,{signal:controller.signal});if(controller.signal.aborted||closed)return;const current=db.get('SELECT * FROM monitors WHERE id=?',row.id);if(!current||!current.enabled||current.revision!==row.revision)return;
   // Compare structured vacancies when available; dynamic HTML alone is not proof of a vacancy change.
   const jobs=extractJobs(page.body,page.url),normalized=jobs.map(j=>JSON.stringify(j)).sort();const digest=jobs.length?createHash('sha256').update(JSON.stringify(normalized)).digest('hex'):null;
   db.transaction(()=>{if(digest&&row.content_hash&&digest!==row.content_hash)notice(row,'changed','公开页的结构化岗位内容有变化，请打开官网核对；不代表新增或关闭已确认');if(row.status==='failed'||row.status==='interrupted')notice(row,'recovered','公开页面已恢复读取');db.run('UPDATE monitors SET status=?,last_success=?,next_check=?,content_hash=?,error=? WHERE id=?',jobs.length?'success':'manual_required',clock(),clock()+DAY,digest||row.content_hash,jobs.length?'':'未读取到结构化岗位，请手动核验；不代表停止招聘',row.id);});
  }catch(error){if(controller.signal.aborted||closed)return;const current=db.get('SELECT * FROM monitors WHERE id=?',row.id);if(!current||!current.enabled||current.revision!==row.revision)return;db.transaction(()=>{if(row.status!=='failed')notice(row,'failed','公开页面检查失败，保留上次成功结果，请手动核验');db.run("UPDATE monitors SET status='failed',error=?,next_check=? WHERE id=?",'读取失败，请在浏览器核验公开链接；可能需要登录或稍后重试',clock()+DAY,row.id);});}
  finally{active.delete(row.id);}
 }
 async function tick(){if(!enabled||closed||ticking)return; ticking=true;try{db.run('DELETE FROM monitor_attempts WHERE last_attempt<?',clock()-2*DAY);db.run('INSERT INTO monitor_health(id,last_tick) VALUES(1,?) ON CONFLICT(id) DO UPDATE SET last_tick=excluded.last_tick',clock());const rows=db.all('SELECT * FROM monitors WHERE enabled=1 AND next_check<=? ORDER BY next_check LIMIT 20',clock());for(const row of rows){if(closed)break;const current=db.get('SELECT * FROM monitors WHERE id=?',row.id);if(current?.enabled&&current.revision===row.revision)await check(current);}}finally{ticking=false;}}
 if(enabled&&autoStart){timer=setInterval(()=>{tick().catch(()=>{});},60000);timer.unref();queueMicrotask(()=>tick().catch(()=>{}));}
 return{list,add,update,remove,read,tick,close(){closed=true;clearInterval(timer);for(const controller of active.values())controller.abort();}};
}
module.exports={createMonitoring};
