'use strict';
const {createHmac,timingSafeEqual,randomUUID}=require('node:crypto'),{requestId}=require('./jobs.cjs'),{hash}=require('./accounts.cjs');
function verifyStripe(body,header,secret,clock=Date.now){if(!secret||typeof header!=='string'||header.length>4096)throw Error('支付签名缺失');const parts=header.split(',').map(s=>s.split('=')),timestamp=parts.find(([k])=>k==='t')?.[1];if(!/^\d+$/.test(timestamp||'')||Math.abs(clock()/1000-Number(timestamp))>300)throw Error('支付签名过期');const expected=createHmac('sha256',secret).update(timestamp+'.').update(body).digest();if(!parts.some(([k,v])=>k==='v1'&&/^[a-f0-9]{64}$/.test(v||'')&&timingSafeEqual(Buffer.from(v,'hex'),expected)))throw Error('支付签名无效');return JSON.parse(body.toString('utf8'));}
function createPayments(db,{secretKey,webhookSecret,packs=[],successUrl,cancelUrl,live=false,fetchImpl=fetch,clock=Date.now}={}){
 for(const pack of packs)if(!pack||typeof pack.id!=='string'||!/^[a-z0-9_-]{1,50}$/.test(pack.id)||!Number.isSafeInteger(pack.units)||pack.units<1||pack.units>1000000||!Number.isSafeInteger(pack.amount)||pack.amount<1||pack.amount>10000000||!['usd','cny','eur','hkd','sgd'].includes(pack.currency))throw Error('额度包配置无效');
 if(new Set(packs.map(p=>p.id)).size!==packs.length)throw Error('额度包标识重复');
 if(secretKey){if(!secretKey.startsWith(live?'sk_live_':'sk_test_'))throw Error('支付密钥与运行模式不一致');for(const value of [successUrl,cancelUrl]){const u=new URL(value);if(u.protocol!=='https:'||u.username||u.password)throw Error('支付返回地址必须为 HTTPS');}}
 const enabled=!!(secretKey&&webhookSecret&&packs.length),active=new Map();
 async function checkout(accountId,input){if(!enabled)throw Error('支付尚未配置');if(db.get('SELECT frozen FROM accounts WHERE id=?',accountId)?.frozen)throw Error('账号支付待核对');if(input.confirmed!==true)throw Error('请确认购买金额与额度');const pack=packs.find(p=>p.id===input.packId);if(!pack)throw Error('额度包不存在');const rid=requestId(input.requestId),id=hash(accountId+'\0'+rid).slice(0,40);
  let order=db.get('SELECT * FROM orders WHERE id=?',id);if(order&&order.pack_id!==pack.id)throw Error('请求标识已用于其他购买');const expected=order||pack;if(input.amount!==expected.amount||input.currency!==expected.currency||input.units!==expected.units)throw Error('购买金额或额度已变化，请重新确认');if(order?.url)return{orderId:id,url:order.url,status:order.status};if(active.has(id))return active.get(id);if(order&&clock()-Date.parse(order.created_at)>20*3600000)throw Error('旧订单接收状态不明，请联系运营方核对，不自动创建第二笔支付');
  if(!order){db.run('INSERT INTO orders(id,account_id,request_id,pack_id,units,amount,currency,status,created_at) VALUES(?,?,?,?,?,?,?,?,?)',id,accountId,rid,pack.id,pack.units,pack.amount,pack.currency,'pending',new Date(clock()).toISOString());order=db.get('SELECT * FROM orders WHERE id=?',id);}
  const action=(async()=>{const body=new URLSearchParams({mode:'payment',client_reference_id:id,success_url:successUrl,cancel_url:cancelUrl,'line_items[0][quantity]':'1','line_items[0][price_data][currency]':order.currency,'line_items[0][price_data][unit_amount]':String(order.amount),'line_items[0][price_data][product_data][name]':`招聘工作台 ${order.units} 额度`});
   const response=await fetchImpl('https://api.stripe.com/v1/checkout/sessions',{method:'POST',redirect:'error',signal:AbortSignal.timeout(30000),headers:{Authorization:`Bearer ${secretKey}`,'Content-Type':'application/x-www-form-urlencoded','Idempotency-Key':`checkout-${id}`},body});if(!response.ok)throw Error('支付渠道暂不可用，请用同一订单重试');let text='',size=0;for await(const chunk of response.body){size+=chunk.length;if(size>256000)throw Error('支付响应异常');text+=Buffer.from(chunk).toString('utf8');}const result=JSON.parse(text),url=new URL(result.url);if(url.protocol!=='https:'||url.hostname!=='checkout.stripe.com'||!/^cs_/.test(result.id)||result.client_reference_id!==id)throw Error('支付渠道返回无效订单');db.run('UPDATE orders SET session_id=?,url=? WHERE id=?',result.id,url.href,id);return{orderId:id,url:url.href,status:order.status};})();active.set(id,action);try{return await action;}finally{active.delete(id);}
 }
 function webhook(body,signature){if(!enabled)throw Error('支付尚未配置');const event=verifyStripe(body,signature,webhookSecret,clock);if(event.livemode!==live)throw Error('支付模式不匹配');if(['charge.refunded','charge.dispute.created','charge.dispute.funds_withdrawn'].includes(event.type)){const object=event.data?.object,intent=typeof object?.payment_intent==='string'?object.payment_intent:object?.payment_intent?.id;return db.transaction(()=>{if(db.get('SELECT id FROM payment_alerts WHERE id=?',event.id))return{received:true};const order=intent?db.get('SELECT * FROM orders WHERE payment_intent=?',intent):null;if(order)db.run('UPDATE accounts SET frozen=1 WHERE id=?',order.account_id);db.run('INSERT INTO payment_alerts(id,event_type,account_id,order_id,payment_intent,status,created_at) VALUES(?,?,?,?,?,?,?)',event.id,event.type,order?.account_id||null,order?.id||null,intent||null,'needs_review',new Date(clock()).toISOString());return{received:true};});}if(!['checkout.session.completed','checkout.session.async_payment_succeeded'].includes(event.type))return{received:true};const session=event.data?.object;if(session?.payment_status!=='paid')return{received:true};
  return db.transaction(()=>{const order=db.get('SELECT * FROM orders WHERE id=?',session.client_reference_id);if(!order||!order.session_id||order.session_id!==session.id||order.amount!==session.amount_total||order.currency!==session.currency)throw Error('支付回调与订单不一致');if(order.status==='paid')return{received:true};const now=new Date(clock()).toISOString(),intent=typeof session.payment_intent==='string'?session.payment_intent:session.payment_intent?.id||null;if(intent&&db.get('SELECT id FROM payment_alerts WHERE payment_intent=? AND status=?',intent,'needs_review')){db.run('UPDATE accounts SET frozen=1 WHERE id=?',order.account_id);db.run('UPDATE payment_alerts SET account_id=?,order_id=? WHERE payment_intent=?',order.account_id,order.id,intent);}db.run('UPDATE accounts SET balance=balance+? WHERE id=?',order.units,order.account_id);db.run('INSERT INTO ledger VALUES(?,?,?,?,?,?,?)',randomUUID(),order.account_id,'purchase',order.id,order.units,0,now);db.run("UPDATE orders SET status='paid',payment_intent=? WHERE id=?",typeof session.payment_intent==='string'?session.payment_intent:session.payment_intent?.id||null,order.id);return{received:true};});
 }
 return{checkout,webhook,catalog:()=>({enabled,mode:live?'live':'test',packs:enabled?packs:[]})};
}
module.exports={createPayments,verifyStripe};
