const {executeControl}=require('./control-dispatcher.cjs');
const {fillTextControl,confirmedAge}=require('./text-control.cjs');
const {fillPhoenix}=require('./phoenix.cjs');const {controlValue}=require('./control-value.cjs');const {fillRegion}=require('./region.cjs');
const isQiyuan=page=>new URL(page.url()).hostname==='qiyuanzp.zhiye.com'&&new URL(page.url()).pathname.startsWith('/form');
async function fillQiyuan(page,profile,cancelled=()=>false,inspect=false){
const runTag=String(Date.now());const started=Date.now(),report=[],b=profile.values.basic[0],s=profile.aircasSupplement||{},v=profile.values,seen=new Set();
const label=t=>page.locator('.form-item__title').filter({hasText:new RegExp('^'+t.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')+'$')});
const forms=(...titles)=>titles.reduce((l,t)=>l.filter({has:label(t)}),page.locator('.ux-standard-form'));
const field=(f,t)=>f.locator('.form-item').filter({has:label(t)});
async function set(f,t,value,options={}){const id=await f.evaluate(e=>[...document.querySelectorAll('.ux-standard-form')].indexOf(e));seen.add(id+'|'+t);const r={label:t,group:options.group||'启元实验室',status:'pending',reason:''};report.push(r);if(value===undefined||value===null||value===''){r.reason='缺少确认资料';return;}if(cancelled()){r.reason='已停止';return;}if(inspect){const it=field(f,t);if(await it.count()===1)await it.evaluate((e,tag)=>e.dataset.qiyuanChecked=tag,runTag);r.status='ready';return;}
try{const item=field(f,t);if(await item.count()===1)await item.evaluate((e,tag)=>e.dataset.qiyuanChecked=tag,runTag);if(await item.count()===0){r.status='notApplicable';r.reason='条件不适用，字段未显示';return;}if(await item.count()!==1)throw Error('字段不唯一');if(!await item.isVisible()){r.status='notApplicable';r.reason='此条件字段当前未显示';return;}const root=t==='证件号码'?item.locator('input').first():await item.locator('.phoenix-select').count()?item.locator('.phoenix-select'):await item.locator('.phoenix-radio-group').count()?item.locator('.phoenix-radio-group'):item.locator('input:not([type=checkbox]),textarea').first();
let current=await root.evaluate(controlValue);const expected=options.region?options.region.at(-1):String(value);if(current===expected||(options.date&&current===expected.slice(0,7))){r.status='existing';return;}
if(current&&!/^(请选择|请输入)$/.test(current)&&!options.correct)throw Error('已有内容不同，待核对');
const result=await executeControl(page,root,{value:expected,regionPath:options.region,match:{groupId:options.group||'education',key:t,spec:{date:!!options.date}},allowOverwrite:!!options.correct,cancelled});r.controlType=result.controlType;r.attempts=result.attempts;
current=await root.evaluate(controlValue);if(current!==expected&&!(options.date&&current===expected.slice(0,7))&&!(options.region&&current.includes(expected)))throw Error('回读不一致');r.status='filled';r.reason='已回读，未暂存或提交';
}catch(e){r.reason=e.message;r.controlType=e.controlType;r.attempts=e.attempts;}}
async function ensure(group,identityLabel,identity,addText){let found=-1;for(let i=0;i<await group.count();i++){const val=await field(group.nth(i),identityLabel).locator('input,textarea').first().inputValue().catch(()=> '');if(val===identity){found=i;break;}}if(found>=0)return group.nth(found);
for(let i=0;i<await group.count();i++){const val=await field(group.nth(i),identityLabel).locator('input,textarea').first().inputValue().catch(()=> '');if(!val)return group.nth(i);}
if(inspect||cancelled())return null;const before=await group.count();await page.getByText(addText,{exact:true}).click({timeout:1500});try{await group.nth(before).waitFor({timeout:2000});return group.nth(before);}catch{report.push({label:addText,group:'启元实验室',status:'pending',reason:'当前记录尚有必填项，网站未新增下一条；继续其他栏目'});return null;}}
if(!inspect){const cancel=page.locator('.area-selector-container:visible .phoenix-button__content').filter({hasText:/^取消$/});if(await cancel.count()===1)await cancel.click();const otherCancel=page.locator('.constant-main-selector-container:visible .phoenix-button__content').filter({hasText:/^取消$/});if(await otherCancel.count()===1)await otherCancel.click();}
const basic=forms('是否博士后');if(await basic.count()===1){for(const [t,value]of Object.entries({'姓名':b.name,'性别':b.gender,'最高学历':v.education[0].level,'最高学位':'硕士','国籍':s.nationality,'民族':b.ethnicity,'政治面貌':b.politicalStatus,'婚否':b.maritalStatus,'健康状况':'健康','手机号码':b.phone,'邮箱':b.email,'证件号码':b.idNumber,'毕业学校':v.education[0].school,'个人特点、特长':v.evaluation[0].description,'是否博士后':'否','博士后工作站':'无'}))await set(basic,t,value);
await set(basic,'出生日期',b.birthDate,{date:true});await set(basic,'籍贯',b.nativePlace,{region:b.nativePlacePath});await set(basic,'户口所在地','海淀区',{region:['北京市','海淀区']});}
const eduForms=forms('学校名称','导师');const educations=[...v.education,{school:s.high_school,level:'高中',major:'无',degree:'无',startTime:s.high_school_start,endTime:s.high_school_end,supervisor:'无'}];
for(const e of educations){let f;for(let i=0;i<await eduForms.count();i++){const level=await field(eduForms.nth(i),'学历').locator('input').inputValue();if(level===e.level){f=eduForms.nth(i);break;}}if(!f&&!inspect){const before=await eduForms.count();await page.getByText('添加教育经历',{exact:true}).click();await eduForms.nth(before).waitFor();f=eduForms.nth(before);}if(!f)continue;
for(const [t,value]of Object.entries({'学校名称':e.school,'专业名称':e.major,'学历':e.level,'学位':/硕士/.test(e.level)?'硕士':e.level==='本科'?'学士':'无','导师':/硕士/.test(e.level)?s.supervisor_name:'无'}))await set(f,t,value,{correct:t==='学位'||t==='导师'||(t==='专业名称'&&e.level==='本科')});
await set(f,'开始时间',e.startTime,{date:true});await set(f,'结束时间',e.endTime,{date:true});}
const intern=v.internship[0];for(const spec of [{group:forms('职位名称','证明人姓名'),fields:{'开始时间':intern.startTime,'结束时间':intern.endTime,'公司名称':intern.company,'部门':intern.department,'职位名称':intern.position,'证明人姓名':s.internship_leader}},{group:forms('工作事项及业绩'),fields:{'开始时间':intern.startTime,'结束时间':intern.endTime,'公司名称':intern.company,'部门':intern.department,'工作事项及业绩':intern.description,'本人作用':intern.position}}])if(await spec.group.count()===1)for(const [t,value]of Object.entries(spec.fields))await set(spec.group,t,value,{date:/^(开始|结束)时间$/.test(t)});
const family=forms('关系','年龄');for(const member of s.family||[]){const f=await ensure(family,'姓名',member.userName,'添加家庭其他成员');if(!f)continue;for(const [t,value]of Object.entries({'姓名':member.userName,'关系':member.relation,'工作（学习）单位':member.workUnit,'年龄':confirmedAge(member),'职务及职称':member.position}))await set(f,t,value);}
const projects=forms('项目名称','项目来源');for(const project of v.projects.filter(p=>profile.autoProjectNames.includes(p.name))){const f=await ensure(projects,'项目名称',project.name,'添加已完成及在研科研项目/工程技术项目');if(!f)continue;for(const [t,value]of Object.entries({'项目名称':project.name,'项目来源':project.name.split('｜')[1]?.trim(),'个人作用':project.role,'开始时间':project.startTime,'结束时间':project.endTime}))await set(f,t,value,{date:/^(开始|结束)时间$/.test(t)});}
const thesis=forms('硕士学位论文标题');if(await thesis.count()===1){for(const [t,value]of Object.entries({'硕士学位论文标题':v.education[0].thesis,'硕士导师姓名':s.supervisor_name,'博士学位论文标题':'无','博士导师姓名':'无','博士后出站报告论文标题':'无','博士后导师姓名':'无'}))await set(thesis,t,value);}
const self=forms('具体内容');if(await self.count()===1)await set(self,'具体内容',v.projects.filter(p=>profile.autoProjectNames.includes(p.name)).map(p=>p.name+'\n'+p.description).join('\n\n'));
const quals=forms('证书名称');for(const language of v.languages){const f=await ensure(quals,'证书名称',language.name,'添加资格证书');if(!f)continue;await set(f,'证书名称',language.name);await set(f,'获得时间',language.date,{date:true});await set(f,'证书描述',language.name+'：'+language.score);}
const awards=forms('获奖描述');for(const award of v.awards){const description=award.name+'（'+award.date+'）\n'+award.description;let f;for(let i=0;i<await awards.count();i++){const text=await awards.nth(i).locator('textarea').inputValue();if(text===description||[award.name,...award.aliases].some(a=>text.includes(a))||(award.name.includes('第十五届')&&text==='北邮研究生英语演讲比赛第一名（2024）')){f=awards.nth(i);break;}}if(!f)f=await ensure(awards,'获奖描述',description,'添加奖惩情况');if(f)await set(f,'获奖描述',description,{correct:true});}
const spouse=forms('文化程度','现工作单位、职务及职称');if(b.maritalStatus==='未婚'&&await spouse.count()===1){for(const t of await spouse.locator('.form-item__title').allTextContents()){const it=field(spouse,t);await it.evaluate((e,tag)=>e.dataset.qiyuanChecked=tag,runTag);report.push({label:t,group:'配偶情况',status:'notApplicable',reason:'本人未婚，无配偶；不捏造配偶生日或身份'});}}
const papers=forms('刊物/会议名称');if(profile.noPublications&&await papers.count()===1){for(const t of ['标题','刊物/会议名称','个人作用'])await set(papers,t,'无');const it=field(papers,'发表年份');await it.evaluate((e,tag)=>e.dataset.qiyuanChecked=tag,runTag);report.push({label:'发表年份',group:'论文、报告',status:'notApplicable',reason:'无论文，不编造发表日期'});}
const additions=forms('第一志愿研究方向');if(await additions.count()===1){await set(additions,'第一志愿研究方向','002-微电子中心');if(profile.aircasFacts.accept_role_adjustment===true)await set(additions,'服从调剂','是');}
if(await thesis.count()===1)for(const t of ['博士学位论文答辩年月','博士后出站报告答辩年月']){await field(thesis,t).evaluate((e,tag)=>e.dataset.qiyuanChecked=tag,runTag);report.push({label:t,group:'学位论文',status:'notApplicable',reason:'无该阶段学历，不编造日期'});} const all=page.locator('.ux-standard-form');for(let i=0;i<await all.count();i++){for(const t of await all.nth(i).locator('.form-item__title').allTextContents())if(await field(all.nth(i),t).getAttribute('data-qiyuan-checked')!==runTag)report.push({label:t,group:'启元待核对',status:'pending',reason:'尚无确认映射或需核对现有内容'});}
return {fields:report,elapsedMs:Date.now()-started,counts:Object.fromEntries(['filled','ready','pending','existing','failed','notApplicable'].map(s=>[s,report.filter(f=>f.status===s).length]))};}
module.exports={isQiyuan,fillQiyuan};





